### ISSUE TITLE
graceful shutdown for tornado is not thread-safe.

### ISSUE THREAD

**Issue by ccl0326** [benoitc/gunicorn#1032]
ERROR:tornado.application:Exception in callback None
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado/ioloop.py", line 840, in start
    handler_func(fd_obj, events)
  File "/Library/Python/2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/tornado/netutil.py", line 211, in accept_handler
    connection, address = sock.accept()
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
…
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
  File "/Library/Python/2.7/site-packages/gunicorn-19.3.0-py2.7.egg/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
RuntimeError: maximum recursion depth exceeded

The testing script:

import os
import requests
import signal
import threading
import time

from optparse import OptionParser

class ReqThread(threading.Thread):
    def run(self):
        while True:
            r = requests.get('http://127.0.0.1:8000')
            print r.status_code

if __name__ == '__main__':
    parser = OptionParser()
    parser.add_option("-p", "--pid", dest="pid", help="")
    (options, args) = parser.parse_args()
    os.kill(int(options.pid), signal.SIGTERM)
    for x in xrange(0, 10000):
        thread = ReqThread()
        thread.start()
    time.sleep(10)

The implementation for graceful shutdown of tornado is not thread-safe.
PeriodicCallback and server.stop are both not thread-safe when ioloop is running.

**Comment by berkerpeksag** [comment]
Fixed by https://github.com/benoitc/gunicorn/commit/d9b89599cce55036bd3fc13258e92626a5e1ba6a.
