### ISSUE TITLE
Upgrade with USR2 not supported with unix socket

### ISSUE THREAD

**Issue by frensjan** [benoitc/gunicorn#1109]
Hi,

I'm trying to use the USR2 signal to reload my app after a deployment. I'm running on CentOS 7. I'm systemd to manage the gunicorn service as well as a unix socket for communication between nginx and gunicorn closely following http://gunicorn-docs.readthedocs.org/en/latest/deploy.html#systemd.

However when I attempt to send the USR2 signal, no new arbiter is started and the following error appears in the systemd journal:

```
Aug 31 19:33:01 xxxxx-qa-web-1 systemd[1]: Reloaded gunicorn daemon for xxxxx.
-- Subject: Unit gunicorn-xxxxx.service has finished reloading its configuration
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit gunicorn-xxxxx.service has finished reloading its configuration
-- 
-- The result is done.
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: Traceback (most recent call last):
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: File "/var/www/xxxxx/bin/gunicorn", line 11, in <module>
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: sys.exit(run())
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: File "/var/www/xxxxx/lib/python3.3/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: File "/var/www/xxxxx/lib/python3.3/site-packages/gunicorn/app/base.py", line 189, in run
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: super(Application, self).run()
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: File "/var/www/xxxxx/lib/python3.3/site-packages/gunicorn/app/base.py", line 72, in run
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: Arbiter(self).run()
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: File "/var/www/xxxxx/lib/python3.3/site-packages/gunicorn/arbiter.py", line 171, in run
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: self.start()
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: File "/var/www/xxxxx/lib/python3.3/site-packages/gunicorn/arbiter.py", line 130, in start
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: self.LISTENERS = create_sockets(self.cfg, self.log)
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: File "/var/www/xxxxx/lib/python3.3/site-packages/gunicorn/sock.py", line 193, in create_sockets
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: listeners.append(sock_type(addr, conf, log, fd=fd))
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: File "/var/www/xxxxx/lib/python3.3/site-packages/gunicorn/sock.py", line 31, in __init__
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: self.sock = self.set_options(sock, bound=(fd is not None))
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: File "/var/www/xxxxx/lib/python3.3/site-packages/gunicorn/sock.py", line 78, in set_options
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
Aug 31 19:37:30 xxxxx-qa-web-1 gunicorn[9947]: OSError: [Errno 95] Operation not supported
```

I'm using the following versions:
* **gunicorn** 19.3.0
* **python** 3.3.2
* **systemd** 208-20.el7_1.5

My systemd service definition is:
```
[Unit]
Description=gunicorn daemon for xxxxx
Requires=gunicorn-xxxxx.socket
After=network.target

[Service]
User=nginx
Group=nginx
WorkingDirectory=/var/www/xxxxx
Environment="DJANGO_SETTINGS_MODULE=xxxxx.settings.qa"
PIDFile=/var/run/gunicorn/xxxxx.pid
ExecStartPre=/var/www/xxxxx/bin/gunicorn --chdir ./current --config current/xxxxx/settings/gunicorn.py xxxxx.wsgi --check-conf
ExecStart=/var/www/xxxxx/bin/gunicorn --chdir ./current --config current/xxxxx/settings/gunicorn.py --log-config /var/www/xxxxx/logging.conf --pid /var/run/gunicorn/xxxxx.pid xxxxx.wsgi
ExecReload=/bin/kill -s HUP $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```

The systemd socket definition is: 
```
[Unit]
Description=gunicorn socket for xxxxx

[Socket]
ListenStream=/var/run/gunicorn/xxxxx.socket

[Install]
WantedBy=sockets.target
```

My gunicorn config is:
```python
import multiprocessing

workers = multiprocessing.cpu_count() * 2 + 1
threads = 2
timeout = 300
loglevel = 'info'
```

I've logged the `addr` and `sock_type` in [the loop](https://github.com/benoitc/gunicorn/blob/master/gunicorn/sock.py#L188) over the already bound sockets in `create_sockets` ([gunicorn/sock.py](https://github.com/benoitc/gunicorn/blob/master/gunicorn/sock.py)); their values are `('127.0.0.1', 8000)` and `<class 'gunicorn.sock.TCPSocket'>` respectively.

As `laddr` is taken from the `address` property of the `conf` argument I went digging up through the call stack and developed the suspicion that the default bind address is used (which is 127.0.0.1:8000) as I haven't provided a bind address (in ExecStart in the systemd service definition nor in my gunicorn settings).

On the initial start of gunicorn this isn't an issue since the `GUNICORN_FD` environment variable is not set. However, in [reexec](https://github.com/benoitc/gunicorn/blob/a132ca97c87a30d766f07a8c41a29838d8963631/gunicorn/arbiter.py#L362) the file descriptors are passed to the new arbiter without any information on what type of socket the file descriptor is for.

I guess that somehow adding the type of the socket to the GUNICORN_FD environment variable which can be used in `create_socket` would be a way forward.

Can anyone confirm this? If it is confirmed, could a fix be developed?

**Comment by tilgovi** [comment]
I believe #1185 should fix this.

**Comment by benoitc** [comment]
@tilgovi indeed. closing the issue.
