### ISSUE TITLE
NameError: global name 'fileno' is not defined

### ISSUE THREAD

**Issue by bristi** [benoitc/gunicorn#1179]
Serving a Django or Flask application throws exception NameError: global name 'fileno' is not defined. Version 19.4.3 works.

This is my stack trace:

[2016-01-04 22:06:19 +0100] [66398] [ERROR] Error handling request /static/js/admin_events.js
Traceback (most recent call last):
  File "/Users/brian/VEnvs/flask-newsocketio/lib/python2.7/site-packages/gunicorn/workers/async.py", line 52, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/Users/brian/VEnvs/flask-newsocketio/lib/python2.7/site-packages/gunicorn/workers/async.py", line 110, in handle_request
    resp.write_file(respiter)
  File "/Users/brian/VEnvs/flask-newsocketio/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 396, in write_file
    if not self.sendfile(respiter):
  File "/Users/brian/VEnvs/flask-newsocketio/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 360, in sendfile
    offset = os.lseek(fileno, 0, os.SEEK_CUR)
NameError: global name 'fileno' is not defined

Also see thread (I am not the creator) :
http://stackoverflow.com/questions/34600218/gunicorn-nameerror-global-name-fileno-is-not-defined/34600808#34600808

Let me know if I can help out further.

cheers,
-brian

**Comment by jeffbean** [comment]
Hit this with python 3.3 as well

```
 [2016-01-04 22:35:05 +0000] [26] [ERROR] Error handling request /static/img/favicon.ico
Traceback (most recent call last):
 File "/usr/local/lib/python3.3/site-packages/gunicorn/workers/sync.py", line 130, in handle
     self.handle_request(listener, req, client, addr)
   File "/usr/local/lib/python3.3/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
     resp.write_file(respiter)
   File "/usr/local/lib/python3.3/site-packages/gunicorn/http/wsgi.py", line 396, in write_file
     if not self.sendfile(respiter):
   File "/usr/local/lib/python3.3/site-packages/gunicorn/http/wsgi.py", line 360, in sendfile
     offset = os.lseek(fileno, 0, os.SEEK_CUR)
 NameError: global name 'fileno' is not defined
```

**Comment by jmoiron** [comment]
https://github.com/benoitc/gunicorn/pull/1178 should fix this

**Comment by berkerpeksag** [comment]
Thanks for the report. @jmoiron is right. This is fixed in master. We will release a new version tomorrow.
