### ISSUE TITLE
GeventSocketIOWorker invalid or not found

### ISSUE THREAD

**Issue by ocervell** [benoitc/gunicorn#1315]
When I try to use the GeventSocketIOWorker like:

`gunicorn --worker-class socketio.sgunicorn.GeventSocketIOWorker ui:app`

Get following exception:

```
class uri 'socketio.sgunicorn.GeventSocketIOWorker' invalid or not found:

[Traceback (most recent call last):
  File "/Users/ocervell/.virtualenvs/flask/lib/python2.7/site-packages/gunicorn/util.py", line 142, in load_class
    mod = import_module('.'.join(components))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named socketio.sgunicorn
]

```

**Comment by ocervell** [comment]
I figured I had to use `geventwebsocket.gunicorn.workers.GeventWebSocketWorker` worker instead. Not sure why or how they're different but this one seems to be working.
