### ISSUE TITLE
gunicorn systemd and max_requests issues

### ISSUE THREAD

**Issue by fusionbeam** [benoitc/gunicorn#1318]
Hi guys,

I have the following gunicorn systemd configuration:

/etc/systemd/system/my-app.socket 

```
[Unit]
Description=my-app socket

[Socket]
ListenStream=/run/my-app/socket

[Install]
WantedBy=sockets.target
```

/etc/systemd/system/my-app.service 

```
[Unit]
Description=my-app daemon
Requires=my-app.socket
After=network.target

[Service]
PIDFile=/run/my-app/pid
User=ubuntu
Group=ubuntu
Environment="RUN_ENV=live"
WorkingDirectory=/home/ubuntu/myapp
ExecStart=/home/ubuntu/myapp/env/bin/gunicorn -c /home/ubuntu/myapp/settings/gunicorn_live.py wsgi:app
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```

and

/home/ubuntu/myapp/settings/gunicorn_live.py 

```
bind = "unix:/run/my-app/socket"
workers = 6
threads = 2
timeout = 600
max_requests = 2048
max_requests_jitter = 64
pidfile = "/run/my-app/pid"
```

Nginx proxy configured as 

```
cat /etc/nginx/sites-enabled/myapp

##
# Nginx site configuration generated by codesmith
##

upstream my_app_server {
        server unix:/run/my-app/socket fail_timeout=120;
}
server {

    listen          x.x.x.x:80;
    server_name     xxxx.io;

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root html;
    }


    location / { try_files $uri @flaskapp; }
    location @flaskapp {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_redirect off;

            proxy_pass   http://my_app_server;

    }
}
```

Everything works like a charm with the exception of gunicorn auto restarts when the max_requests+jitter limit is being met.
When that happens nothing shows up on any of the logs (systemd nor custom app logs), the gunicorn process is gone, the PID files are still there and nginx returns 404 complaining that the upstream request is not answered.
The only way to recover is to clean all pid files, stop the services with systemctl as if they were running and then start the services again. (Reboot also does it). 

Any pointers on how to further trouble shoot this or perhaps a solution hint?

Thanks,
Rares

**Comment by fusionbeam** [comment]
gunicorn==19.6.0

**Comment by fusionbeam** [comment]
thanks for answering.
restarting myapp.service alone does not work

the only way to restart is to stop myapp service first and then restart myapp.socket

**Comment by benoitc** [comment]
I do not understand `The only way to recover is to clean all pid files, stop the services with systemctl as if they were running and then start the services again. (Reboot also does it).`

why do you need to restart the pid? Are the workers restarted correctly when one die? What show the gunicorn logs?

**Comment by fusionbeam** [comment]
The logs indicate a successful restart. And indeed there is gunicorn process running.

```
Aug 11 08:46:20 popmetricsng gunicorn[1577]: [2016-08-11 08:46:20 +0000] [1599] [INFO] Autorestarting worker after current request.
Closing connection.
Aug 11 08:46:20 popmetricsng gunicorn[1577]: [2016-08-11 08:46:20 +0000] [1599] [INFO] Worker exiting (pid: 1599)
Aug 11 08:46:20 popmetricsng gunicorn[1577]: INIT
Aug 11 08:46:20 popmetricsng gunicorn[1577]: [2016-08-11 08:46:20 +0000] [1654] [INFO] Booting worker with pid: 1654
```

Nginx on the other hand cannot connect to the upstream socket after the autorestart.

```
2016/08/11 08:52:26 [crit] 2198#2198: *1 connect() to unix:/run/my-app/socket failed (2: No such file or directory) while connecting to upstream, client: 81.180.122.118, server: xxxx.io, request: "GET / HTTP/1.1", upstream: "http://unix:/run/my-app/socket:/", host: "xxx.io"
```

**Comment by fusionbeam** [comment]
Another observation:
restarting the gunicorn service, either manually or automatically by gunicorn deletes /run/my-app/socket and doesn't recreate it

**Comment by fusionbeam** [comment]
more diagnostics.
this is the log of starting up gunicorn. (systemctl start my-app)
despite it showing that it binds to /run/my-app/socket nu such file exists even though all gunicorn processes are running.

```
Aug 11 10:29:01 popmetricsng gunicorn[6299]: [2016-08-11 10:29:01 +0000] [6299] [DEBUG] Current configuration:
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   proxy_protocol: False
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   worker_connections: 1000
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   statsd_host: None
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   max_requests_jitter: 64
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   post_fork: <function post_fork at 0x7fc12c8b3a28>
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   pythonpath: None
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   enable_stdio_inheritance: False
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   worker_class: sync
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   ssl_version: 3
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   suppress_ragged_eofs: True
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   syslog: False
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   syslog_facility: user
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   when_ready: <function when_ready at 0x7fc12c8b3758>
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   pre_fork: <function pre_fork at 0x7fc12c8b38c0>
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   cert_reqs: 0
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   preload_app: False
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   keepalive: 2
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   accesslog: None
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   group: 1000
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   graceful_timeout: 30
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   do_handshake_on_connect: False
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   spew: False
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   workers: 6
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   proc_name: None
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   sendfile: None
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   pidfile: /run/my-app/pid
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   umask: 0
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   on_reload: <function on_reload at 0x7fc12c8b35f0>
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   pre_exec: <function pre_exec at 0x7fc12c8ba050>
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   worker_tmp_dir: None
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   post_worker_init: <function post_worker_init at 0x7fc12c8b3b90>
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   limit_request_fields: 100
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   on_exit: <function on_exit at 0x7fc12c8ba6e0>
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   config: /home/ubuntu/popmetrics/settings/gunicorn_live.py
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   logconfig: None
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   check_config: False
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   statsd_prefix:
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   proxy_allow_ips: ['127.0.0.1']
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   pre_request: <function pre_request at 0x7fc12c8ba1b8>
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   post_request: <function post_request at 0x7fc12c8ba2a8>
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   user: 1000
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   forwarded_allow_ips: ['127.0.0.1']
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   worker_int: <function worker_int at 0x7fc12c8b3cf8>
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   threads: 2
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   max_requests: 2048
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   limit_request_line: 4094
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   certfile: None
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   worker_exit: <function worker_exit at 0x7fc12c8ba410>
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   chdir: /home/ubuntu/popmetrics
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   paste: None
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   default_proc_name: wsgi:app
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   errorlog: -
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   loglevel: debug
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   capture_output: False
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   syslog_addr: udp://localhost:514
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   syslog_prefix: None
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   daemon: False
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   ciphers: TLSv1
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   on_starting: <function on_starting at 0x7fc12c8b3488>
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   worker_abort: <function worker_abort at 0x7fc12c8b3e60>
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   bind: ['unix:/run/my-app/socket']
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   raw_env: []
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   reload: False
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   limit_request_field_size: 8190
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   nworkers_changed: <function nworkers_changed at 0x7fc12c8ba578>
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   timeout: 600
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   ca_certs: None
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   django_settings: None
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   tmp_upload_dir: None
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   keyfile: None
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   backlog: 2048
Aug 11 10:29:01 popmetricsng gunicorn[6299]:   logger_class: gunicorn.glogging.Logger
Aug 11 10:29:01 popmetricsng gunicorn[6299]: [2016-08-11 10:29:01 +0000] [6299] [INFO] Starting gunicorn 19.6.0
Aug 11 10:29:01 popmetricsng gunicorn[6299]: [2016-08-11 10:29:01 +0000] [6299] [DEBUG] Socket activation sockets: unix:/run/popmetrics-app/socket
Aug 11 10:29:01 popmetricsng gunicorn[6299]: [2016-08-11 10:29:01 +0000] [6299] [DEBUG] Arbiter booted
Aug 11 10:29:01 popmetricsng gunicorn[6299]: [2016-08-11 10:29:01 +0000] [6299] [INFO] Listening at: unix:/run/popmetrics-app/socket (6299)
Aug 11 10:29:01 popmetricsng gunicorn[6299]: [2016-08-11 10:29:01 +0000] [6299] [INFO] Using worker: threads
Aug 11 10:29:01 popmetricsng gunicorn[6299]: [2016-08-11 10:29:01 +0000] [6306] [INFO] Booting worker with pid: 6306
Aug 11 10:29:01 popmetricsng gunicorn[6299]: [2016-08-11 10:29:01 +0000] [6307] [INFO] Booting worker with pid: 6307
```

**Comment by fusionbeam** [comment]
My conclusion so far is that gunicorn requires support for working with systemd auto-activated sockets. It should not remove/create the socket files when stopping/starting.

**Comment by tilgovi** [comment]
@fusionbeam you could test if maybe #1310 fixes your issue.

**Comment by tilgovi** [comment]
@fusionbeam any possibility to test #1310?

**Comment by krtek4** [comment]
I had a similar issue where the socked was disappearing when the max_request was met using supervisor to manage the gunicorn process.

I switched to using systemd a few days ago, and the same issue is present, so I don't think it is related to systemd itself.

I am using gunicorn 19.6 with the sync workers.

I will be glad to test with any fix you have ready, but as I am a bit swamped under work right now it would be great if you could explain to me how to do that. FYI I have everything in a virtualenv installed with pip, so a pip command to issue in order to upgrade would be best.

Sorry I cannot be of more help right now.

**Comment by tilgovi** [comment]
@krtek4 if you want to test with gunicorn's master branch and you use a pip requirements file you can change it to say `https://github.com/benoitc/gunicorn/archive/master.zip#egg=gunicorn` I think.

**Comment by krtek4** [comment]
Do I need to change anything in the configuration to use the `master` branch. I updated it with `pip` and I have the following error when starting gunicorn:

> [2017-01-05 09:32:58 +0100] [26318] [INFO] Worker exiting (pid: 26318)
[2017-01-05 09:32:58 +0100] [26319] [INFO] Booting worker with pid: 26319
[2017-01-05 09:32:58 +0100] [26319] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/srv/www/chauve/ENV/lib/python3.4/site-packages/gunicorn/arbiter.py", line 574, in spawn_worker
    worker.init_process()
  File "/srv/www/chauve/ENV/lib/python3.4/site-packages/gunicorn/workers/gthread.py", line 109, in init_process
    super(ThreadWorker, self).init_process()
  File "/srv/www/chauve/ENV/lib/python3.4/site-packages/gunicorn/workers/base.py", line 140, in init_process
    self.run()
  File "/srv/www/chauve/ENV/lib/python3.4/site-packages/gunicorn/workers/gthread.py", line 213, in run
    events = self.poller.select(1.0)
  File "/usr/lib/python3.4/selectors.py", line 424, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
ValueError: maxevents must be greater than 0, got 0

For reference, here is the configuration I use :

```
 ± cat /etc/systemd/system/chauve.service 
[Unit]
Description=CHauve Gunicorn daemon
After=network.target

[Service]
User=www-data
Group=www-data
WorkingDirectory=/srv/www/chauve/
ExecStart=/srv/www/chauve//ENV/bin/gunicorn --error-logfile ./logs/error.log -c ./server_config/gunicorn.conf.py --preload chauvepourlabonnecause.wsgi:application


[Install]
WantedBy=multi-user.target
```

```
 ± cat server_config/gunicorn.conf.py 
bind = 'unix:/tmp/gunicorn-chauve.sock'
workers = 1
threads = 2
timeout = 600
max_requests = 5
log_level = 'info'
```

**Comment by benoitc** [comment]
fixed in master. also no activity since awhile. closing the issue.
