### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by nashuiliang** [benoitc/gunicorn#1324]
run: `gunicorn --config __pycache__/a.gunicorn.conf.cpython-35.pyc a:app`
version: `python3.5.2`
err: 

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/gunicorn/app/base.py", line 95, in get_config_from_filename
    execfile_(filename, cfg, cfg)
  File "/usr/lib/python3.5/site-packages/gunicorn/_compat.py", line 69, in execfile_
    code = _get_codeobj(fname)
  File "/usr/lib/python3.5/site-packages/gunicorn/_compat.py", line 53, in _get_codeobj
    code_obj = marshal.loads(data[8:])
ValueError: bad marshal data (unknown type code)
```

when I run in python2, it's right.
From the article (PEP 3147) https://www.python.org/dev/peps/pep-3147/#background, **Byte code files contain two 32-bit big-endian numbers followed by the marshaled code object.**

---

in python3.5, I change the file _/usr/lib/python3.5/site-packages/gunicorn/_compat.py_ at   **Line 32**  to `code_obj = marshal.loads(data[12:])`. It's ok.

**Comment by benoitc** [comment]
@berkerpeksag any idea? did something changed ?

@nashuiliang how did you install the package? On which machine?

**Comment by berkerpeksag** [comment]
The OP's fix looks good to me.

**Comment by nashuiliang** [comment]
`# uname -a`
> Linux arch 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux

`# pip3 install gunicorn`

**Comment by tilgovi** [comment]
If we can fix it so that it works on on Python2 and Python3 then we should do it!

**Comment by benoitc** [comment]
@berkerpeksag what's the correct way to check the python version there ? will it be for anything > 3.5 ?

**Comment by berkerpeksag** [comment]
I think the easiest way to check it would be

```
header_size = 12 if PY3 else 8
```

I haven't had a chance to test it, but I think the same line would fail any Python 3 version newer than 3.2.

I'll try to address this before the next release.

**Comment by dmiyakawa** [comment]
It seems pyc after 3.3 has 12bytes header instead of 8. See the following for more detail.

* http://qiita.com/amedama/items/698a7c4dbdd34b03b427
* http://code.activestate.com/recipes/577880-inspect-a-pyc-file/

**Comment by tilgovi** [comment]
Maybe we should push the minimum py3 version when we release 2.0, in addition to dropping py2 support.

**Comment by tilgovi** [comment]
It just seems to me like the value of supporting the first few py3 releases is low, but I don't know what actual usage looks like.

**Comment by benoitc** [comment]
should be fixed in 20x. closing the issue since no activity happened since awhile. Please open a new ticket if  there is still an issue.
