### ISSUE TITLE
Gunicorn giving syntax error for my configuration file

### ISSUE THREAD

**Issue by jameelgrand** [benoitc/gunicorn#1341]
my config file 

   
```
[loggers]
    keys=root, gunicorn.error, gunicorn.access
    
    [handlers]
    keys=console, error_file, access_file
    
    [formatters]
    keys=generic, access
    
    [logger_root]
    level=INFO
    handlers=console
    
    [logger_gunicorn.error]
    level=INFO
    handlers=error_file
    propagate=1
    qualname=gunicorn.error
    
    [logger_gunicorn.access]
    level=INFO
    handlers=access_file
    propagate=0
    qualname=gunicorn.access
    
    [handler_console]
    class=StreamHandler
    formatter=generic
    args=(sys.stdout, )
    
    [handler_error_file]
    class=logging.FileHandler
    formatter=generic
    args=('/tmp/gunicorn.error.log',)
    
    [handler_access_file]
    class=logging.FileHandler
    formatter=access
    args=('/tmp/gunicorn.access.log',)
    
    [formatter_generic]
    format=%(asctime)s [%(process)d] [%(levelname)s] %(message)s
    datefmt=%Y-%m-%d %H:%M:%S
    class=logging.Formatter
    
    [formatter_access]
    format=%(message)s
    class=logging.Formatter
```

My command to execute 

 `  gunicorn --env DJANGO_SETTINGS_MODULE=myproject.settings myproject.wsgi --log-level debug --log-file=- -c file:gunicorn_log.conf`

Getting this error 

   
 ```
Failed to read config file: gunicorn_log.conf
    Traceback (most recent call last):
      File "/home/jameel/django-env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 93, in get_config_from_filename
        execfile_(filename, cfg, cfg)
      File "/home/jameel/django-env/local/lib/python2.7/site-packages/gunicorn/_compat.py", line 91, in execfile_
        return execfile(fname, *args)
      File "gunicorn_log.conf", line 27
        class=StreamHandler
             ^
    SyntaxError: invalid syntax
```

I was followed as per example in github [link](https://github.com/benoitc/gunicorn/blob/master/examples/logging.conf)

**Comment by jamadden** [comment]
The [`-c` option](http://docs.gunicorn.org/en/latest/settings.html#config-file) specifies a *gunicorn* configuration file, not a `logging` `.ini`-style configuration file. The gunicorn config file uses Python syntax, and configures gunicorn settings. There is [an example](https://github.com/benoitc/gunicorn/blob/master/examples/example_config.py).

**Comment by jameelgrand** [comment]
yea got it . I need to give "--log-config" instead of "-c" thank you so much
