### ISSUE TITLE
Django 1.10's BaseCommand no longer has option_list -  breaking run_gunicorn

### ISSUE THREAD

**Issue by naegelin** [benoitc/gunicorn#1355]
The current Django 1.10 release has removed support for BaseCommand.option_list. Instead, a new add_arguments() method has been added starting in 1.8

see: https://github.com/benoitc/gunicorn/blob/master/gunicorn/management/commands/run_gunicorn.py#L84

```
Traceback (most recent call last):
  File "/var/www/mighty/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/var/www/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/var/www/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/env/local/lib/python2.7/site-packages/gunicorn/management/commands/run_gunicorn.py", line 83, in <module>
    class Command(BaseCommand):
  File "/var/www/env/local/lib/python2.7/site-packages/gunicorn/management/commands/run_gunicorn.py", line 84, in Command
    option_list = BaseCommand.option_list + GUNICORN_OPTIONS
AttributeError: type object 'BaseCommand' has no attribute 'option_list' ```

**Comment by berkerpeksag** [comment]
Thanks for the report. `run_gunicorn` has been deprecated a long time ago and it will be removed in Gunicorn 20 (see #1076) Please use the `gunicorn` CLI.
