### ISSUE TITLE
no access log when gunicorn work class as tornado

### ISSUE THREAD

**Issue by northlandsnow** [benoitc/gunicorn#1358]
I has a gunicorn config as below:
```
bind = '127.0.0.1:3000'
workers = 2
worker_class = 'tornado'
proc_name = 'dome'
loglevel = 'debug'
pidfile = './gunicorn.pid'
accesslog = './log/access.log'
errorlog = './log/error.log'
raw_env = 'env=dev'
```
I do not find any access log when debugging.
But I change worker_class as gevent,  the access log is work!

**Comment by benoitc** [comment]
maybe tornado is overriding the log config? I will check

**Comment by yunstanford** [comment]
yeah, i have the same issue.

**Comment by berkerpeksag** [comment]
I couldn't get tornado worker work with gunicorn master and tornado 4.4.2 by the way:

```py
ERROR:tornado.application:Uncaught exception
Traceback (most recent call last):
  File "/home/berker/projects/gunicorn/venv34/lib/python3.4/site-packages/tornado/http1connection.py", line 238, in _read_message
    delegate.finish()
  File "/home/berker/projects/gunicorn/venv34/lib/python3.4/site-packages/tornado/httpserver.py", line 287, in finish
    self.server.request_callback(self.request)
  File "/home/berker/projects/gunicorn/venv34/lib/python3.4/site-packages/tornado/wsgi.py", line 304, in __call__
    request.connection.write_headers(start_line, header_obj, chunk=body)
  File "/home/berker/projects/gunicorn/venv34/lib/python3.4/site-packages/tornado/http1connection.py", line 398, in write_headers
    data += self._format_chunk(chunk)
  File "/home/berker/projects/gunicorn/venv34/lib/python3.4/site-packages/tornado/http1connection.py", line 410, in _format_chunk
    "Tried to write more data than Content-Length")
tornado.httputil.HTTPOutputError: Tried to write more data than Content-Length
```

**Comment by ankitgarg2212gmailcom** [comment]
Is there any ETA for fix of this issue? or any workaround for the same.

**Comment by benoitc** [comment]
Closing - tornado workers handle requests independently and don't use gunicorn's access logging. This is expected behavior for third-party worker classes.
