### ISSUE TITLE
Not able to start flask app with gunicorn on Docker container

### ISSUE THREAD

**Issue by patelkunal** [benoitc/gunicorn#1383]
Following is my configuration for Docker image 

```Docker
FROM python:3.5.2 

RUN apt-get update && apt-get install -y vim nginx gunicorn supervisor
RUN pip install --upgrade pip
RUN pip install flask
```

And I have simple flask application (hello-world) and starting same using following command.
```bash
gunicorn hello:app
```

And it fails with following error - I believe its something to do with python's version mismatching. Since I have imported docker image for version 3.5.2 from official python repository and apt-get is installing 2.7 version of gunicorn. It could be simple configuration changes but I am not able to figure out.
```
Traceback (most recent call last):
  File "/usr/bin/gunicorn", line 9, in <module>
    load_entry_point('gunicorn==19.0.0', 'console_scripts', 'gunicorn')()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 166, in run
    super(Application, self).run()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 71, in run
    Arbiter(self).run()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 169, in run
    self.manage_workers()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 477, in manage_workers
    self.spawn_workers()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 537, in spawn_workers
    time.sleep(0.1 * random.random())
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 209, in handle_chld
    self.reap_workers()
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 459, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

**Comment by zhipcui** [comment]
According to the error log, master process receive it's child process 'SIGCHLD' signal for some reasons. I recommend you change your Docker image conf like this.

From:
        linux distribution like ubuntu
run:
      install Virtualenv # control python version and isolated envirment
      install gunicorn & flask &....
 
hope this work

**Comment by tilgovi** [comment]
With a docker container you should probably just install gunicorn using `pip` rather than `apt` to ensure you get the latest gunicorn and so that it uses the default `python`.
