### ISSUE TITLE
Working with Heroku, Programming in Flask with gunicorn and a little of socketio I have this issue:

### ISSUE THREAD

**Issue by jaguarulises** [benoitc/gunicorn#1419]
[10] [ERROR] Error handling request /socket.io/?EIO=3&transport=websocket
Traceback (most recent call last):
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/async.py", line 52, in handle
self.handle_request(listener_name, req, client, addr)
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/async.py", line 112, in handle_request
resp.close()
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 418, in close
self.send_headers()
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 334, in send_headers
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 315, in default_headers
tosend = self.default_headers()
elif self.should_close():
File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 238, in should_close
if self.status_code < 200 or self.status_code in (204, 304):
AttributeError: 'Response' object has no attribute 'status_code'

Thanks for reading this,
see you later,
-JaguarUlises.

**Comment by benoitc** [comment]
which worker? Did you tried the latest master?

**Comment by jaguarulises** [comment]
I have this in mi Procfile:

web: gunicorn -k eventlet main:app

and the eventlet is working fine with the patch, if I write -w 1 in that line, the server goes down.
Only see the issue when the server socketio is working with the java socketio web client.

Thanks for answer.

**Comment by benoitc** [comment]
did you try the latest master?

**Comment by stefaang** [comment]
This is fixed with https://github.com/benoitc/gunicorn/pull/1406

**Comment by jaguarulises** [comment]
Thank you guys for your time. I appreciate your work. (y)
