### ISSUE TITLE
19.7 release

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#1471]
ticket to track the release of the 19.7 version

- [x] add Project management page
- [x] triage bugs in new projects
- [x] prepare changelog

**Comment by benoitc** [comment]
project page available: https://github.com/benoitc/gunicorn/wiki/Project-management

**Comment by benoitc** [comment]
changelog is done. release will be done tomorrow

**Comment by benoitc** [comment]
19.7 released

**Comment by marcinkuzminski** [comment]
In one of our servers, running gunicorn. We noticied that after a Postgres connection problem we still got this exception:

```
2018-02-12 02:01:02 [1769] [ERROR] Exception in post_request hook
Traceback (most recent call last):
  File "/nix/store/ciwd5mg0mkcnw4bwhzap8g3k9630a0mp-python2.7-gunicorn-19.7.1/lib/python2.7/site-packages/gunicorn/workers/async.py", line 144, in handle_request
    self.cfg.post_request(self, req, environ, resp)
  File "/home/xxx/conf/gunicorn_prod.py", line 132, in post_request
    worker.nr, req.method, req.path, resp.status_code, total_time)
AttributeError: 'Response' object has no attribute 'status_code'
```

Here's the post_request code:

```
def post_request(worker, req, environ, resp):
    total_time = time.time() - worker.start_time
    worker.log.debug(
        "GNCRN POST WORKER [cnt:%s]: %s %s resp: %s, Load Time: %.3fs",
        worker.nr, req.method, req.path, resp.status_code, total_time)
```
