### ISSUE TITLE
Inconsistent error log format for propagated application errors

### ISSUE THREAD

**Issue by tuukkamustonen** [benoitc/gunicorn#1476]
I'm seeing following:

```
[2017-03-03 13:13:44 +0000] [1720] [INFO] Starting gunicorn 19.6.0
[2017-03-03 13:13:44 +0000] [1720] [INFO] Listening at: http://0.0.0.0:8000 (1720)
[2017-03-03 13:13:44 +0000] [1720] [INFO] Using worker: sync
[2017-03-03 13:13:44 +0000] [1723] [INFO] Booting worker with pid: 1723
[2017-03-03 13:24:07,770] ERROR in app: Exception on /admin-ui/node/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.4/dist-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flask_admin/model/base.py", line 1818, in index_view
    view_args.search, view_args.filters)
  File "/usr/local/lib/python3.4/dist-packages/flask_admin/contrib/peewee/view.py", line 385, in get_list
    query = f.apply(query, f.clean(value))
  File "/usr/local/lib/python3.4/dist-packages/fs/csm/admin_ui/admin_ui.py", line 77, in apply
    key, value = v.split(':')
ValueError: need more than 1 value to unpack
```

The bug here (in my own code) is not the problem but error log format - why does it change when logging errors propagated from the application?

Normally it's

```
[2017-03-03 13:13:44 +0000] [1723] [INFO] Booting worker with pid: 1723
```

But then for propagated exception it turns into:

```
[2017-03-03 13:24:07,770] ERROR in app: Exception on /admin-ui/node/ [GET]
...
```

(It even uses different timetsamp here, with millisecond precision.)

Why not:

```
[2017-03-03 13:24:07 +0000] [1723] [ERROR] ERROR in app: Exception on /admin-ui/node/ [GET]
...
```

Using inconsistent syntax screws up log pattern matching and alarming.

Also, there is `--access-logformat` so why not `--error-logformat`?

(I think I might be able to customize these by `--log-config` but the default behavior seems weird.)

**Comment by tuukkamustonen** [comment]
I was accidentally running newer version of Flask (`0.12`) that changes logging behavior somewhat. I am not quite sure what happens but probably Flask interferes with logging here somehow. Closing this now - will re-check when upgrading to latest flask...
