### ISSUE TITLE
gevent + inotify reload engine don't work together

### ISSUE THREAD

**Issue by sevein** [benoitc/gunicorn#1494]
I'm trying to move my app from synchronous workers to  `--worker-class gevent`. It seems to be working but when combined with `--reload` (which I used to use before), I see the following error:

```
[2017-04-03 21:35:31 +0000] [7] [INFO] Starting gunicorn 19.7.1
[2017-04-03 21:35:31 +0000] [7] [INFO] Listening at: http://0.0.0.0:8000 (7)
[2017-04-03 21:35:31 +0000] [7] [INFO] Using worker: gevent
[2017-04-03 21:35:31 +0000] [12] [INFO] Booting worker with pid: 12
[2017-04-03 21:35:31 +0000] [12] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 123, in init_process
    self.reloader = reloader_cls(callback=changed)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/reloader.py", line 82, in __init__
    self._watcher = Inotify()
  File "/usr/local/lib/python2.7/site-packages/inotify/adapters.py", line 44, in __init__
    self.__epoll = select.epoll()
AttributeError: 'module' object has no attribute 'epoll'
[2017-04-03 21:35:31 +0000] [12] [INFO] Worker exiting (pid: 12)
[2017-04-03 21:35:31 +0000] [7] [INFO] Shutting down: Master
[2017-04-03 21:35:31 +0000] [7] [INFO] Reason: Worker failed to boot.
```

This is not reproducible when I use `--reload-engine poll`.

Environment:
- gunicorn 19.7.1
- Python 2.7.13
- futures 3.0.5
- gevent 1.2.1
- inotify 0.2.8

**Comment by jamadden** [comment]
When the system is monkey-patched, gevent explicitly removes the function `select.epoll` (when it exists) because it is not cooperative (blocks the whole process). Modules like `selectors` inspect the functions available in the `select` module to determine what to use as the default implementation, so if we don't do that then things block unexpectedly.

It looks like `inotify` is assuming the existence of the `epoll` function when it's not there. And it also looks like gunicorn is assuming that if `inotify` is installed, it can be unconditionally used. I would suggest that some code, somewhere, needs to perform a runtime check before attempting to use this functionality...after all, it appears that `inotify` can be installed on platforms (like OS X) that don't support `epoll` in the first place! (You get an AttributeError at runtime, which gunicorn isn't prepared to deal with.)

In the meantime you can try the `--reloader-engine` argument set to `poll` to workaround this issue.

**Comment by sevein** [comment]
Thanks @jamadden,

> In the meantime you can try the --reloader-engine argument set to poll to workaround this issue.

That's exactly what I'm doing. I prefer having gevent workers over inotify's reload engine but it would be awesome to have both :)

**Comment by jamadden** [comment]
> That's exactly what I'm doing. 

Yeah, sorry, I missed that line in the initial comment at first.

> it would be awesome to have both :)

gevent would need to grow a cooperative, non-blocking version of the `select.epoll` object for that to happen. Given that epoll is more sophisticated than select or poll (e.g., support for edge triggered *and* level triggered events), I don't know if we can emulate that close enough with the capabilities that libev exposes (we'd need to pass the stdlib tests when monkey-patched), and I don't know what the performance characteristics would be (and if the subtle differences would break apps). But I also don't know that anyone has tried 😄

**Comment by sevein** [comment]
Oh no problem and thanks for your time!

**Comment by benoitc** [comment]
maybe we can make a worker override the reload function used in the worker to use it's own way to wait for the changes? Ie having something specific for workers like gevent/eventlet?

**Comment by jamadden** [comment]
> maybe we can make a worker override the reload function used in the worker to use it's own way to wait for the changes?

That seems possible. gevent does provide stat watchers, based on libev's same concept. On Linux they are implemented with inotify, everywhere else they're implemented with timer-based polling. (If/when the libuv backend goes active, they could be implemented with kqueue on BSD-derived platforms and CoreFoundation on macOS.) 

The problem is that they're pretty much undocumented on the gevent side of things.

**Comment by jamadden** [comment]
I haven't really looked into it, beyond digging up the [one test](https://github.com/gevent/gevent/blob/master/src/greentest/test__core_stat.py) that I could think of that exercises the functionality.  The [libev docs](http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#code_ev_stat_code_did_the_file_attri) should basically apply.

**Comment by philfreo** [comment]
See also: #1537

**Comment by benoitc** [comment]
Closing - expected behavior. Gevent monkey-patches select.epoll which breaks inotify. Use --reload-engine=poll with gevent workers.
