### ISSUE TITLE
Python 3.6 seem to not work with my config

### ISSUE THREAD

**Issue by bart3005** [benoitc/gunicorn#1496]
Starting app excetly the same under Python 3.5 works just fine. With all packages up to date under 3.6 I seem to have issues.

Starting my app under venv with python 3.6 I get this:

gunicorn app:app -k gaiohttp

Error: class uri 'gaiohttp' invalid or not found: 

[Traceback (most recent call last):
  File "venv/lib64/python3.6/site-packages/gunicorn/util.py", line 134, in load_class
    mod = import_module('.'.join(components))
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "venv/lib64/python3.6/site-packages/gunicorn/workers/gaiohttp.py", line 14, in <module>
    from gunicorn.workers._gaiohttp import AiohttpWorker
  File "venv/lib64/python3.6/site-packages/gunicorn/workers/_gaiohttp.py", line 19, in <module>
    from aiohttp.wsgi import WSGIServerHttpProtocol as OldWSGIServerHttpProtocol
ModuleNotFoundError: No module named 'aiohttp.wsgi'
]

Is Python 3.6 supported or am I too early?

**Comment by bart3005** [comment]
Ah looks like it was removed from aiohttp 2.0

Dropped aiohttp.wsgi #1108

**Comment by berkerpeksag** [comment]
Note that #1418 is going to deprecate our gaiohttp worker in Gunicorn 19.7.

**Comment by bart3005** [comment]
Is there a replacement for  -k gaiohttp?

**Comment by berkerpeksag** [comment]
I believe it will be `-k aiohttp.worker.GunicornWebWorker`. We can probably make `-k gaiohttp`  an alias with a deprecation warning.

**Comment by benoitc** [comment]
@bart3005 there will be an asyncio worker yes
