### ISSUE TITLE
UnsupportedOperation: fileno

### ISSUE THREAD

**Issue by Colbert337** [benoitc/gunicorn#1535]
Hello~

I use Gunicorn to deploy python application - CTFd, but when I use export file function  there was an error message:

`2017-06-27 14:16:28 [20405] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 129, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/dist-packages/gunicorn/http/wsgi.py", line 326, in write_file
    fileno = respiter.filelike.fileno()
UnsupportedOperation: fileno
`
Is there a problem with the component?

Please help，thank you very much:)

**Comment by berkerpeksag** [comment]
Thank you for the detailed report. The problem here is that `io.BytesIO()` has a `fileno` method defined and it raises an `io.UnsupportedOperation` exception. However, there is the following check in the `sendfile` method which called by the `write_file` method:

```py
if not util.has_fileno(respiter.filelike):
    return False
```

And our `has_fileno` helper is already looking for an `io.UnsupportedOperation` exception:

```py
# check BytesIO case and maybe others
try:
    obj.fileno()
except (AttributeError, IOError, io.UnsupportedOperation):
    return False
```

See https://github.com/benoitc/gunicorn/blob/9eea021ac8e3a9e287d885e90e7251337a0b9bfe/gunicorn/util.py#L518 for details.

What's your Gunicorn version? Could you try the latest stable and master versions?

**Comment by benoitc** [comment]
@Colbert337 ping
