### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor (gunicorn 19.1.0, eventlet)

### ISSUE THREAD

**Issue by simoncos** [benoitc/gunicorn#1552]
My program usually went well when handling streaming data for days, but happened to breakdown. When I checked using `ps` I found no gunicorn processors existed, which means that all gunicorn workers were dead.

My gunicorn log (found one Error):
```
2017-07-24 09:54:28 [22490] [INFO] 6 workers
2017-07-24 09:54:29 [22490] [INFO] 6 workers
2017-07-24 09:54:29 [22490] [INFO] Unhandled exception in main loop:
Traceback (most recent call last):
  File "/opt/conda/envs/spamdoc/lib/python3.5/site-packages/gunicorn/arbiter.py", line 175, in run
    self.murder_workers()
  File "/opt/conda/envs/spamdoc/lib/python3.5/site-packages/gunicorn/arbiter.py", line 430, in murder_workers
    if time.time() - worker.tmp.last_update() <= self.timeout:
  File "/opt/conda/envs/spamdoc/lib/python3.5/site-packages/gunicorn/workers/workertmp.py", line 50, in last_update
    return os.fstat(self._tmp.fileno()).st_ctime
OSError: [Errno 9] Bad file descriptor

2017-07-24 09:54:33 [8124] [INFO] Worker exiting (pid: 8124)
2017-07-24 09:54:33 [8123] [INFO] Worker exiting (pid: 8123)
2017-07-24 09:54:35 [8127] [INFO] Worker exiting (pid: 8127)
```
my `gunicron_conf.py`:
```
workers = 10
worker_class = 'eventlet' # asynchronous workers
bind = '0.0.0.0:8100'
pidfile = '../gunicorn.pid'
accesslog = '../logs/gunicorn.log'
errorlog = '../logs/gunicorn.log'
reload = False # This setting is intended for development. It will cause workers to be restarted whenever application code changes.
daemon = True # Detaches the server from the controlling terminal and enters the background
timeout = 1200
```

**Comment by benoitc** [comment]
is there any way to reproduce the issue?
