### ISSUE TITLE
SSL Verification: error: [Errno 0] Error

### ISSUE THREAD

**Issue by lawja** [benoitc/gunicorn#1554]
So I am making requests to the gunicorn app that I'm running from a separate python script using the requests module. Because the gunicorn app is running with some SSL configurations I have to verify the requests, a typical post request looks like this
`requests.post(https://<ADDRESS_TO_ENDPOINT, json=<DATA>, verify=<PATH_TO_CERT>)`
If I don't verify the request i.e. set verify=False, all works fine but I'm not verifying the request which is something I'd like to be doing. When I make the request I crash with error 0, and no real help is given by the error message. When I do verify the request I point the verify path to the public key file; more can be read about verifying requests [here](http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification). THe error message from the gunicorn app is shown below.
```shell
[2017-07-27 14:52:09 +0000] [20767] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 134, in handle
    req = six.next(parser)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/message.py", line 152, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/message.py", line 52, in __init__
    unused = self.parse(self.unreader)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/message.py", line 164, in parse
    self.get_data(unreader, buf, stop=True)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/message.py", line 155, in get_data
    data = unreader.read()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/unreader.py", line 38, in read
    d = self.chunk()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/unreader.py", line 65, in chunk
    return self.sock.recv(self.mxchunk)
  File "/usr/lib/python2.7/ssl.py", line 766, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 653, in read
    v = self._sslobj.read(len)
error: [Errno 0] Error
```
Any help would be appreciated

**Comment by tilgovi** [comment]
How are you launching Gunicorn?

**Comment by tilgovi** [comment]
If you can provide more debugging information, please re-open this issue and share your gunicorn configuration as much as you can (obviously, do not share your SSL cert :)).

**Comment by usmetanina** [comment]
Please tell us, how to solve this problem

**Comment by benoitc** [comment]
@usmetanina see comment above, please open a new ticket with all the info/logs you have about it. That would help us a lot to answer to the question.

**Comment by glroman** [comment]
You connection is failing during the handshake.  This issue is discussed at length **[here](https://github.com/benoitc/gunicorn/issues/1776)**.
