### ISSUE TITLE
gevent BlockingSwitchOutError sometimes occurs when sending signal USR1

### ISSUE THREAD

**Issue by ant1g** [benoitc/gunicorn#1645]
I am encountering the following error from time to time, when sending the USR1 signal to all gunicorn processes (to rotate log files).
**Python 2.6**
**Gunicorn 19.7.1**
**Gevent 1.1.2**

I found this old issue that could potentially be related:
https://github.com/benoitc/gunicorn/issues/1044

Traceback
```
Traceback (most recent call last):
  File "/usr/lib/python/gunicorn-19.7.1-py2.6.egg/gunicorn/workers/base.py", line 177, in handle_usr1
    self.log.reopen_files()
  File "/usr/lib/python/gunicorn-19.7.1-py2.6.egg/gunicorn/glogging.py", line 351, in reopen_files
    handler.acquire()
  File "/usr/lib64/python2.6/logging/__init__.py", line 636, in acquire
    self.lock.acquire()
  File "/usr/lib64/python2.6/threading.py", line 123, in acquire
    rc = self.__block.acquire(blocking)
  File "/usr/lib/python/gunicorn-19.7.1-py2.6.egg/gunicorn/workers/base.py", line 177, in handle_usr1
    self.log.reopen_files()
  File "/usr/lib/python/gunicorn-19.7.1-py2.6.egg/gunicorn/glogging.py", line 351, in reopen_files
    handler.acquire()
  File "/usr/lib64/python2.6/logging/__init__.py", line 636, in acquire
    self.lock.acquire()
  File "/usr/lib64/python2.6/threading.py", line 123, in acquire
    rc = self.__block.acquire(blocking)
  File "gevent/_semaphore.py", line 198, in gevent._semaphore.Semaphore.acquire (gevent/gevent._semaphore.c:4117)
  File "gevent/_semaphore.py", line 226, in gevent._semaphore.Semaphore.acquire (gevent/gevent._semaphore.c:3944)
  File "gevent/_semaphore.py", line 166, in gevent._semaphore.Semaphore._do_wait (gevent/gevent._semaphore.c:3178)
  File "/usr/lib/python/gevent-1.1.2-py2.6-linux-x86_64.egg/gevent/hub.py", line 608, in switch
    switch_out()
  File "/usr/lib/python/gevent-1.1.2-py2.6-linux-x86_64.egg/gevent/hub.py", line 612, in switch_out
    raise BlockingSwitchOutError('Impossible to call blocking function in the event loop callback')
BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
```

Thanks!

**Comment by ant1g** [comment]
I monkey patched the GeventWorker class to override the **handle_usr1** method and applied the same fix as proposed here #1044, spawning a new greenlet. I do not see that error anymore. I will submit a PR.
Cheers

**Comment by ant1g** [comment]
Here https://github.com/benoitc/gunicorn/pull/1651

**Comment by benoitc** [comment]
hrm apparently it blocks while trying to log. did anyone figued why?

**Comment by ant1g** [comment]
All workers do this upon receiving the USR1 signal:
`    def handle_usr1(self, sig, frame):
        self.log.reopen_files()`

The reopen_files() function in glogging will then do this:
`with self.lock:...`

This is most likely the culprit!

**Comment by tilgovi** [comment]
In any case, doing any significant work on a signal handler is a bad idea to me. Reopening log files could mean lots of things, depending on the logging implementation and filesystem. It's probably best to merge this at #1651.

**Comment by berkerpeksag** [comment]
PR #1651 has been merged. Closing this as 'fixed'.

**Comment by johaven** [comment]
have this problem too (uwsgi 2.0.18) (gevent 1.4.0):

```
gateway "uWSGI http 1" has been buried (pid: 3993)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 3991)...
Error in atexit._run_exitfuncs:
Tue Apr 28 18:28:38 2020 - stopping gevent signals watchers for worker 1 (pid: 3991)...
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 726, in gevent._greenlet.Greenlet.join
Tue Apr 28 18:28:38 2020 - stopping gevent sockets watchers for worker 1 (pid: 3991)...
Tue Apr 28 18:28:38 2020 - main gevent watchers stopped for worker 1 (pid: 3991)...
goodbye to the gevent Hub on worker 1 (pid: 3991)
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 66, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
  File "src/gevent/_greenlet_primitives.py", line 67, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
gevent.exceptions.BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
mule 1 (pid: 3992) annihilated
worker 1 buried after 1 seconds
````
