### ISSUE TITLE
"no such option" error 

### ISSUE THREAD

**Issue by ocervell** [benoitc/gunicorn#1650]
Hi,

Everything was working great till this morning. Now gunicorn won't start, saying it doesn't recognize the `-c` flag:

```
gunicorn manage:app -c `pwd`/configs/gunicorn_dev.py

Usage
=====
  gunicorn [options] [<source> [<destination>]]

gunicorn: error: no such option: -c
```

Tried re-installing gunicorn, no success. Not sure if this is due to a version upgrade because nothing else has changed. 

Running on Centos 7 with fresh install in a virtualenv.

**Comment by berkerpeksag** [comment]
Works for me:

```sh
$ gunicorn test:app -c `pwd`/example_config.py 
[2017-11-27 18:53:35 +0300] [12471] [INFO] Starting gunicorn 19.7.1
...
```

How did you install Gunicorn? `gunicorn` might be wrapper around real Gunicorn executable since the error message is different for invalid options:

```sh
$ gunicorn test:app -x `pwd`/example_config.py 
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: unrecognized arguments: -x /home/berker/projects/gunicorn/examples/example_config.py
```

**Comment by ocervell** [comment]
Found the issue. Not gunicorn's fault though.

The following import in one of my routes was causing the issue, interfering with how Gunicorn reads the config file:




Look at the following traceback:

[2017-11-27 15:56:05 +0000] [30411] [INFO] Worker exiting (pid: 30411)
[2017-11-27 15:56:05 +0000] [30417] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/centos/.virtualenvs/ndc/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/home/centos/.virtualenvs/ndc/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/centos/.virtualenvs/ndc/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/centos/.virtualenvs/ndc/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/centos/.virtualenvs/ndc/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/centos/.virtualenvs/ndc/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/centos/.virtualenvs/ndc/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/home/centos/ndc/manage.py", line 24, in <module>
    from app import create_app
  File "/home/centos/ndc/app/__init__.py", line 3, in <module>
    from app.blueprints import BLUEPRINTS_UI, BLUEPRINTS_ADMIN, RESOURCES_API
  File "/home/centos/ndc/app/blueprints.py", line 24, in <module>
    from ui.pypi import pypi as pypi_bp
  File "/home/centos/ndc/app/ui/pypi/__init__.py", line 5, in <module>
    import routes
  File "/home/centos/ndc/app/ui/pypi/routes.py", line 3, in <module>
    import pypi_functions
  File "/home/centos/.virtualenvs/ndc/lib/python2.7/site-packages/pypi_functions/__init__.py", line 11, in <module>
    from pypipackage import PyPIPackage
  File "/home/centos/.virtualenvs/ndc/lib/python2.7/site-packages/pypi_functions/pypipackage.py", line 6, in <module>
    from rst2html5 import HTML5Writer
  File "/home/centos/.virtualenvs/ndc/bin/rst2html5.py", line 35, in <module>
    publish_cmdline(writer_name='html5', description=description)
  File "/home/centos/.virtualenvs/ndc/lib/python2.7/site-packages/docutils/core.py", line 354, in publish_cmdline
    config_section=config_section, enable_exit_status=enable_exit_status)
  File "/home/centos/.virtualenvs/ndc/lib/python2.7/site-packages/docutils/core.py", line 214, in publish
    **(settings_overrides or {}))
  File "/home/centos/.virtualenvs/ndc/lib/python2.7/site-packages/docutils/core.py", line 161, in process_command_line
    self.settings = option_parser.parse_args(argv)
  File "/usr/lib64/python2.7/optparse.py", line 1399, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/usr/lib64/python2.7/optparse.py", line 1439, in _process_args
    self._process_long_opt(rargs, values)
  File "/usr/lib64/python2.7/optparse.py", line 1514, in _process_long_opt
    option.process(opt, value, values, self)
  File "/home/centos/.virtualenvs/ndc/lib/python2.7/site-packages/docutils/frontend.py", line 342, in process
    result = optparse.Option.process(self, opt, value, values, parser)
  File "/usr/lib64/python2.7/optparse.py", line 788, in process
    self.action, self.dest, opt, value, values, parser)
  File "/usr/lib64/python2.7/optparse.py", line 808, in take_action
    self.callback(self, opt, value, parser, *args, **kwargs)
  File "/home/centos/.virtualenvs/ndc/lib/python2.7/site-packages/docutils/frontend.py", line 64, in read_config_file
    new_settings = parser.get_config_file_settings(value)
  File "/home/centos/.virtualenvs/ndc/lib/python2.7/site-packages/docutils/frontend.py", line 672, in get_config_file_settings
    parser.read(config_file, self)
  File "/home/centos/.virtualenvs/ndc/lib/python2.7/site-packages/docutils/frontend.py", line 781, in read
    CP.RawConfigParser.readfp(self, fp, filename)
  File "/usr/lib64/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib64/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: /home/centos/ndc/configs/gunicorn_dev.py, line: 2
u'import multiprocessing\n'

**Comment by caio-vinicius** [comment]
I'm on the same issue. Can't find anything, how another package can interfere on gunicorn arguments?

**Comment by caio-vinicius** [comment]
```
(env) bash$ gunicorn --chdir ./src wsgi:app
[2021-01-09 03:50:23 -0300] [24902] [INFO] Starting gunicorn 20.0.4
[2021-01-09 03:50:23 -0300] [24902] [INFO] Listening at: http://127.0.0.1:8000 (24902)
[2021-01-09 03:50:23 -0300] [24902] [INFO] Using worker: sync
[2021-01-09 03:50:23 -0300] [24904] [INFO] Booting worker with pid: 24904
Usage: gunicorn [OPTIONS]
Try 'gunicorn --help' for help.

Error: no such option: --chdir
[2021-01-09 03:50:23 -0300] [24904] [INFO] Worker exiting (pid: 24904)
[2021-01-09 03:50:23 -0300] [24905] [INFO] Booting worker with pid: 24905
Usage: gunicorn [OPTIONS]
Try 'gunicorn --help' for help.

Error: no such option: --chdir
[2021-01-09 03:50:23 -0300] [24905] [INFO] Worker exiting (pid: 24905)
^C[2021-01-09 03:50:23 -0300] [24902] [INFO] Handling signal: int
[2021-01-09 03:50:23 -0300] [24902] [INFO] Shutting down: Master

```

**Comment by caio-vinicius** [comment]
I found it! I'm using Flask-Login and somewhere in my code I'm starting a DB:

```
try:                            
   init_db_command()            
except sqlite3.OperationalError:
   pass      
```

Just comment this code and gunicorn was able to start without any error. Just cant identify why this happens with this particular call.

**Comment by snowmirage** [comment]
I'm hitting this same hour and after an entire day of google fu and trail and error I'm no closer.

I've been trying to learn a bit about flask apps and was following this guide.

https://flask.palletsprojects.com/en/1.0.x/tutorial/database/

Guessing @caio-vinicius may have been too, that "init_db_command()" call is in a db.py file you create in that guide.

`# http://flask.pocoo.org/docs/1.0/tutorial/database/
import sqlite3

import click
from flask import current_app, g
from flask.cli import with_appcontext


def get_db():
    if "db" not in g:
        g.db = sqlite3.connect(
            "sqlite_db", detect_types=sqlite3.PARSE_DECLTYPES
        )
        g.db.row_factory = sqlite3.Row

    return g.db


def close_db(e=None):
    db = g.pop("db", None)

    if db is not None:
        db.close()


def init_db():
    db = get_db()

    with current_app.open_resource("schema.sql") as f:
        db.executescript(f.read().decode("utf8"))


@click.command("init-db")
@with_appcontext
def init_db_command():
    """Clear the existing data and create new tables."""
    init_db()
    click.echo("Initialized the database.")


def init_app(app):
    app.teardown_appcontext(close_db)
    app.cli.add_command(init_db_command)
`

As @caio-vinicius pointed out if you remove the init_db_command it runs, but I can't for the life of me figure out why.

Maybe its something with the click module?
