### ISSUE TITLE
Gunicorn catches Django SSL error and shows 403 forbidden

### ISSUE THREAD

**Issue by dpetukhov** [benoitc/gunicorn#1660]
Hi guys.

I'm using django with gunicorn. I made mistake in my django config during last update here:

```python
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'root@domain.ru'
EMAIL_HOST_PASSWORD = 'myspass'
EMAIL_USE_SSL = True
```

Actually, port number is wrong. And when inside my app error occure, and Django tries to send me an email, it can't connect to that port and raises SSL exception.

But this exception is not get written in django_log, it appears in user's browser as 403 Forbidden page. And gunicorn with --log-level DEBUG shows this (nothing useful):

```
[2017-12-10 00:45:39 +0000] [20250] [DEBUG] POST /funnel/novoline/
[2017-12-10 00:45:39 +0000] [20250] [DEBUG] Error processing SSL request.
[2017-12-10 00:45:39 +0000] [20250] [DEBUG] Invalid request from ip=31.47.175.20: [Errno 1] _ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```
It is absolutely impossible to debug this and find the reason of the error in production environment.

I found that exception get catched here: https://github.com/benoitc/gunicorn/blob/ad44552a03f55c0329296963916cbef9d35ffe4f/gunicorn/workers/sync.py#L145

To view the error trace, I had to modify this piece in file  https://github.com/benoitc/gunicorn/blob/ad44552a03f55c0329296963916cbef9d35ffe4f/gunicorn/workers/base.py#L235

like this:

```
            self.log.debug(msg.format(ip=addr[0], error=str(exc)), exc_info=exc)
```

And only after that it showed me the actual trace and figured out the real error reason:

```
[2017-12-10 00:45:39 +0000] [20250] [DEBUG] POST /funnel/novoline/
[2017-12-10 00:45:39 +0000] [20250] [DEBUG] Error processing SSL request.
[2017-12-10 00:45:39 +0000] [20250] [DEBUG] Invalid request from ip=31.47.175.27: [Errno 1] _ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Traceback (most recent call last):
  File "/home/novodj/.virtualenvs/novodj/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/novodj/.virtualenvs/novodj/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 191, in handle_request
    six.reraise(*sys.exc_info())
  File "/home/novodj/.virtualenvs/novodj/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/novodj/.virtualenvs/novodj/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
  File "/home/novodj/.virtualenvs/novodj/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 216, in get_response
    'request': request
  File "/usr/lib/python2.7/logging/__init__.py", line 1178, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/home/novodj/.virtualenvs/novodj/local/lib/python2.7/site-packages/django/utils/log.py", line 117, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/home/novodj/.virtualenvs/novodj/local/lib/python2.7/site-packages/django/utils/log.py", line 120, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/home/novodj/.virtualenvs/novodj/local/lib/python2.7/site-packages/django/core/mail/__init__.py", line 97, in mail_admins
    mail.send(fail_silently=fail_silently)
  File "/home/novodj/.virtualenvs/novodj/local/lib/python2.7/site-packages/django/core/mail/message.py", line 292, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/novodj/.virtualenvs/novodj/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
    new_conn_created = self.open()
```

Can anyone tell me if this is correct that gunicorn catches django's errors and it really should show 403 (why 403?) error to user.
As admin, I would like to see real error reason in debug log.

Any suggestions?

**Comment by tilgovi** [comment]
I think this is related to #1507. Gunicorn has trouble distinguishing errors that originate in its own code from errors that originate in application code. It looks like the Django code that tries to email the admin failed with an SSL error and didn't catch it. Gunicorn caught the SSL error and returned 403.

If you'd like to open a PR to add `exc_info` to that debug log, that would be great.

I'm not sure what else to change in Gunicorn at this point.

**Comment by dpetukhov** [comment]
Yes, it's very related. And maybe you're right and adding exception info in **debug** log file will at least solve some time to a person who see similar errors. Looks like a straightforward solution. It's a debug log, right?

I will try to add pull request. Not sure if I need to add exc_info for every exception type.

Will this fix help to shed light on the https://github.com/benoitc/gunicorn/issues/1507 issue?

**Comment by dpetukhov** [comment]
Ah, I see Pull request that can fix this error:

https://github.com/benoitc/gunicorn/pull/1637/commits/29356049924e98049411d985395406ee0589e62f
