### ISSUE TITLE
Shouldn't "Unhandled exception" be logged as errors in Arbiter class

### ISSUE THREAD

**Issue by galak75** [benoitc/gunicorn#1667]
Unexpected errors are logged with the "info" level in the code below (from `Arbiter.run` method):
```
            except Exception:
                self.log.info("Unhandled exception in main loop:\n%s",
                            traceback.format_exc())
                self.stop(False)
                if self.pidfile is not None:
                    self.pidfile.unlink()
                sys.exit(-1)
```

It leads to having an "INFO" log line like the one above :
```
[2017-12-17 05:34:00 -0500] [80] [INFO] Unhandled exception in main loop:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 180, in run
    self.murder_workers()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 430, in murder_workers
    if time.time() - worker.tmp.last_update() <= self.timeout:
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/workertmp.py", line 50, in last_update
    return os.fstat(self._tmp.fileno()).st_ctime
OSError: [Errno 9] Bad file descriptor
```

And the log line is not displayed when enabling only warnings and above.

Shouldn't it be a `self.log.error` call here ?
And maybe an additional message saying all workers will be stopped abruptly (`self.stop(False)`) ?

**Comment by tilgovi** [comment]
See also #1637
