### ISSUE TITLE
Incompatibility with Python3

### ISSUE THREAD

**Issue by tjppires** [benoitc/gunicorn#1732]
I am having a problem running Heroku's websockets chat example:
https://github.com/heroku-examples/python-websockets-chat

I run the command: gunicorn -k flask_sockets.worker chat:app and it works fine in python2.7. If I switch to python3 (I'm using 3.6, only tested on this version), I get the following error (even though the package is installed - I can do a normal import):
```
Error: class uri 'flask_sockets.worker' invalid or not found:

[Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gunicorn/util.py", line 134, in load_class
    mod = import_module('.'.join(components))
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'flask_sockets'
]
```

I have searched online but did not manage to find a solution. Any ideas?

P.S.: Running this in a virtualenv.

**Comment by tilgovi** [comment]
I cannot reproduce the issue:

``` shellsession
randall@krampus ~/Desktop/tmpenv (master*) $ python3 -m venv .
randall@krampus ~/Desktop/tmpenv (master*) $ ./bin/pip install flask_sockets
Collecting flask_sockets
  Downloading Flask_Sockets-0.2.1-py2.py3-none-any.whl
Collecting gevent (from flask_sockets)
  Using cached gevent-1.2.2-cp36-cp36m-macosx_10_6_intel.whl
Collecting gevent-websocket (from flask_sockets)
  Downloading gevent_websocket-0.10.1-py3-none-any.whl
Collecting Flask (from flask_sockets)
  Using cached Flask-0.12.2-py2.py3-none-any.whl
Collecting greenlet>=0.4.10 (from gevent->flask_sockets)
  Downloading greenlet-0.4.13.tar.gz (58kB)
    100% |████████████████████████████████| 61kB 5.3MB/s
Collecting click>=2.0 (from Flask->flask_sockets)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from Flask->flask_sockets)
Collecting Jinja2>=2.4 (from Flask->flask_sockets)
  Using cached Jinja2-2.10-py2.py3-none-any.whl
Collecting Werkzeug>=0.7 (from Flask->flask_sockets)
  Using cached Werkzeug-0.14.1-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.4->Flask->flask_sockets)
Installing collected packages: greenlet, gevent, gevent-websocket, click, itsdangerous, MarkupSafe, Jinja2, Werkzeug, Flask, flask-sockets
  Running setup.py install for greenlet ... done
Successfully installed Flask-0.12.2 Jinja2-2.10 MarkupSafe-1.0 Werkzeug-0.14.1 click-6.7 flask-sockets-0.2.1 gevent-1.2.2 gevent-websocket-0.10.1 greenlet-0.4.13 itsdangerous-0.24
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
randall@krampus ~/Desktop/tmpenv (master*) $ ./bin/pip install gunicorn
Collecting gunicorn
  Using cached gunicorn-19.7.1-py2.py3-none-any.whl
Installing collected packages: gunicorn
Successfully installed gunicorn-19.7.1
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
randall@krampus ~/Desktop/tmpenv (master*) $ cp ~/src/gunicorn/examples/echo.py .
randall@krampus ~/Desktop/tmpenv (master*) $ ./bin/gunicorn -k flask_sockets.worker echo:app
[2018-03-22 10:04:01 -0700] [93559] [INFO] Starting gunicorn 19.7.1
[2018-03-22 10:04:01 -0700] [93559] [INFO] Listening at: http://127.0.0.1:8000 (93559)
[2018-03-22 10:04:01 -0700] [93559] [INFO] Using worker: flask_sockets.worker
[2018-03-22 10:04:01 -0700] [93562] [INFO] Booting worker with pid: 93562
^C[2018-03-22 10:04:06 -0700] [93559] [INFO] Handling signal: int
[2018-03-22 10:04:07 -0700] [93562] [INFO] Worker exiting (pid: 93562)
[2018-03-22 10:04:07 -0700] [93559] [INFO] Shutting down: Master
randall@krampus ~/Desktop/tmpenv (master*) $ ./bin/python --version
Python 3.6.4
```

**Comment by tjppires** [comment]
I'm sorry, my bad. I had some problems with my virtualenv installation that were causing it. Thank you for our time.
