### ISSUE TITLE
Greenlet: write_and_close: failed with BrokenPipeError

### ISSUE THREAD

**Issue by nikitarulz** [benoitc/gunicorn#1743]
While executing Self test of gevent:1.2.2 on a custom board, with kernel: 4.9.76 generated the following error:

ssss......................Traceback (most recent call last):
    File "/usr/lib/python3.5/site-packages/gevent/greenlet.py", line 536, in run
      result = self._run(*self.args, **self.kwargs)
    File "/usr/lib/python3.5/site-packages/gevent/subprocess.py", line 1371, in write_and_close
      fobj.flush()
    File "/usr/lib/python3.5/unittest/mock.py", line 919, in __call__
      return _mock_self._mock_call(*args, **kwargs)
    File "/usr/lib/python3.5/unittest/mock.py", line 975, in _mock_call
      raise effect
  BrokenPipeError
  Wed Mar 21 17:43:53 2018 <Greenlet at 0x7603cd50: write_and_close(<MagicMock name='stdin' id='1981703792'>, b'stuff')> failed with BrokenPipeError
  
  .Traceback (most recent call last):
    File "/usr/lib/python3.5/site-packages/gevent/greenlet.py", line 536, in run
      result = self._run(*self.args, **self.kwargs)
    File "/usr/lib/python3.5/site-packages/gevent/subprocess.py", line 1368, in write_and_close
      fobj.write(data)
    File "/usr/lib/python3.5/unittest/mock.py", line 919, in __call__
      return _mock_self._mock_call(*args, **kwargs)
    File "/usr/lib/python3.5/unittest/mock.py", line 975, in _mock_call
      raise effect
  BrokenPipeError
  Wed Mar 21 17:43:53 2018 <Greenlet at 0x7603c170: write_and_close(<MagicMock name='stdin' id='1981702960'>, b'stuff')> failed with BrokenPipeError
  
  ...........s...................................................s...........

Can someone explain why this error and how to resolve that?

Versions:
gevent: 1.2.2
Python: 3.5
Flash: 0.12.2
greenlet: 0.4.12

**Comment by tilgovi** [comment]
This looks like the gevent test suite, not gunicorn.
https://github.com/gevent/gevent/blob/master/src/greentest/3.7/test_subprocess.py#L2725

I'm not sure there's an error here. It might be that the test suite logs the traceback through some hook, but that it's not raised to the point of calling a failure. I don't see any message about tests failing. It looks like this test is supposed to trigger this error, but swallow it. See the comment `# Should swallow the BrokenPipeError.`.
