### ISSUE TITLE
Setting environment variables programmatically 

### ISSUE THREAD

**Issue by nareshsankapelly** [benoitc/gunicorn#1759]
I have use case where I need to setup the environment variable(OMP_NUM_THREADS) from within the application. I can't use --env option as the value is dynamic and I don't have any control on that variable. 

Setting OMP_NUM_THREADS to 1 using "os.environ["OMP_NUM_THREADS"] = 1" is failing with the following stacktrace. 

Traceback (most recent call last):
  File "/home/vagrant/miniconda2/envs/test_env/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/home/vagrant/miniconda2/envs/test_env/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/vagrant/miniconda2/envs/test_env/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "/home/vagrant/miniconda2/envs/test_env/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/vagrant/miniconda2/envs/test_env/lib/python2.7/site-packages/gunicorn/arbiter.py", line 218, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/vagrant/miniconda2/envs/test_env/lib/python2.7/site-packages/gunicorn/arbiter.py", line 331, in halt
    self.stop()
  File "/home/vagrant/miniconda2/envs/test_env/lib/python2.7/site-packages/gunicorn/arbiter.py", line 381, in stop
    time.sleep(0.1)
  File "/home/vagrant/miniconda2/envs/test_env/lib/python2.7/site-packages/gunicorn/arbiter.py", line 231, in handle_chld
    self.reap_workers()
  File "/home/vagrant/miniconda2/envs/test_env/lib/python2.7/site-packages/gunicorn/arbiter.py", line 506, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

**Comment by jamadden** [comment]
Is it possible that you're not specifying a string for the value (right hand side)? That would cause an exception to be thrown, probably killing the worker. In your example you're using an integer for the right hand side:
```python
>>> os.environ['FOO'] = 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//2.7/lib/python2.7/os.py", line 473, in __setitem__
    putenv(key, item)
TypeError: putenv() argument 2 must be string, not int
```

**Comment by berkerpeksag** [comment]
The value of the environment value should be a string. It should work if you replace `os.environ["OMP_NUM_THREADS"] = 1` with `os.environ["OMP_NUM_THREADS"] = "1"`.

That said, I think the traceback you posted is too cryptic. I'm going to keep this issue open to discuss if we could make errors like this easier to spot.

**Comment by benoitc** [comment]
@berkerpeksag did you find anything?

**Comment by berkerpeksag** [comment]
I'm not sure if there's an easy way to show a more meaningful message without inspecting the exception object:

```py
# Untested:
try:
    ...
except Exception as exc:
    if isinstance(exc, TypeError) and 'putenv() argument 2 must be string' in str(exc):
        raise ABetterExceptionType(
            'explain the issue',
            # Perhaps give users a hint:
            hint='The value of os.environ should always be a str.',
        )
        # Or we can just reraise the original exception.
    ...
```

**Comment by benoitc** [comment]
closing the issue since no activity since . @berkerpeksag thanks for your answer!
