### ISSUE TITLE
Error when using --log-syslog

### ISSUE THREAD

**Issue by rudolphfroger** [benoitc/gunicorn#1768]
I'm using gunicorn 19.8 with the following log options:

```
--log-syslog
--log-syslog-to "unix:///var/run/log#dgram"
--log-level "warning"
```

I'm getting this error:

```
Error handling request Traceback (most recent call last):
File "/usr/local/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 185, in handle_request
  self.log.access(resp, req, environ, request_time)
File "/usr/local/venv/lib/python3.6/site-packages/gunicorn/glogging.py", line 343, in access     (self.cfg.syslog and not self.cfg.disable_access_log_redirection)):
File "/usr/local/venv/lib/python3.6/site-packages/gunicorn/config.py", line 62, in __getattr__ 
raise AttributeError("No configuration setting for: %s" % name)
AttributeError: No configuration setting for: disable_access_log_redirection
```

I think there is a naming inconsistency: the setting is called `disable_redirect_access_to_syslog` and not `disable_access_log_redirection`. The bug has been introduced in this commit: https://github.com/benoitc/gunicorn/commit/7dc9003dff149e29c0af4d409060d34f9a7775fa

**Comment by tilgovi** [comment]
@rudolphfroger Thanks! I'll take a look tomorrow. If you can put together a PR before then, I'll gladly review it and merge it.
