### ISSUE TITLE
user = 'nobody' causes "Worker failed to boot"

### ISSUE THREAD

**Issue by naisanza** [benoitc/gunicorn#1785]
When `user = 'nobody'` is in the gunicorn.conf file, `gunicorn3` fails to start. But when `user = 'nobody'` is commented it out, `gunicorn3` starts

gunicorn.conf:
```
#import multiprocessing

bind = '[::]'
workers = 1

# Uncomment out this line to set the number of workers based
# on the numbers of cores available on the server
#workers = multiprocessing.cpu_count() * 2 + 1

threads = 2
limit_request_line = 4094
limit_request_fields = 100
limit_request_field_size = 8190
proxy_allow_ips = '*'
reload = False
reload_engine = 'auto'
spew = False
check_config = False
chdir = '/var/www'
user = 'nobody'
group = 'nogroup'
loglevel = 'debug'
syslog = False
#accesslog = '/var/log/gunicorn/gunicorn.log'
#errorlog = '/var/log/gunicorn/gunicorn-error.log'
access_log_format = '%({X-Real-IP}i)s %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
```

Error log:
```
root@world0-python-ubuntu-1:/var/www# gunicorn3 -c gunicorn.conf app:app
[2018-05-17 18:48:07 +0000] [130] [DEBUG] Current configuration:
  config: gunicorn.conf
  bind: ['[::]']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 2
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  chdir: /var/www
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 65534
  group: 65534
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  access_log_format: %({X-Real-IP}i)s %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  statsd_prefix:
  proc_name: None
  default_proc_name: app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f0ac63081e0>
  on_reload: <function OnReload.on_reload at 0x7f0ac6308378>
  when_ready: <function WhenReady.when_ready at 0x7f0ac6308510>
  pre_fork: <function Prefork.pre_fork at 0x7f0ac63086a8>
  post_fork: <function Postfork.post_fork at 0x7f0ac6308840>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f0ac63089d8>
  worker_int: <function WorkerInt.worker_int at 0x7f0ac6308b70>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f0ac6308d08>
  pre_exec: <function PreExec.pre_exec at 0x7f0ac6308ea0>
  pre_request: <function PreRequest.pre_request at 0x7f0ac630e0d0>
  post_request: <function PostRequest.post_request at 0x7f0ac630e1e0>
  child_exit: <function ChildExit.child_exit at 0x7f0ac630e378>
  worker_exit: <function WorkerExit.worker_exit at 0x7f0ac630e510>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f0ac630e6a8>
  on_exit: <function OnExit.on_exit at 0x7f0ac630e840>
  proxy_protocol: False
  proxy_allow_ips: ['*']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: TLSv1
  raw_paste_global_conf: []
[2018-05-17 18:48:07 +0000] [130] [INFO] Starting gunicorn 19.7.1
[2018-05-17 18:48:07 +0000] [130] [DEBUG] Arbiter booted
[2018-05-17 18:48:07 +0000] [130] [INFO] Listening at: http://[::]:8000 (130)
[2018-05-17 18:48:07 +0000] [130] [INFO] Using worker: threads
[2018-05-17 18:48:07 +0000] [133] [INFO] Booting worker with pid: 133
[2018-05-17 18:48:07 +0000] [133] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/gthread.py", line 109, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 377, in import_app
    __import__(module)
  File "/var/www/app.py", line 13, in <module>
    import helpers.auth as auth
  File "/var/www/helpers/auth.py", line 1, in <module>
    from flask import redirect, url_for, session, flash, request
ModuleNotFoundError: No module named 'flask'
[2018-05-17 18:48:07 +0000] [133] [INFO] Worker exiting (pid: 133)
[2018-05-17 18:48:07 +0000] [130] [DEBUG] 1 workers
[2018-05-17 18:48:07 +0000] [130] [INFO] Shutting down: Master
[2018-05-17 18:48:07 +0000] [130] [INFO] Reason: Worker failed to boot.
```

With `user = 'nobody'` commented out, it works:
```
root@world0-python-ubuntu-1:/var/www# gunicorn3 -c gunicorn.conf app:app
[2018-05-17 18:48:07 +0000] [130] [DEBUG] Current configuration:
  config: gunicorn.conf
  bind: ['[::]']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 2
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  chdir: /var/www
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 65534
  group: 65534
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  access_log_format: %({X-Real-IP}i)s %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  statsd_prefix:
  proc_name: None
  default_proc_name: app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f0ac63081e0>
  on_reload: <function OnReload.on_reload at 0x7f0ac6308378>
  when_ready: <function WhenReady.when_ready at 0x7f0ac6308510>
  pre_fork: <function Prefork.pre_fork at 0x7f0ac63086a8>
  post_fork: <function Postfork.post_fork at 0x7f0ac6308840>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f0ac63089d8>
root@world0-python-ubuntu-1:/var/www# gunicorn3 -c gunicorn.conf app:app
[2018-05-17 18:50:41 +0000] [134] [DEBUG] Current configuration:
  config: gunicorn.conf
  bind: ['[::]']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 2
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  chdir: /var/www
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 65534
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  access_log_format: %({X-Real-IP}i)s %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  statsd_prefix:
  proc_name: None
  default_proc_name: app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f0f3c5751e0>
  on_reload: <function OnReload.on_reload at 0x7f0f3c575378>
  when_ready: <function WhenReady.when_ready at 0x7f0f3c575510>
  pre_fork: <function Prefork.pre_fork at 0x7f0f3c5756a8>
  post_fork: <function Postfork.post_fork at 0x7f0f3c575840>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f0f3c5759d8>
  worker_int: <function WorkerInt.worker_int at 0x7f0f3c575b70>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f0f3c575d08>
  pre_exec: <function PreExec.pre_exec at 0x7f0f3c575ea0>
  pre_request: <function PreRequest.pre_request at 0x7f0f3c57b0d0>
  post_request: <function PostRequest.post_request at 0x7f0f3c57b1e0>
  child_exit: <function ChildExit.child_exit at 0x7f0f3c57b378>
  worker_exit: <function WorkerExit.worker_exit at 0x7f0f3c57b510>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f0f3c57b6a8>
  on_exit: <function OnExit.on_exit at 0x7f0f3c57b840>
  proxy_protocol: False
  proxy_allow_ips: ['*']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: TLSv1
  raw_paste_global_conf: []
[2018-05-17 18:50:41 +0000] [134] [INFO] Starting gunicorn 19.7.1
[2018-05-17 18:50:41 +0000] [134] [DEBUG] Arbiter booted
[2018-05-17 18:50:41 +0000] [134] [INFO] Listening at: http://[::]:8000 (134)
[2018-05-17 18:50:41 +0000] [134] [INFO] Using worker: threads
[2018-05-17 18:50:44 +0000] [137] [INFO] Booting worker with pid: 137
[2018-05-17 18:50:44 +0000] [134] [DEBUG] 1 workers
```

**Comment by tilgovi** [comment]
Where is flask installed? It sounds like the module is not readable by `nobody`.

**Comment by naisanza** [comment]
@tilgovi globally with `pip3 install flask`, but it seemed to have resolved itself
