### ISSUE TITLE
Getting [ERROR] Exception in worker process with Gunicorn + NGINX on Docker.

### ISSUE THREAD

**Issue by da-edra** [benoitc/gunicorn#1789]
Hello, I was working on a Django project when suddenly I was no longer able to start my app using `docker-compose up`. I started having this problem yesterday with no apparent cause, I even did a `git reset HEAD --hard` with no luck (it was working with that commit). One of my coworkers is not having that problem.

I'm using Python 3.6.5 on Arch Linux and using Docker. I have my .env the same way I had it before it stopped working so I have no clue why I'm getting a problem with my SECRET_KEY.

After deleting all the .pyc and containers and building again I have the same problem.
I even cloned the repo to another directory without luck.

```
$ docker-compose up                                                                                                                             10:28  67% (0:23)   
asofarma-django_db_1 is up-to-date
Starting asofarma-django_webapp_1 ... done
Starting asofarma-django_nginx_1  ... done
Attaching to asofarma-django_db_1, asofarma-django_webapp_1, asofarma-django_nginx_1
webapp_1  | [2018-05-21 03:56:30 +0000] [1] [INFO] Starting gunicorn 19.8.1
webapp_1  | [2018-05-21 03:56:30 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
webapp_1  | [2018-05-21 03:56:30 +0000] [1] [INFO] Using worker: sync
webapp_1  | [2018-05-21 03:56:30 +0000] [10] [INFO] Booting worker with pid: 10
webapp_1  | [2018-05-21 03:56:30 +0000] [11] [INFO] Booting worker with pid: 11
db_1      | 2018-05-21 03:52:56.516 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1      | 2018-05-21 03:52:56.516 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1      | 2018-05-21 03:52:56.722 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1      | 2018-05-21 03:52:57.391 UTC [26] LOG:  database system was interrupted; last known up at 2018-05-21 03:50:23 UTC
db_1      | 2018-05-21 03:53:01.185 UTC [26] LOG:  database system was not properly shut down; automatic recovery in progress
db_1      | 2018-05-21 03:53:01.235 UTC [26] LOG:  invalid record length at 0/1723550: wanted 24, got 0
db_1      | 2018-05-21 03:53:01.235 UTC [26] LOG:  redo is not required
db_1      | 2018-05-21 03:53:01.932 UTC [1] LOG:  database system is ready to accept connections
nginx_1   | [2018-05-21 03:56:31 +0000] [1] [INFO] Starting gunicorn 19.8.1
nginx_1   | [2018-05-21 03:56:31 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
nginx_1   | [2018-05-21 03:56:31 +0000] [1] [INFO] Using worker: sync
nginx_1   | [2018-05-21 03:56:31 +0000] [10] [INFO] Booting worker with pid: 10
nginx_1   | [2018-05-21 03:56:31 +0000] [11] [INFO] Booting worker with pid: 11
nginx_1   | [2018-05-21 03:56:31 +0000] [10] [ERROR] Exception in worker process
nginx_1   | Traceback (most recent call last):
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
nginx_1   |     worker.init_process()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
nginx_1   |     self.load_wsgi()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
nginx_1   |     self.wsgi = self.app.wsgi()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
nginx_1   |     self.callable = self.load()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
nginx_1   |     return self.load_wsgiapp()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
nginx_1   |     return util.import_app(self.app_uri)
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
nginx_1   |     __import__(module)
nginx_1   |   File "/opt/services/webapp/src/asofarma/wsgi.py", line 16, in <module>
nginx_1   |     application = get_wsgi_application()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
nginx_1   |     django.setup(set_prefix=False)
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
nginx_1   |     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
nginx_1   |     self._setup(name)
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 43, in _setup
nginx_1   |     self._wrapped = Settings(settings_module)
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 125, in __init__
nginx_1   |     raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
nginx_1   | django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.[2018-05-21 03:56:31 +0000] [11] [ERROR] Exception in worker process
nginx_1   | Traceback (most recent call last):
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
nginx_1   |     worker.init_process()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
nginx_1   |     self.load_wsgi()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
nginx_1   |     self.wsgi = self.app.wsgi()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
nginx_1   |     self.callable = self.load()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
nginx_1   |     return self.load_wsgiapp()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
nginx_1   |     return util.import_app(self.app_uri)
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
nginx_1   |     __import__(module)
nginx_1   |   File "/opt/services/webapp/src/asofarma/wsgi.py", line 16, in <module>
nginx_1   |     application = get_wsgi_application()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
nginx_1   |     django.setup(set_prefix=False)
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
nginx_1   |     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
nginx_1   |     self._setup(name)
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 43, in _setup
nginx_1   |     self._wrapped = Settings(settings_module)
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 125, in __init__
nginx_1   |     raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
nginx_1   | django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
nginx_1   | 
nginx_1   | [2018-05-21 03:56:31 +0000] [10] [INFO] Worker exiting (pid: 10)
nginx_1   | [2018-05-21 03:56:31 +0000] [11] [INFO] Worker exiting (pid: 11)
nginx_1   | Traceback (most recent call last):
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 210, in run
nginx_1   |     self.sleep()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 360, in sleep
nginx_1   |     ready = select.select([self.PIPE[0]], [], [], 1.0)
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
nginx_1   |     self.reap_workers()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
nginx_1   |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
nginx_1   | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
nginx_1   | 
nginx_1   | During handling of the above exception, another exception occurred:
nginx_1   | 
nginx_1   | Traceback (most recent call last):
nginx_1   |   File "/usr/local/bin/gunicorn", line 11, in <module>
nginx_1   |     sys.exit(run())
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
nginx_1   |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 223, in run
nginx_1   |     super(Application, self).run()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
nginx_1   |     Arbiter(self).run()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 232, in run
nginx_1   |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 345, in halt
nginx_1   |     self.stop()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
nginx_1   |     time.sleep(0.1)
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
nginx_1   |     self.reap_workers()
nginx_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
nginx_1   |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
nginx_1   | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
asofarma-django_nginx_1 exited with code 1
```
Heres my requirements.txt:
```
bcrypt==3.1.4
cffi==1.11.5
Django==2.0.4
Pillow==5.1.0
psycopg2==2.7.4
psycopg2-binary==2.7.4
pycparser==2.18
pytz==2018.4
six==1.11.0
django-phonenumber-field==2.0.0
gunicorn==19.8.1
```

And my Dockerfile:
```
# Start with an official Python image
FROM python:3.6

ENV PYTHONUNBUFFERED 1
RUN mkdir -p /opt/services/webapp/src
WORKDIR /opt/services/webapp/src

# Install dependencies
ADD requirements.txt /opt/services/webapp/src
RUN pip install -r requirements.txt

COPY . /opt/services/webapp/src

# Expose port 8000
EXPOSE 8000

# Default command to run when starting the container
CMD ["gunicorn", "-c", "config/gunicorn/conf.py", "--bind", ":8000", "--chdir", "asofarma", "asofarma.wsgi:application"]
```
How can I solve this problem? It happened with no apparent reason.

**Comment by da-edra** [comment]
Yes, I've checked that. My `SECRET_KEY` is set with an .env file.
I'm getting the error even if I manually set my `SECRET_KEY` on my `settings.py`.

As weird as it may sound this problem occurred _out of the blue_.

**Comment by da-edra** [comment]
So the problem was solved after doing a  `docker system prune -a -f`.

**Comment by hckhanh** [comment]
`docker system prune -a -f`
This is a dangerous command that you should not follow. Remove `-f` to make sure you do not delete your important images.
