### ISSUE TITLE
Python3.7 changes breaks import (SyntaxError: invalid syntax)

### ISSUE THREAD

**Issue by m3talstorm** [benoitc/gunicorn#1822]
Running the latest **python:3.7.0b5**:

```
[Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 135, in load_class
    mod = import_module('.'.join(components))
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/geventlet.py", line 27
    from gunicorn.workers.async import AsyncWorker
                              ^
SyntaxError: invalid syntax
]

```

https://docs.python.org/3.7/whatsnew/3.7.html

> Backwards incompatible syntax changes:
> 
> async and await are now reserved keywords.

The README says

> Gunicorn requires Python 2.x >= 2.6 or Python 3.x >= 3.2.

So technically Gunicorn should support 3.7?

**Comment by tilgovi** [comment]
Already handled in #1795. I will make a release in the next day or two.

**Comment by tilgovi** [comment]
Gunicorn 19.9.0 has been released!
