### ISSUE TITLE
gunicorn worker boot failed when workers >= 2 in python3 and tornado 5.0.2

### ISSUE THREAD

**Issue by yuiitsu** [benoitc/gunicorn#1829]
`[2018-07-12 10:59:35 +0800] [24794] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/apps/python/Python-3.6.5/lib/python3.6/asyncio/selector_events.py", line 264, in _add_reader
    key = self._selector.get_key(fd)
  File "/apps/python/Python-3.6.5/lib/python3.6/selectors.py", line 191, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '9 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/python/Python-3.6.5/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/apps/python/Python-3.6.5/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.run()
  File "/apps/python/Python-3.6.5/lib/python3.6/site-packages/gunicorn/workers/gtornado.py", line 139, in run
    server.add_socket(s)
  File "/apps/python/Python-3.6.5/lib/python3.6/site-packages/tornado/tcpserver.py", line 163, in add_socket
    self.add_sockets([socket])
  File "/apps/python/Python-3.6.5/lib/python3.6/site-packages/tornado/tcpserver.py", line 159, in add_sockets
    sock, self._handle_connection)
  File "/apps/python/Python-3.6.5/lib/python3.6/site-packages/tornado/netutil.py", line 258, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "/apps/python/Python-3.6.5/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 75, in add_handler
    fd, self._handle_events, fd, IOLoop.READ)
  File "/apps/python/Python-3.6.5/lib/python3.6/asyncio/selector_events.py", line 337, in add_reader
    return self._add_reader(fd, callback, *args)
  File "/apps/python/Python-3.6.5/lib/python3.6/asyncio/selector_events.py", line 267, in _add_reader
    (handle, None))
  File "/apps/python/Python-3.6.5/lib/python3.6/selectors.py", line 412, in register
    self._epoll.register(key.fd, epoll_events)
FileExistsError: [Errno 17] File exists`

`gunicorn -k=tornado --workers=2 index:app`

Any help? Thanks.

**Comment by yunstanford** [comment]
it might be because you've started/referenced `ioloop` before gunicorn os.fork, and it causes the same `fd` cloned to several worker processes and shared by them.

**Comment by tilgovi** [comment]
@cfregly can you talk more about your solution?

If [this comment](https://github.com/tornadoweb/tornado/issues/2426#issuecomment-401506092) is accurate, it looks like we may need to change how we [import tornado](https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/gtornado.py#L17) in our tornado worker.

**Comment by benoitc** [comment]
closing issue since no activity happened there and not reproduced on our own. Feel free to reopen it if needed.
