### ISSUE TITLE
python3.7 gevent worker RuntimeError

### ISSUE THREAD

**Issue by songguoxiong** [benoitc/gunicorn#1899]
I am learning flask and deploying it on the server through gunicorn.

But I encountered problems on python3.7. I want to find out why.
```
flask==1.0.2
gunicorn==19.9.0
gevent==1.3.6
```

```
# coding: utf-8
import asyncio

from flask import Flask

app = Flask(__name__)

async def main():
    return "ok"

@app.route("/")
def hello():
    loop = asyncio.new_event_loop()
    result = loop.run_until_complete(main())
    return result
```

I run the following commands
`gunicorn -b 0.0.0.0:8080 -k gevent wsgi:app`

Concurrent request service:
```
# coding: utf-8
from concurrent.futures import ThreadPoolExecutor, as_completed

import requests

if __name__ == '__main__':
    url = "http://127.0.0.1:8080"
    with ThreadPoolExecutor() as ex:
        fs = [ex.submit(requests.get, url) for _ in range(100)]
        for f in as_completed(fs):
            print(f.result())
```

error:
```
[2018-10-17 10:57:54,544] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/root/.envs/py37/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.envs/py37/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.envs/py37/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.envs/py37/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/root/.envs/py37/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.envs/py37/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/wsgi.py", line 18, in hello
    result = loop.run_until_complete(main())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 555, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 513, in run_forever
    'Cannot run the event loop while another loop is running')
RuntimeError: Cannot run the event loop while another loop is running
```

The above code is successful in python3.6.
But 3.7 failed.

Finally, thank all the developers who contributed to the project.

**Comment by tilgovi** [comment]
From what I read now, it seems like maybe `aiogevent` exists, but setting the `asyncio` event loop implementation is not something that `gevent` by itself does.

In that case, maybe something changed about the internals of `ThreadPoolExecutor` between 3.6 and 3.7?

**Comment by benoitc** [comment]
@songguoxiong . what was it?
