### ISSUE TITLE
[ERROR] Exception in worker process when trying to start Gunicorn

### ISSUE THREAD

**Issue by kkmoslehpour** [benoitc/gunicorn#1901]
This has been working for me for the longest time until when I pulled new code into the directory that gunicorn starts my app, now it doesnt start anymore.

wsgi.py:

```
from my_app import app as application

if __name__ == "__main__":
    application.run()
```

When I run my app with gunicorn i get the following error:

```
# /usr/bin/python3 /usr/bin/gunicorn 0.0.0.0:5000 wsgi
[2018-10-19 19:09:38 -0700] [2703] [INFO] Starting gunicorn 19.9.0
[2018-10-19 19:09:38 -0700] [2703] [INFO] Listening at: http://127.0.0.1:8000 (2703)
[2018-10-19 19:09:38 -0700] [2703] [INFO] Using worker: sync
[2018-10-19 19:09:38 -0700] [2706] [INFO] Booting worker with pid: 2706
[2018-10-19 19:09:38 -0700] [2706] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ImportError: No module named '0'
[2018-10-19 19:09:38 -0700] [2706] [INFO] Worker exiting (pid: 2706)
[2018-10-19 19:09:38 -0700] [2703] [INFO] Shutting down: Master
[2018-10-19 19:09:38 -0700] [2703] [INFO] Reason: Worker failed to boot.
```

I am able to run my app using `python3 run.py`fine.

```
# python3 run.py
 * Serving Flask app "my_app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5005/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 248-833-980
```

Any ideas why this is all of a sudden happeneing ?

**Comment by benoitc** [comment]
hrm are you sure it ever worked with that comand line ? Normally it should be `module:application` where application is a callable inside that file.

**Comment by tilgovi** [comment]
No reply for some months. Closing.

**Comment by drmaq** [comment]
I am having a similar issue with this exact error.

**Comment by pramodkhapare** [comment]
![Error](https://user-images.githubusercontent.com/58319460/73050965-7fa1eb80-3ea7-11ea-8422-352805c0d98b.jpg)
Getting this error, please suggest me solution

**Comment by pramodkhapare** [comment]
![Error](https://user-images.githubusercontent.com/58319460/73051084-defffb80-3ea7-11ea-98f6-bff05ed3dea7.jpg)
Getting this error, please suggest me solution

**Comment by jamadden** [comment]
@pramodkhapare Please do not comment on closed issues for something unrelated, please open a new issue.

That said, your problem is that you've specified your application as `path/to/file`. You need to specify it as a Python module `my.app.module`.

**Comment by kiansina** [comment]
I have the same issue. I cannot understand what is the problem.
