### ISSUE TITLE
[ERROR] Exception in worker process when trying to start Gunicorn

### ISSUE THREAD

**Issue by rssw** [benoitc/gunicorn#1904]
I'm not sure if this is related to another issue by this name, but since none of the packages match I'm starting a new post.  This error started appearing since I updated Graphite last night:

`11:59 user@server ~ $ sudo -H -u graphite -g www-data /usr/local/bin/gunicorn wsgi --pythonpath /opt/graphite/webapp,/opt/graphite/webapp/graphite --bind 127.0.0.1:8087 --workers 4 --preload
[2018-10-25 11:59:41 +0000] [32597] [INFO] Starting gunicorn 19.9.0
[2018-10-25 11:59:41 +0000] [32597] [INFO] Listening at: http://127.0.0.1:8087 (32597)
[2018-10-25 11:59:41 +0000] [32597] [INFO] Using worker: sync
[2018-10-25 11:59:41 +0000] [32603] [INFO] Booting worker with pid: 32603
[2018-10-25 11:59:41 +0000] [32604] [INFO] Booting worker with pid: 32604
[2018-10-25 11:59:41 +0000] [32605] [INFO] Booting worker with pid: 32605
[2018-10-25 11:59:41 +0000] [32606] [INFO] Booting worker with pid: 32606
[2018-10-25 11:59:50 +0000] [32605] [ERROR] Error handling request /render
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 135, in handle_uncaught_exception
    extra={'status_code': 500, 'request': request},
  File "/usr/lib/python2.7/logging/__init__.py", line 1200, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1293, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1303, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 766, in handle
    self.emit(record)
  File "/usr/lib/python2.7/dist-packages/django/utils/log.py", line 119, in emit
    message = "%s\n\n%s" % (self.format(no_exc_record), reporter.get_traceback_text())
  File "/usr/lib/python2.7/dist-packages/django/views/debug.py", line 334, in get_traceback_text
    return t.render(c)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 1040, in render
    output = self.filter_expression.resolve(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 736, in resolve
    new_obj = func(obj, *arg_vals)
  File "/usr/lib/python2.7/dist-packages/django/template/defaultfilters.py", line 255, in stringformat
    return ("%" + six.text_type(arg)) % value
  File "/usr/lib/python2.7/dist-packages/django/utils/functional.py", line 79, in __repr__
    return repr(self.__cast())
  File "/usr/lib/python2.7/dist-packages/django/utils/functional.py", line 131, in __cast
    return self.__text_cast()
  File "/usr/lib/python2.7/dist-packages/django/utils/functional.py", line 119, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/usr/lib/python2.7/dist-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/lib/python2.7/dist-packages/django/urls/resolvers.py", line 440, in _reverse_with_prefix
    possibilities = self.reverse_dict.getlist(lookup_view)
  File "/usr/lib/python2.7/dist-packages/django/urls/resolvers.py", line 337, in reverse_dict
    return self._reverse_dict[language_code]
KeyError: 'en-us'`

I've tried to track the error, and I got as far as to determine that the resolvers.py script fails it's _populate(self) script because the self.url_patterns returns None.  This is the limit of my abilities, hopefully someone can shed some light on this issue.  

Right now my Grafana dashboards are all dead.

**Comment by benoitc** [comment]
how to reproduce it?

**Comment by ifduyue** [comment]
File "/usr/lib/python2.7/dist-packages/django/urls/resolvers.py", line 337, in reverse_dict
    return self._reverse_dict[language_code]
    KeyError: 'en-us'

It's a django exception. Related issue https://github.com/graphite-project/graphite-web/issues/1971
