### ISSUE TITLE
Large size response resulting in Error: [('SSL routines', 'ssl3_write_pending', 'bad write retry')]

### ISSUE THREAD

**Issue by nav-agarwal** [benoitc/gunicorn#1912]
I'm submitting a potential bug report

**Describe the bug. What is the current behavior?**
Returning large sized response(>3MB) results in SSL error: Error: [('SSL routines', 'ssl3_write_pending', 'bad write retry')]

**To Reproduce:**
1. Setup a gunicorn server with gevent worker class and ssl configured. In handler return a buffer of size more than 3 MB. 
2. Call the given API using requests
3. On server side, following traceback is observed:

```
Traceback (most recent call last):
  File "/usr/local/pyenv/versions/2.7.13/lib/python2.7/site-packages/gunicorn/workers/async.py", line 115, in handle_request
    resp.write(item)
  File "/usr/local/pyenv/versions/2.7.13/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 361, in write
    util.write(self.sock, arg, self.chunked)
  File "/usr/local/pyenv/versions/2.7.13/lib/python2.7/site-packages/gunicorn/util.py", line 306, in write
    sock.sendall(data)
  File "/usr/local/pyenv/versions/2.7.13/lib/python2.7/site-packages/gevent_openssl/SSL.py", line 49, in sendall
    return self.__send(self._connection.sendall, data, flags)
  File "/usr/local/pyenv/versions/2.7.13/lib/python2.7/site-packages/gevent_openssl/SSL.py", line 53, in __send
    return self.__iowait(send_method, data, flags)
  File "/usr/local/pyenv/versions/2.7.13/lib/python2.7/site-packages/gevent_openssl/SSL.py", line 29, in __iowait
    return io_func(*args, **kwargs)
  File "/usr/local/pyenv/versions/2.7.13/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1302, in sendall
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/pyenv/versions/2.7.13/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1187, in _raise_ssl_error
    _raise_current_error()
  File "/usr/local/pyenv/versions/2.7.13/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('SSL routines', 'ssl3_write_pending', 'bad write retry')]
Traceback (most recent call last):
  File "/usr/local/pyenv/versions/2.7.13/lib/python2.7/site-packages/gunicorn/workers/async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/pyenv/versions/2.7.13/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 192, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File "/usr/local/pyenv/versions/2.7.13/lib/python2.7/site-packages/gunicorn/workers/async.py", line 136, in handle_request
    sock.shutdown(socket.SHUT_RDWR)
TypeError: shutdown() takes exactly 1 argument (2 given)
```
**Setup Details:**
Python 2.7.13
Gunicorn: '19.7.1
Openssl: OpenSSL 1.0.1f 6 Jan 2014 (Library: OpenSSL 1.0.2o-fips  27 Mar 2018)

**Comment by javabrett** [comment]
Wondering do you have a reproducible test project you are able to share? Is it sensitive to SSL/TLS or Python versions?

**Comment by javabrett** [comment]
Possibly unrelated but several other projects report similar errors relating to unicode char encoding in headers. https://github.com/urllib3/urllib3/issues/855

**Comment by nav-agarwal** [comment]
I will try to create a sample server and upload it here. It is more related to SSL/TLS version.

The requests/urllib3 bug you pointed out  are on client side, where requests is writing data to socket. In my bug, gunicorn is writing data to socket not requests.

**Comment by nav-agarwal** [comment]
Sample Server Code:
```
from __future__ import unicode_literals
import gunicorn.app.base
from gunicorn.six import iteritems
from gunicorn.six import iteritems
from OpenSSL import SSL

import falcon
SSL_CIPHERS =  'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA:HIGH:!RC4:!MD5:!aNULL:!3DES:!DES-CBC3-SHA'
# Falcon follows the REST architectural style, meaning (among
# other things) that you think in terms of resources and state
# transitions, which map to HTTP verbs.
class ThingsResource(object):
    def on_get(self, req, resp):
        """Handles GET requests"""
        # result = 'a' * 5
        result = 'a' * 1024 * 1024 * 50
        resp.status = falcon.HTTP_200  # This is the default status
        resp.body = result


def number_of_workers():
    return 1
    # return (multiprocessing.cpu_count() * 2) + 1


class StandaloneApplication(gunicorn.app.base.BaseApplication):

    def __init__(self, app, options=None):
        self.options = options or {}
        self.application = app
        super(StandaloneApplication, self).__init__()

    def load_config(self):
        config = dict([(key, value) for key, value in iteritems(self.options)
                       if key in self.cfg.settings and value is not None])
        for key, value in iteritems(config):
            self.cfg.set(key.lower(), value)

    def load(self):
        return self.application


def get_ctx():
    ctx = SSL.Context(SSL.SSLv23_METHOD)
    ctx.use_privatekey_file('privkey.pem')
    ctx.use_certificate_file('cert.pem')
    return ctx


if __name__ == '__main__':
    print "b"
    options = {
        'bind': '%s:%s' % ('0.0.0.0', '4789'),
        'workers': number_of_workers(),
        'custom_use_openssl': True,
        'custom_ssl_context': get_ctx()

    }
    options['certfile'] = 'cert.pem'
    options['ciphers'] = SSL_CIPHERS
    options['ssl_version'] = SSL.TLSv1_2_METHOD
    options['worker_class'] = 'gevent'

    # falcon.API instances are callable WSGI apps
    app = falcon.API()

    # Resources are represented by long-lived class instances
    things = ThingsResource()

    # things will handle all requests to the '/things' URL path
    app.add_route('/things', things)

    StandaloneApplication(app, options).run()
```
Client Code:
```
import requests
r = requests.get("https://localhost:4789/things", verify=False)
```

**Comment by nav-agarwal** [comment]
Update: Issue is not occuring with latest gunicorn. Reason for this is latest gunicorn has moved away from gevent_openssl package.

**Comment by javabrett** [comment]
@benoitc this is a candidate for closing.
