### ISSUE TITLE
Gunicorn when used with flast_jwt showing 500 reponse , eventhough flask_jwt sending 401 response 

### ISSUE THREAD

**Issue by bharathi-kmesh** [benoitc/gunicorn#1916]
```ERROR:flask.app:Exception on /klink [GET]
Traceback (most recent call last):
  File "/home/bharthi-kmesh/rest_repoistories/controller-rest-api/.env/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bharthi-kmesh/rest_repoistories/controller-rest-api/.env/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bharthi-kmesh/rest_repoistories/controller-rest-api/.env/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/bharthi-kmesh/rest_repoistories/controller-rest-api/.env/local/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/bharthi-kmesh/rest_repoistories/controller-rest-api/.env/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/bharthi-kmesh/rest_repoistories/controller-rest-api/.env/local/lib/python2.7/site-packages/flask_jwt/__init__.py", line 176, in decorator
    _jwt_required(realm or current_app.config['JWT_DEFAULT_REALM'])
  File "/home/bharthi-kmesh/rest_repoistories/controller-rest-api/.env/local/lib/python2.7/site-packages/flask_jwt/__init__.py", line 155, in _jwt_required
    headers={'WWW-Authenticate': 'JWT realm="%s"' % realm})
JWTError: Authorization Required. Request does not contain an access token```

**Comment by marcinkuzminski** [comment]
- [ ] one
- [ ] one

**Comment by javabrett** [comment]
I think you are using Flask-JWT.  If so, have you noticed that it is currently abandoned, and there are alternatives?  I wonder if those would behave differently.

Looks like Flask-JWT does not use Flask `abort()` to register the auth problem, I wonder if that makes a difference for Gunicorn.

**Comment by bharathi-kmesh** [comment]
After adding the below code in my flask code
`app.config['PROPAGATE_EXCEPTIONS'] = True`
Its Working fine, Thanks @javabrett

**Comment by javabrett** [comment]
@bharathi-kmesh if your issue is resolved please consider closing this issue.
