### ISSUE TITLE
SyntaxError: unexpected EOF while parsing in Heroku Deployment

### ISSUE THREAD

**Issue by SterlingButters** [benoitc/gunicorn#2002]
Greetings, I am getting the following SyntaxError in my Heroku build, any ideas on what the problem might be? Using Gunicorn 19.9.0

    2019-03-10T21:11:24.936875+00:00 heroku[web.1]: Starting process with command `gunicorn main: app.server`
    2019-03-10T21:11:27.137010+00:00 heroku[web.1]: State changed from starting to up
    2019-03-10T21:11:26.929950+00:00 app[web.1]: [2019-03-10 21:11:26 +0000] [4] [INFO] Starting gunicorn 19.9.0
    2019-03-10T21:11:26.930979+00:00 app[web.1]: [2019-03-10 21:11:26 +0000] [4] [INFO] Listening at: http://0.0.0.0:32580 (4)
    2019-03-10T21:11:26.931151+00:00 app[web.1]: [2019-03-10 21:11:26 +0000] [4] [INFO] Using worker: sync
    2019-03-10T21:11:26.935311+00:00 app[web.1]: [2019-03-10 21:11:26 +0000] [9] [INFO] Booting worker with pid: 9
    2019-03-10T21:11:36.572657+00:00 app[web.1]: [2019-03-10 21:11:36 +0000] [9] [ERROR] Exception in worker process
    2019-03-10T21:11:36.572690+00:00 app[web.1]: Traceback (most recent call last):
    2019-03-10T21:11:36.572693+00:00 app[web.1]: File "/app/.heroku/miniconda/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    2019-03-10T21:11:36.572695+00:00 app[web.1]: worker.init_process()
    2019-03-10T21:11:36.572697+00:00 app[web.1]: File "/app/.heroku/miniconda/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    2019-03-10T21:11:36.572699+00:00 app[web.1]: self.load_wsgi()
    2019-03-10T21:11:36.572701+00:00 app[web.1]: File "/app/.heroku/miniconda/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    2019-03-10T21:11:36.572702+00:00 app[web.1]: self.wsgi = self.app.wsgi()
    2019-03-10T21:11:36.572704+00:00 app[web.1]: File "/app/.heroku/miniconda/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    2019-03-10T21:11:36.572705+00:00 app[web.1]: self.callable = self.load()
    2019-03-10T21:11:36.572707+00:00 app[web.1]: File "/app/.heroku/miniconda/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    2019-03-10T21:11:36.572709+00:00 app[web.1]: return self.load_wsgiapp()
    2019-03-10T21:11:36.572710+00:00 app[web.1]: File "/app/.heroku/miniconda/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    2019-03-10T21:11:36.572712+00:00 app[web.1]: return util.import_app(self.app_uri)
    2019-03-10T21:11:36.572714+00:00 app[web.1]: File "/app/.heroku/miniconda/lib/python3.6/site-packages/gunicorn/util.py", line 362, in import_app
    2019-03-10T21:11:36.572715+00:00 app[web.1]: app = eval(obj, vars(mod))
    2019-03-10T21:11:36.572717+00:00 app[web.1]: File "<string>", line 0
    2019-03-10T21:11:36.572719+00:00 app[web.1]: 
    2019-03-10T21:11:36.572721+00:00 app[web.1]: ^
    2019-03-10T21:11:36.572723+00:00 app[web.1]: SyntaxError: unexpected EOF while parsing
    2019-03-10T21:11:36.575629+00:00 app[web.1]: [2019-03-10 21:11:36 +0000] [9] [INFO] Worker exiting (pid: 9)
    2019-03-10T21:11:36.946391+00:00 app[web.1]: [2019-03-10 21:11:36 +0000] [4] [INFO] Shutting down: Master
    2019-03-10T21:11:36.946455+00:00 app[web.1]: [2019-03-10 21:11:36 +0000] [4] [INFO] Reason: Worker failed to boot.
    2019-03-10T21:11:37.037342+00:00 heroku[web.1]: State changed from up to crashed
    2019-03-10T21:11:37.020575+00:00 heroku[web.1]: Process exited with status 3

**Comment by jamadden** [comment]
It would seem that the application callable portion of your configured app URI is resulting in an empty string. ("obj" is the result of [splitting the application URI on ":"](https://github.com/benoitc/gunicorn/blob/master/gunicorn/util.py#L365)):

```pycon
>>> module, obj = "package:".split(":", 1)
>>> obj
''
>>> eval(obj)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by tilgovi** [comment]
In other words, `gunicorn main: app.server` is not correct usage.

**Comment by SterlingButters** [comment]
@jamadden @tilgovi thanks, I haven't had a chance to investigate further since my computer died, hope to post back soon

**Comment by SterlingButters** [comment]
@tilgovi Indeed, I didn't realize no space was vital in `web: gunicorn main:app.server`
