### ISSUE TITLE
[ERROR] Socket error processing request

### ISSUE THREAD

**Issue by PradeepTammali** [benoitc/gunicorn#2033]
I am trying to deploy a python service on gunicorn server as pod in kubernetes. I am getting the following issue.

[2019-05-14 08:28:22 +0000] [24] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = six.next(parser)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/http/message.py", line 181, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/http/message.py", line 54, in __init__
    unused = self.parse(self.unreader)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/http/message.py", line 193, in parse
    self.get_data(unreader, buf, stop=True)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/http/message.py", line 184, in get_data
    data = unreader.read()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/http/unreader.py", line 38, in read
    d = self.chunk()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/http/unreader.py", line 65, in chunk
    return self.sock.recv(self.mxchunk)
  File "/usr/local/lib/python2.7/ssl.py", line 754, in recv
    return self.read(buflen)
  File "/usr/local/lib/python2.7/ssl.py", line 641, in read
    v = self._sslobj.read(len)
error: [Errno 0] Error

The service inside pod is running bu I am keep on getting this error in the error log. Cloud you please help me on this.

**Comment by tilgovi** [comment]
That looks like you are running with HTTPS but the pod receives an HTTP request. Perhaps there is a health check from your load balancer?

**Comment by PradeepTammali** [comment]
Found the issue. I have kept readiness probe in yaml which keeps pinging the pod on the port  by which it is giving me socket error. 
When I removed readiness probe, it is working fine. Not getting any error in the log. 

This is how my yamls is with readiness probe.

kind: Deployment
spec:
  template:
    spec:
      volumes:
      - hostPath:
          path: "/home/pradeep/logs/"
        name: logs
      containers:
      - command:
        - "/home/pradeep/startup.sh"
        name: gateway
        securityContext:
          privileged: true
        image: gateway:latest
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: "/home/pradeep/logs/"
          name: logs
        ports:
        - containerPort: 8888
        readinessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /test
            scheme: HTTPS
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 20
        resources:
          requests:
            cpu: 2
            memory: 2Gi
          limits:
            cpu: '2'
            memory: 2Gi
      nodeSelector:
        kubernetes.io/hostname: "test"
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value : "value"
        effect: "NoSchedule"
    metadata:
      labels:
        app: gw
  replicas: 1
apiVersion: extensions/v1beta1
metadata:
  name: gateway
  namespace: pradeep-testing


Is there any way to keep readiness probe for the health check purpose and not get the above the error.

**Comment by benoitc** [comment]
either you run gunicorn in https mode or use an HTTP probe. If you're using gunicorn behind nginx then you can do the routing quite easily also.

**Comment by PradeepTammali** [comment]
Thanks.. It's working now. I have used HTTP probe.
