### ISSUE TITLE
Load .ini files with the --config option?

### ISSUE THREAD

**Issue by ORESoftware** [benoitc/gunicorn#2037]
I have this in a .ini file:

```ini
###
# app configuration
# http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/environment.html
###

[app:main]
use = egg:mwapi
```

then I run:
```
 gunicorn -w 4 -c development_bd_prod.ini gunicorn:app
```

and I get:

```
Failed to read config file: development_bd_prod.ini
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 106, in get_config_from_filename
    execfile_(filename, cfg, cfg)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/_compat.py", line 71, in execfile_
    code = compile(open(fname, 'rb').read(), fname, 'exec')
  File "development_bd_prod.ini", line 6
    [app:main]
        ^
SyntaxError: invalid syntax
```

I thought the config option could load .ini files? maybe I was wrong, how to load ini configs?

**Comment by tilgovi** [comment]
Use the `--paste` option.

**Comment by ORESoftware** [comment]
yeah ok --paste, tbh a little surprising api, but i can manage, why is it called "paste"?

**Comment by tilgovi** [comment]
The sections of the `.ini` file that you are using are described by the Paste Deployment project. https://docs.pylonsproject.org/projects/pastedeploy/en/latest/

**Comment by tilgovi** [comment]
I've closed the issue, but feel free to follow up, or open new issues, if you have any other trouble.

**Comment by ORESoftware** [comment]
tyvm
