### ISSUE TITLE
Periodic 502 status codes with nginx+gunicorn+django

### ISSUE THREAD

**Issue by laukhin** [benoitc/gunicorn#2064]
Hi
We're using gunicorn with nginx in production with this configuration:
```
-k eventlet -w 8 --max-requests 1000 --reload --timeout 600
```
gunicorn version is 19.6.0
One of our endpoints is processing a lot of requests for a short period of time and sometimes gunicorn terminates connection, which leads to a 502 status code on nginx.
Sometimes it follows with this message:
```
[2019-06-25 08:18:35 +0000] [8498] [ERROR] Socket error processing request.
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/async.py", line 62, in handle
six.reraise(*sys.exc_info())
File "/usr/local/lib/python3.6/site-packages/gunicorn/six.py", line 625, in reraise
raise value
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/async.py", line 35, in handle
istener_name = listener.getsockname()
OSError: [Errno 9] Bad file descriptor
```
This looks exactly like issue in https://github.com/benoitc/gunicorn/pull/1725 PR, but as i can see this PR wasn't merged. Is this problem still relevant for 19.9.0? Can you suggest any workarounds to avoid this kind of errors, if gunicorn upgrade won't help?

**Comment by benoitc** [comment]
no activity since awhile. closing feel free to create a new ticket if needed.
