### ISSUE TITLE
gunicorn fails after Python-2.7.16 upgrade

### ISSUE THREAD

**Issue by dbf256** [benoitc/gunicorn#2093]
I upgraded Python from 2.7.6 to 2.7.16 on my ubuntu vps.
Gunicorn server version 19.4.1 fails to start with such error:

```
Traceback (most recent call last):
  File "/home/user/bin/python-2.7/bin/gunicorn", line 7, in <module>
    from gunicorn.app.wsgiapp import run
  File "/home/user/bin/python-2.7/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "/home/user/bin/python-2.7/lib/python2.7/site-packages/gunicorn/app/base.py", line 12, in <module>
    from gunicorn import util
  File "/home/user/bin/python-2.7/lib/python2.7/site-packages/gunicorn/util.py", line 12, in <module>
    import pkg_resources
  File "/home/user/bin/python-2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 82, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/home/user/bin/python-2.7/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 61, in load_module
    "distribution.".format(**locals())
ImportError: The 'packaging.requirements' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

```

I tried to upgrade gunicorn to version 19.9.0 and had the same issue.

**Comment by jamadden** [comment]
`pkg_resources` is a part of [setuptools](https://setuptools.readthedocs.io/en/latest/), the library that runs `setup.py` to build and install packages. `pip` uses it under the scenes in many cases, so it's a pretty fundamental library. That library's installation appears to be broken, and you'll need to fix that.

You might try `python -m ensurepip`.

**Comment by dbf256** [comment]
@jamadden I tried this command (and also tried to reinstall setuptools) and it didn't help.
But looks like it is not a gunicorn issue because it is just an import in gunicorn code.

**Comment by berkerpeksag** [comment]
I think this is a duplicate of #1716.

**Comment by dbf256** [comment]
@berkerpeksag why do you think so? In ticket #1716 missing setuptools is mentioned, while I have it installed but it doesn't work properly
