### ISSUE TITLE
'str' object is not callable in 19.9.0 (django, python 2.7, docker-compose)

### ISSUE THREAD

**Issue by Dem0n3D** [benoitc/gunicorn#2110]
Faced an issue after upgrade:
```
[2019-09-13 10:01:02 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-13 10:01:02 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2019-09-13 10:01:02 +0000] [1] [INFO] Using worker: sync
[2019-09-13 10:01:02 +0000] [1] [INFO] Unhandled exception in main loop
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 203, in run
    self.manage_workers()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 545, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 616, in spawn_workers
    self.spawn_worker()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 565, in spawn_worker
    self.cfg, self.log)
TypeError: 'str' object is not callable
```

Running in Docker Swarm with docker-compose, using next command:
```
command: gunicorn django_wsgi:application --bind 0.0.0.0:8000 --timeout 180 -w 8 --access-logfile -
```

Downgrading to 19.8.* helped.

**Comment by benoitc** [comment]
which python and django versions?

**Comment by Dem0n3D** [comment]
Python 2.7, Django 1.8

**Comment by benoitc** [comment]
can you try #2114? IT should solve your issue with python2.7.

**Comment by benoitc** [comment]
bump.
