### ISSUE TITLE
module 'tornado.wsgi' has no attribute 'WSGIApplication'

### ISSUE THREAD

**Issue by bingwork** [benoitc/gunicorn#2116]
Name: tornado
Version: 6.0.3

Name: gunicorn
Version: 19.9.0

**tornadoapp.py**

from datetime import timedelta

from tornado.web import Application, RequestHandler
from tornado.ioloop import IOLoop
from tornado import gen

class MainHandler(RequestHandler):
    def get(self):
        print('hello')
        self.write("Hello, world")

class LongPollHandler(RequestHandler):
    @gen.coroutine
    def get(self):
        lines = ['line 1\n', 'line 2\n']

        def send():
            try:
                self.write(lines.pop(0))
                self.flush()
            except:
                self.finish()
            else:
                IOLoop.instance().add_timeout(timedelta(0, 20), send)

        send()

app = Application([
    (r"/", MainHandler),
    (r"/longpoll", LongPollHandler)
])

**then use command to run:**
gunicorn -k tornado test_tornado:app

**cause errors:**
[2019-09-24 13:08:46 +0800] [23577] [INFO] Worker exiting (pid: 23577)
[2019-09-24 13:08:46 +0800] [23578] [INFO] Booting worker with pid: 23578
TestTornadoApp init ok!
[2019-09-24 13:08:46 +0800] [23578] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/user/envs/python37/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/user/envs/python37/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.run()
  File "/Users/user/envs/python37/lib/python3.7/site-packages/gunicorn/workers/gtornado.py", line 88, in run
    isinstance(app, tornado.wsgi.WSGIApplication):
AttributeError: module 'tornado.wsgi' has no attribute 'WSGIApplication'

how to fix? thx.

**Comment by bingwork** [comment]
I find the reason and fixed. I should use tornado==5.1.1, not 6.*.*.

@benoitc can you think it's need to fix in latest gunicorn? thx.

**Comment by benoitc** [comment]
@bingwork did you try latest master?

**Comment by bingwork** [comment]
@benoitc I try latest master, and see changes in #2001 . It has been fixed. Thx.

**Comment by tilgovi** [comment]
The relevant commit is also in #2114. I'll close this issue. Thanks for reporting!
