### ISSUE TITLE
can reproduce，place help!!!

### ISSUE THREAD

**Issue by fushenghua** [benoitc/gunicorn#2117]
[2019-09-26 11:50:44 +0000] [2774] [ERROR] Error handling request /socket.io/?EIO=3&transport=websocket
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base_async.py", line 56, in handle
self.handle_request(listener_name, req, client, addr)
File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base_async.py", line 115, in handle_request
resp.write(item)
File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/wsgi.py", line 333, in write
self.send_headers()
File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/wsgi.py", line 325, in send_headers
tosend = self.default_headers()
File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/wsgi.py", line 306, in default_headers
elif self.should_close():
File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/wsgi.py", line 229, in should_close
if self.status_code < 200 or self.status_code in (204, 304):
AttributeError: 'Response' object has no attribute 'status_code'
^C[2019-09-26 11:50:44 +0000] [2768] [INFO] Handling signal: int

**Comment by benoitc** [comment]
you need to give us more details. Which application is doing it? Which libraries are you using?

**Comment by art-i-svsg** [comment]
@benoitc @miguelgrinberg We have the same issue. We are using flask-socketio for websockets and we see this error very often. It seems that it was fixed in the past but now it is here again. 
Versions of packages installed: 
`certifi==2019.6.16
chardet==3.0.4
Click==7.0
datadog==0.29.2
decorator==4.4.0
dnspython==1.16.0
eventlet==0.24.1
fire==0.1.3
Flask==1.0.4
Flask-Cors==3.0.6
Flask-SocketIO==3.0.2
Flask-SQLAlchemy==2.3.2
greenlet==0.4.15
gunicorn==19.9.0
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10.1
logdna==1.3.0
MarkupSafe==1.1.1
marshmallow==2.19.5
marshmallow-enum==1.4.1
monotonic==1.5
newrelic==4.4.1.104
pip==10.0.1
psycopg2==2.7.7
pydantic==0.11.2
python-engineio==3.8.2.post1
python-memcached==1.59
python-socketio==4.2.0
pytz==2019.2
requests==2.22.0
sentry-sdk[flask]==0.10.2
setuptools==39.2.0
six==1.12.0
SQLAlchemy==1.2.19
SQLAlchemy-Utils==0.33.11
urllib3==1.25.3
Werkzeug==0.15.5
wheel==0.31.1
`
Gunicorn is started with this command: 
`gunicorn wsgi:app --workers 1 --bind 0.0.0.0:5001 --worker-class=eventlet --preload`
Is there any way to fix it?

**Comment by benoitc** [comment]
no activity since awhile. closing feel free to create a new ticket if needed.
