### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 141-142: ordinal not in range(128)

### ISSUE THREAD

**Issue by allbugsbelongtous** [benoitc/gunicorn#2127]
I'm making a Bottle app and serving it with Gunicorn. I've been able to reduce the code to this demo snippet:

    demo.py
    ====================
    import bottle
    from bottle import get, redirect
    
    app = bottle.app()
    
    @get('/')
    def index():
        return redirect('/foobàr')

starting Gunicorn

    (venv) user@debian10:/srv/demo$ gunicorn --bind ":8080" demo:app
    [2019-10-09 12:32:35 +0200] [2614] [INFO] Starting gunicorn 19.9.0
    [2019-10-09 12:32:35 +0200] [2614] [INFO] Listening at: http://0.0.0.0:8080 (2614)
    [2019-10-09 12:32:35 +0200] [2614] [INFO] Using worker: sync
    [2019-10-09 12:32:35 +0200] [2617] [INFO] Booting worker with pid: 2617

when I visit `localhost:8080` I get a 500 with this error:

    [2019-10-09 12:32:36 +0200] [2617] [ERROR] Error handling request /
    Traceback (most recent call last):
      File "/srv/demo/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
        self.handle_request(listener, req, client, addr)
      File "/srv/demo/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 183, in handle_request
        resp.close()
      File "/srv/demo/venv/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 409, in close
        self.send_headers()
      File "/srv/demo/venv/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 329, in send_headers
        util.write(self.sock, util.to_bytestring(header_str, "ascii"))
      File "/srv/demo/venv/lib/python3.7/site-packages/gunicorn/util.py", line 507, in to_bytestring
        return value.encode(encoding)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 141-142: ordinal not in range(128)

The error **does not** show if I redirect to an ASCII URL, like `return redirect('/foobar')`. Only with non-ASCII URLs. To be honest, I'm not sure if this is a problem with Gunicorn or with Bottle.

**Comment by tilgovi** [comment]
I suspect this is already fixed on master and is about to be merged to the 19.x branch by #2114, where we've changed the encoding for headers to `latin-1` rather than `ascii`.

As a workaround, you can may be able to encode it yourself with `'/foobàr'.encode('latin-1')`. If you would like to try out the branch in #2114 or the master branch, you can also let us know if that helps.

**Comment by benoitc** [comment]
Closing the issue . As said @tilgovi  we are supporting latin 1 in last master and coming 20.0.

According the HTTP spec we should only support ascii but Gunicorn is now supporting latin 1 characters to comply with the WSGI spec and support legacy. Unicode is however not supported.
