### ISSUE TITLE
Gunicorn issue serving static content when running as kubernetes pod

### ISSUE THREAD

**Issue by paulalex** [benoitc/gunicorn#2167]
I have a very basic flask application that I have built into a container and when I run this locally it runs fine and I get no errors and all my static content is working fine.

However when I then deploy this to kubernetes I get no css or images in my application and I get the following error (see below), the application also seems to run incredibly slowly, I would appreciate any help you can give with this:

```
[2019-11-12 17:32:32 +0000] [18] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 111, in handle_request
    resp.write_file(respiter)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += os.sendfile(sockno, fileno, offset + sent, count)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 36, in _gevent_sendfile
    return os.sendfile(fdout, fdin, offset, nbytes)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 36, in _gevent_sendfile
    return os.sendfile(fdout, fdin, offset, nbytes)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 36, in _gevent_sendfile
    return os.sendfile(fdout, fdin, offset, nbytes)
  [Previous line repeated 967 more times]
RecursionError: maximum recursion depth exceeded
[2019-11-12 17:32:32 +0000] [18] [DEBUG] Closing connection.
[2019-11-12 17:32:34 +0000] [21] [DEBUG] Closing connection.
[2019-11-12 17:32:34 +0000] [20] [DEBUG] Closing connection.
[2019-11-12 17:32:34 +0000] [21] [DEBUG] Closing connection.
[2019-11-12 17:32:34 +0000] [20] [DEBUG] Closing connection.
[2019-11-12 17:32:34 +0000] [19] [DEBUG] Closing connection.
[2019-11-12 17:32:34 +0000] [20] [DEBUG] Closing connection.
[2019-11-12 17:32:34 +0000] [20] [DEBUG] Closing connection.
[2019-11-12 17:32:34 +0000] [20] [DEBUG] Closing connection.
[2019-11-12 17:32:34 +0000] [18] [DEBUG] Closing connection.
[2019-11-12 17:32:34 +0000] [20] [DEBUG] Closing connection.
[2019-11-12 17:32:35 +0000] [20] [DEBUG] Closing connection.
[2019-11-12 17:32:39 +0000] [21] [DEBUG] Closing connection.
[2019-11-12 17:32:39 +0000] [19] [DEBUG] Closing connection.
[2019-11-12 17:32:39 +0000] [18] [DEBUG] Closing connection.
[2019-11-12 17:32:40 +0000] [20] [DEBUG] Closing connection.
[2019-11-12 17:32:42 +0000] [18] [DEBUG] Closing connection.
[2019-11-12 17:32:43 +0000] [21] [DEBUG] Closing connection.
[2019-11-12 17:32:43 +0000] [20] [DEBUG] Closing connection.
[2019-11-12 17:32:43 +0000] [20] [DEBUG] Closing connection.
[2019-11-12 17:32:43 +0000] [21] [DEBUG] Closing connection.
[2019-11-12 17:32:43 +0000] [20] [DEBUG] Closing connection.
[2019-11-12 17:32:43 +0000] [19] [DEBUG] Closing connection.
[2019-11-12 17:32:44 +0000] [18] [DEBUG] Closing connection.
[2019-11-12 17:32:44 +0000] [20] [DEBUG] Closing connection.
[2019-11-12 17:32:45 +0000] [21] [DEBUG] Closing connection.
[2019-11-12 17:32:50 +0000] [21] [DEBUG] Closing connection.
[2019-11-12 17:32:54 +0000] [20] [DEBUG] Closing connection.
[2019-11-12 17:32:54 +0000] [18] [DEBUG] Closing connection.
[2019-11-12 17:32:55 +0000] [19] [DEBUG] Closing connection.
[2019-11-12 17:33:00 +0000] [21] [DEBUG] Closing connection.
[2019-11-12 17:33:01 +0000] [20] [DEBUG] Closing connection.
```

Here are the parameters I am passing to kick the script off:

`gunicorn -b 0.0.0.0:5000 --log-level=debug --worker-class gevent --worker-connections 10 --timeout 120 --keep-alive 120 --threads 4 --workers 4 --access-logfile '-' wsgi:app`

**Comment by jamadden** [comment]
Thanks for the report! This appears to be the same issue being discussed in #1925.

**Comment by paulalex** [comment]
Ok so is there a workaround or way to get this to work? It works locally. Or is the answer to not use gunicorn?

**Comment by tilgovi** [comment]
#2172 has merged. We'll work on getting the fix out.
