### ISSUE TITLE
RecursionError with eventlet workers and sendfile

### ISSUE THREAD

**Issue by estadtherr** [benoitc/gunicorn#2170]
When using gunicorn with eventlet workers to serve static files with Flask, there is an infinite recursion error. Looking at `workers/geventlet.py`, it appears to be caused by patching `os.sendfile` to refer to `_eventlet_sendfile`, whereas `_eventlet_sendfile` just turns around and calls `os.sendfile()`:

```python
def _eventlet_sendfile(fdout, fdin, offset, nbytes):
    while True:
        try:
            return os.sendfile(fdout, fdin, offset, nbytes)
        except OSError as e:
            if e.args[0] == errno.EAGAIN:
                trampoline(fdout, write=True)
            else:
                raise
…
def patch_sendfile():
    setattr(os, "sendfile", _eventlet_sendfile)
```

A simple test case follows:

`requirements.txt`:
```
gunicorn[eventlet]==20.0
Flask==1.1
```

`sendfile_bug.py`:
```python
from flask import Flask
application = Flask(__name__)

```

`static/hello`:
```
hello
```

start command:
```shell
% gunicorn -b 0.0.0.0:5000 --log-level=debug -k eventlet sendfile_bug
```

request:
```shell
% curl http://localhost:5000/static/hello
```

Output from `gunicorn` process:
```
[2019-11-12 14:11:45 -0700] [62286] [INFO] Starting gunicorn 20.0.0
[2019-11-12 14:11:45 -0700] [62286] [DEBUG] Arbiter booted
[2019-11-12 14:11:45 -0700] [62286] [INFO] Listening at: http://0.0.0.0:5000 (62286)
[2019-11-12 14:11:45 -0700] [62286] [INFO] Using worker: eventlet
[2019-11-12 14:11:45 -0700] [62289] [INFO] Booting worker with pid: 62289
[2019-11-12 14:11:45 -0700] [62286] [DEBUG] 1 workers
[2019-11-12 14:11:49 -0700] [62289] [DEBUG] GET /static/hello
[2019-11-12 14:11:49 -0700] [62289] [ERROR] Error handling request
Traceback (most recent call last):
  File "venv/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 111, in handle_request
    resp.write_file(respiter)
  File "venv/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "venv/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += os.sendfile(sockno, fileno, offset + sent, count)
  File "venv/lib/python3.7/site-packages/gunicorn/workers/geventlet.py", line 32, in _eventlet_sendfile
    return os.sendfile(fdout, fdin, offset, nbytes)
  File "venv/lib/python3.7/site-packages/gunicorn/workers/geventlet.py", line 32, in _eventlet_sendfile
    return os.sendfile(fdout, fdin, offset, nbytes)
  File "venv/lib/python3.7/site-packages/gunicorn/workers/geventlet.py", line 32, in _eventlet_sendfile
    return os.sendfile(fdout, fdin, offset, nbytes)
  [Previous line repeated 968 more times]
RecursionError: maximum recursion depth exceeded
[2019-11-12 14:11:49 -0700] [62289] [DEBUG] Closing connection.
```

**Comment by jamadden** [comment]
Thank you for the report! #1925 documents a very similar issue with gevent, but I'm not sure we realized it was also an issue with eventlet.

**Comment by tilgovi** [comment]
20.0.2 is released. Thanks all!
