### ISSUE TITLE
gunicorn fails on IBM i with Python <3.7

### ISSUE THREAD

**Issue by ThePrez** [benoitc/gunicorn#2194]
This error, I believe, is introduced by this new feature: https://github.com/benoitc/gunicorn/commit/ee7af1247b8cc289af7b4bcfd2ff93ecfaf8c9df

Starting with gunicorn v20, it fails to start on the IBM i platform. Even a simple `gunicorn -h` fails with:
```
Traceback (most recent call last):
  File "/QOpenSys/pkgs/bin/gunicorn", line 5, in <module>
    from gunicorn.app.wsgiapp import run
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/gunicorn/app/base.py", line 12, in <module>
    from gunicorn.arbiter import Arbiter
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/gunicorn/arbiter.py", line 16, in <module>
    from gunicorn import sock, systemd, util
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/gunicorn/sock.py", line 14, in <module>
    from gunicorn.socketfromfd import fromfd
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/gunicorn/socketfromfd.py", line 26, in <module>
    raise OSError('libc not found')
OSError: libc not found
```
Several issues related to ctypes were fixed for IBM i and AIX in Python 3.7, but Python 3.6 is still widely used (and is the newest version distributed by IBM) on IBM i. 

Will send a PR with a proposed change soon.

**Comment by benoitc** [comment]
thanks for the patch

**Comment by benoitc** [comment]
Hi @ThePrez can you try #2208 and let me know hw it works for you?  I changed the implementation to simply use the python standard library. Any feedback is welcome :)

**Comment by ThePrez** [comment]
Yep, looks good. Thanks for looping me in on the change!
