### ISSUE TITLE
forkserver not available with gunicorn 20.0.2 , eventlet, dask distributed.

### ISSUE THREAD

**Issue by cpaulik** [benoitc/gunicorn#2203]
Same thing works with gunicorn 19.9.0. 

Not 100% sure if this is a gunicorn issue but I'm raising here first since the gunicorn update broke it.

I'm not trying to do any multiprocessing in combination with gunicorn but my code imports the `dask.distributed.Client` because it is not only a app hosted by gunicorn.

``` bash
$ conda create -n gunicorn-test -c conda-forge gunicorn dask eventlet

$ cat my_app.py 
from dask.distributed import Client

def app(environ, start_response):
        data = b"Hello, World!\n"
        start_response("200 OK", [
            ("Content-Type", "text/plain"),
            ("Content-Length", str(len(data)))
        ])
        return iter([data])

$ gunicorn my_app:app -k eventlet

[2019-11-25 13:47:02 +0100] [787789] [INFO] Starting gunicorn 20.0.2
[2019-11-25 13:47:02 +0100] [787789] [INFO] Listening at: http://127.0.0.1:8000 (787789)
[2019-11-25 13:47:02 +0100] [787789] [INFO] Using worker: eventlet
[2019-11-25 13:47:02 +0100] [787892] [INFO] Booting worker with pid: 787892
[2019-11-25 13:47:02 +0100] [787892] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 99, in init_process
    super().init_process()
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cpa/my_app.py", line 2, in <module>
    from dask.distributed import Client
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/site-packages/dask/distributed.py", line 3, in <module>
    from distributed import *
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/site-packages/distributed/__init__.py", line 3, in <module>
    from .actor import Actor, ActorFuture
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/site-packages/distributed/actor.py", line 7, in <module>
    from .client import Future, default_client
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/site-packages/distributed/client.py", line 49, in <module>
    from .batched import BatchedSend
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/site-packages/distributed/batched.py", line 8, in <module>
    from .core import CommClosedError
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/site-packages/distributed/core.py", line 18, in <module>
    from .comm import (
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/site-packages/distributed/comm/__init__.py", line 1, in <module>
    from .addressing import (
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/site-packages/distributed/comm/addressing.py", line 4, in <module>
    from ..utils import get_ip_interface
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/site-packages/distributed/utils.py", line 87, in <module>
    mp_context = _initialize_mp_context()
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/site-packages/distributed/utils.py", line 78, in _initialize_mp_context
    ctx = multiprocessing.get_context(method)
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/multiprocessing/context.py", line 239, in get_context
    return super().get_context(method)
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/multiprocessing/context.py", line 194, in get_context
    ctx._check_available()
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gunicorn-test/lib/python3.8/multiprocessing/context.py", line 305, in _check_available
    raise ValueError('forkserver start method not available')
ValueError: forkserver start method not available
[2019-11-25 13:47:02 +0100] [787892] [INFO] Worker exiting (pid: 787892)
[2019-11-25 13:47:02 +0100] [787789] [INFO] Shutting down: Master
[2019-11-25 13:47:02 +0100] [787789] [INFO] Reason: Worker failed to boot.
```

**Comment by jamadden** [comment]
Earlier versions of gunicorn were broken when it came to monkey-patching eventlet, and [didn't actually do the patch correctly](https://github.com/benoitc/gunicorn/issues/1847). 

It appears that [eventlet's socket](https://github.com/eventlet/eventlet/blob/ac7917c7241bc29696cf65dd7b9757df9c9bc955/eventlet/greenio/base.py#L120) does not implement `sendmsg`, which is a prerequisite for using the forkserver start method. So a monkey-patched process won't be able to use that method.

You could try using a different worker type (I believe gevent provides `sendmsg`; you'll need 1.5a2 for Python 3.8). Or you could try explicitly setting a multiproccessing start method before making this import, e.g., `multiprocessing.set_start_method('fork', force=True)`.

**Comment by cpaulik** [comment]
Thank you for the explanation.

I've fixed it in our application by refactoring our modules so distributed is not imported when the application is run.

Feel free to close this.
