### ISSUE TITLE
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

### ISSUE THREAD

**Issue by rkmullapudi** [benoitc/gunicorn#2232]
Hi, I followed this document from Digital Ocean: 
https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-18-04
but I hit this blocking issue. Is this a known bug and we are completely blocked for deploying our hosting server. 

Django, Gunicorn were installed inisde virtual env.

```
shami@ubuntu-s-2$~/vkproject$ source ~/vkproject/vkenv/bin/activate
(vkenv) shami@ubuntu-s-2$:~/vkproject$ 
(vkenv) shami@ubuntu-s-2$:~/vkproject$ which python
/home/shami/vkproject/vkenv/bin/python
(vkenv) shami@ubuntu-s-2$:~/vkproject$ pwd
/home/shami/vkproject
(vkenv) shami@ubuntu-s-2$:~/vkproject$ ls -lrt 
total 10260
drwxr-xr-x 3 shami shami    4096 Nov 23 18:00 media
drwxrwxr-x 5 shami shami    4096 Nov 24 00:01 vkenv
-rwxrwxr-x 1 shami shami     627 Nov 24 00:05 manage.py
-rw-r--r-- 1 shami shami  277873 Nov 29 02:58 pages.zip
-rw-r--r-- 1 shami shami 1358140 Nov 29 03:00 media.zip
drwxrwxr-x 2 shami shami    4096 Nov 29 04:24 logs
drwxr-xr-x 3 shami shami    4096 Nov 30 07:40 DataBaseScripts
drwxr-xr-x 6 shami shami    4096 Dec  8 05:17 pages
drwxrwxr-x 6 shami shami    4096 Dec  8 14:51 static
drwxrwxr-x 3 shami shami    4096 Dec 29 03:09 vikreya
(vkenv) shami@ubuntu-s-2$:~/vkproject$ 
```
and both Django and gunicron are able to get started successfully and I'm able to login to Django admin site successfully.
```
shami@ubuntu-s-2vcpu-2:~/vkproject$ source ~/vkproject/vkenv/bin/activate
(vkenv) shami@ubuntu-s-2vcpu-2gb-sfo2-01:~/vkproject$ 
(vkenv) shami@ubuntu-s-2:~/vkproject$ 
(vkenv) shami@ubuntu-s-2~/vkproject$ ~/vkproject/manage.py runserver 0.0.0.0:8000
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
January 01, 2020 - 00:19:09
Django version 3.0, using settings 'vikreya.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[01/Jan/2020 00:19:14] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1913
[01/Jan/2020 00:19:14] "GET /static/admin/css/base.css HTTP/1.1" 304 0
```
After this I'm able to login and access admin control of my Django application. I ran this next step as per documentation.

```
(vkenv) shami@ubuntu-s-2:~/vkproject$ gunicorn --bind 0.0.0.0:8000 vikreya.wsgi
[2020-01-01 00:20:04 +0000] [28773] [INFO] Starting gunicorn 20.0.2
[2020-01-01 00:20:04 +0000] [28773] [INFO] Listening at: http://0.0.0.0:8000 (28773)
[2020-01-01 00:20:04 +0000] [28773] [INFO] Using worker: sync
[2020-01-01 00:20:04 +0000] [28777] [INFO] Booting worker with pid: 28777

Again I am able to login and access the admin control of my Django application. Then I exited from the above command by running CTRL-C and ran this command to get python path.

(vkenv) shami@ubuntu-s-2:~/vkproject$ which python
/home/shami/vkproject/vkenv/bin/python
```
As per next documented steps, I ran this outside of the virtual env. but gunicorn was installed inside the virtual env. as stated above.

```
cat /etc/systemd/system/gunicorn.socket
[Unit]
Description=gunicorn socket

[Socket]
ListenStream=/run/gunicorn.sock
#ListenStream=/home/shami/vkproject/vikreya/vikreya.sock
#ListenStream=/home/shami/vkproject/vikreya.sock

[Install]
WantedBy=sockets.target

$ cat /etc/systemd/system/gunicorn.service
[Unit]
Description=gunicorn daemon
Requires=gunicorn.socket
After=network.target

[Service]
User=shami
Group=www-data
WorkingDirectory=/home/shami/vkproject/vikreya
WorkingDirectory=/home/shami/vkproject
ExecStart=/home/shami/vkproject/vkenv/bin/gunicorn \
          --access-logfile - \
          --workers 3 \
          --bind unix:/run/gunicorn.sock \
          vikreya.wsgi.application

[Install]
WantedBy=multi-user.target
$

$ sudo systemctl status gunicorn.socket
Failed to dump process list, ignoring: No such file or directory
● gunicorn.socket - gunicorn socket
   Loaded: loaded (/etc/systemd/system/gunicorn.socket; enabled; vendor preset: enabled)
   Active: active (listening) since Sun 2019-12-29 02:08:16 UTC; 1 weeks 0 days ago
   Listen: /run/gunicorn.sock (Stream)
   CGroup: /system.slice/gunicorn.socket
Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

$ sudo systemctl status gunicorn.service
● gunicorn.service - gunicorn daemon
   Loaded: loaded (/etc/systemd/system/gunicorn.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2019-12-15 04:22:54 UTC; 53min ago
 Main PID: 15788 (code=exited, status=1/FAILURE)

Dec 15 04:22:54 ubuntu-s-01 gunicorn[15788]:     self.stop()
Dec 15 04:22:54 ubuntu-s-01 gunicorn[15788]:   File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/arbi
Dec 15 04:22:54 ubuntu-s-01 gunicorn[15788]:     time.sleep(0.1)
Dec 15 04:22:54 ubuntu-s-01 gunicorn[15788]:   File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/arbi
Dec 15 04:22:54 ubuntu-s-01 gunicorn[15788]:     self.reap_workers()
Dec 15 04:22:54 ubuntu-s-01 gunicorn[15788]:   File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/arbi
Dec 15 04:22:54 ubuntu-s-01 gunicorn[15788]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
Dec 15 04:22:54 ubuntu-s-01 gunicorn[15788]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Dec 15 04:22:54 ubuntu-s-01 systemd[1]: gunicorn.service: Main process exited, code=exited, status=1/FAILURE
Dec 15 04:22:54 ubuntu-s-01 systemd[1]: gunicorn.service: Failed with result 'exit-code'.
```
and gunicorn version is at 

```
pip show gunicorn
Name: gunicorn
Version: 20.0.2
Summary: WSGI HTTP Server for UNIX
Home-page: http://gunicorn.org
```
Here is the log file collected from virtualenv.

```
shami@ubuntu-s-2$ source ~/vkproject/vkenv/bin/activate
(vkenv) shami@ubuntu-s-2$ gunicorn --log-file=- vikreya.wsgi:application
[2019-12-29 02:17:45 +0000] [12929] [INFO] Starting gunicorn 20.0.2
[2019-12-29 02:17:45 +0000] [12929] [INFO] Listening at: http://127.0.0.1:8000 (12929)
[2019-12-29 02:17:45 +0000] [12929] [INFO] Using worker: sync
[2019-12-29 02:17:45 +0000] [12933] [INFO] Booting worker with pid: 12933
[2019-12-29 02:17:45 +0000] [12933] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/shami/vkproject/vkenv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'vikreya'
[2019-12-29 02:17:45 +0000] [12933] [INFO] Worker exiting (pid: 12933)
[2019-12-29 02:17:45 +0000] [12929] [INFO] Shutting down: Master
[2019-12-29 02:17:45 +0000] [12929] [INFO] Reason: Worker failed to boot.
(vkenv) shami@ubuntu-s-2$ 
```
running 'GUNICORN' with preload option from virtual env.

```
(vkenv) shami@ubuntu-s-2$ gunicorn vikreya.wsgi:application --preload
Traceback (most recent call last):
  File "/home/shami/vkproject/vkenv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 219, in run
    super().run()
  File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 71, in run
    Arbiter(self).run()
  File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/shami/vkproject/vkenv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'vikreya'
(vkenv) shami@ubuntu-s-2$
```
I'm not sure what I'm missing. I appreciate if someone can help un-blocking us.

Best regards

**Comment by tilgovi** [comment]
Maybe having two working directories here is causing problems?

```
WorkingDirectory=/home/shami/vkproject/vikreya
WorkingDirectory=/home/shami/vkproject
```

You want only the second one.

If that is not enough, we will have to also add that directory to your Python path. I can help with that if you don't get success.

**Comment by rkmullapudi** [comment]
Hi Tilgovi, thank you very much for your reply. I'm pasting the result here for each one.

```
1. WorkingDirectory=/home/shami/vkproject
shami@ubuntu-s-2$ sudo systemctl daemon-reload
shami@ubuntu-s-2$ sudo systemctl restart gunicorn
shami@ubuntu-s-2$ sudo systemctl status gunicorn
● gunicorn.service - gunicorn daemon
   Loaded: loaded (/etc/systemd/system/gunicorn.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-01-06 01:56:25 UTC; 24s ago
  Process: 13842 ExecStart=/home/shami/vkproject/vkenv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunicorn.sock vikreya
 Main PID: 13842 (code=exited, status=1/FAILURE)

Jan 06 01:56:25 ubuntu-s-2 gunicorn[13842]:     self.stop()
Jan 06 01:56:25 ubuntu-s-2 gunicorn[13842]:   File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/arbi
Jan 06 01:56:25 ubuntu-s-2 gunicorn[13842]:     time.sleep(0.1)
Jan 06 01:56:25 ubuntu-s-2 gunicorn[13842]:   File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/arbi
Jan 06 01:56:25 ubuntu-s-2 gunicorn[13842]:     self.reap_workers()
Jan 06 01:56:25 ubuntu-s-2 gunicorn[13842]:   File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/arbi
Jan 06 01:56:25 ubuntu-s-2 gunicorn[13842]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
Jan 06 01:56:25 ubuntu-s-2 gunicorn[13842]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Jan 06 01:56:25 ubuntu-s-2 systemd[1]: gunicorn.service: Main process exited, code=exited, status=1/FAILURE
Jan 06 01:56:25 ubuntu-s-2 systemd[1]: gunicorn.service: Failed with result 'exit-code'.

2.  WorkingDirectory=/home/shami/vkproject/vikreya

shami@ubuntu-s-2$ sudo systemctl daemon-reload
shami@ubuntu-s-2$ sudo systemctl restart gunicorn
shami@ubuntu-s-2$
shami@ubuntu-s-2$ sudo systemctl status gunicorn
● gunicorn.service - gunicorn daemon
   Loaded: loaded (/etc/systemd/system/gunicorn.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-01-06 02:00:17 UTC; 5s ago
  Process: 13971 ExecStart=/home/shami/vkproject/vkenv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunicorn.sock vikreya
 Main PID: 13971 (code=exited, status=3)

Jan 06 02:00:16 ubuntu-s-2vcpu-2gb-sfo2-01 gunicorn[13971]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_remove
Jan 06 02:00:16 ubuntu-s-2vcpu-2gb-sfo2-01 gunicorn[13971]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Jan 06 02:00:16 ubuntu-s-2vcpu-2gb-sfo2-01 gunicorn[13971]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Jan 06 02:00:16 ubuntu-s-2vcpu-2gb-sfo2-01 gunicorn[13971]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Jan 06 02:00:16 ubuntu-s-2vcpu-2gb-sfo2-01 gunicorn[13971]: ModuleNotFoundError: No module named 'vikreya'
Jan 06 02:00:16 ubuntu-s-2vcpu-2gb-sfo2-01 gunicorn[13971]: [2020-01-06 02:00:16 +0000] [13988] [INFO] Worker exiting (pid: 13988)
Jan 06 02:00:16 ubuntu-s-2vcpu-2gb-sfo2-01 gunicorn[13971]: [2020-01-06 02:00:16 +0000] [13971] [INFO] Shutting down: Master
Jan 06 02:00:16 ubuntu-s-2vcpu-2gb-sfo2-01 gunicorn[13971]: [2020-01-06 02:00:16 +0000] [13971] [INFO] Reason: Worker failed to boot.
Jan 06 02:00:17 ubuntu-s-2vcpu-2gb-sfo2-01 systemd[1]: gunicorn.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jan 06 02:00:17 ubuntu-s-2vcpu-2gb-sfo2-01 systemd[1]: gunicorn.service: Failed with result 'exit-code'.
shami@ubuntu-s-2
```$

**Comment by rkmullapudi** [comment]
Hi Tilgovi, hope you are doing well. Please let me know if you have any suggestions for next steps. Thank you.

**Comment by benoitc** [comment]
@rkmullapudi did you try to force the python path using the setting ?

**Comment by rkmullapudi** [comment]
@benoitc sorry I don't know how to add `WorkingDirectory=/home/shami/vkproject ` in python path.

**Comment by benoitc** [comment]
@rkmullapudi  https://docs.gunicorn.org/en/stable/settings.html#pythonpath 

also makes sure every modules you want to load are available in the python path.

**Comment by rkmullapudi** [comment]
@benoitc I tried the next step as follows and I don't see any difference.

```
shami@ubuntu-s-2~/vkproject$ systemctl status gunicorn.service
● gunicorn.service - gunicorn daemon
   Loaded: loaded (/etc/systemd/system/gunicorn.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2020-01-11 18:05:52 UTC; 4s ago
  Process: 4427 ExecStart=/home/shami/vkproject/vkenv/bin/gunicorn --access-logfile - --pythonpath /home/shami/vkproject/vkenv/bin/python --workers 3 --bind unix:/
 Main PID: 4427 (code=exited, status=1/FAILURE)

Jan 11 18:05:52 ubuntu-s-2 gunicorn[4427]:     self.halt(reason=inst.reason, exit_status=inst.exit_status)
Jan 11 18:05:52 ubuntu-s-2 gunicorn[4427]:   File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 342, in halt
Jan 11 18:05:52 ubuntu-s-2 gunicorn[4427]:     self.stop()
Jan 11 18:05:52 ubuntu-s-2 gunicorn[4427]:   File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
Jan 11 18:05:52 ubuntu-s-2 gunicorn[4427]:     time.sleep(0.1)
Jan 11 18:05:52 ubuntu-s-2 gunicorn[4427]:   File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handl
Jan 11 18:05:52 ubuntu-s-2 gunicorn[4427]:     self.reap_workers()
Jan 11 18:05:52 ubuntu-s-2 gunicorn[4427]:   File "/home/shami/vkproject/vkenv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_
Jan 11 18:05:52 ubuntu-s-2 gunicorn[4427]:     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
Jan 11 18:05:52 ubuntu-s-2 gunicorn[4427]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

Here is my gunicorn.service file

```
[cat /etc/systemd/system/gunicorn.service
[Unit]
Description=gunicorn daemon
Requires=gunicorn.socket
After=network.target

[Service]
User=shami
Group=www-data
#WorkingDirectory=/home/shami/vkproject/vikreya
WorkingDirectory=/home/shami/vkproject
ExecStart=/home/shami/vkproject/vkenv/bin/gunicorn \
          --access-logfile - \
          --pythonpath /home/shami/vkproject/vkenv/bin/python \
          --workers 3 \
          --bind unix:/run/gunicorn.sock \
          vikreya.wsgi.application

[Install]
WantedBy=multi-user.target](url)

```

**Comment by rkmullapudi** [comment]
Hi, I've good news on the issue. Basically, the application name has a typo. That means I had to change my application from vikreya.wsgi.application to vikreya.wsgi**:**application. My apologies for wasting your time with the incorrect application name. I'm not sure Gunicorn should catch this kind of user mistake.
```
Jan 13 01:07:57 ubuntu-s-2 systemd[1]: Started gunicorn daemon.
Jan 13 01:07:57 ubuntu-s-2 gunicorn[22796]: [2020-01-13 01:07:57 +0000] [22796] [INFO] Starting gunicorn 20.0.2
Jan 13 01:07:57 ubuntu-s-2 gunicorn[22796]: [2020-01-13 01:07:57 +0000] [22796] [INFO] Listening at: unix:/run/gunicorn.s
Jan 13 01:07:57 ubuntu-s-2 gunicorn[22796]: [2020-01-13 01:07:57 +0000] [22796] [INFO] Using worker: sync
Jan 13 01:07:57 ubuntu-s-2 gunicorn[22796]: [2020-01-13 01:07:57 +0000] [22816] [INFO] Booting worker with pid: 22816
Jan 13 01:07:57 ubuntu-s-2 gunicorn[22796]: [2020-01-13 01:07:57 +0000] [22820] [INFO] Booting worker with pid: 22820
Jan 13 01:07:57 ubuntu-s-2 gunicorn[22796]: [2020-01-13 01:07:57 +0000] [22821] [INFO] Booting worker with pid: 22821
```
Also, I changed my project directory group ownership to 'www-data'
`drwxrwxr-x 10 shami **www-data**    4096 Dec 15 23:05 vkproject`

Please let me know if this is necessary and if this causes anything on the production hosting server if I don't change it back to previous or local user group owner?

Thank you for your support.

**Comment by rkmullapudi** [comment]
Hi, I've changed the project folder group permission back to the original one and I'm able to restart the Gunicron service fine.
```
drwxrwxr-x 3 shami shami    4096 Jan 11 23:48 vikreya

~$ sudo systemctl status gunicorn
● gunicorn.service - gunicorn daemon
   Loaded: loaded (/etc/systemd/system/gunicorn.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-01-20 23:59:33 UTC; 36s ago
 Main PID: 1445 (gunicorn)
    Tasks: 4 (limit: 2362)
   CGroup: /system.slice/gunicorn.service
           ├─1445 /home/shami/vkproject/vkenv/bin/python3 /home/shami/vkproject/vkenv/bin/gunicorn --
           ├─1465 /home/shami/vkproject/vkenv/bin/python3 /home/shami/vkproject/vkenv/bin/gunicorn --
           ├─1467 /home/shami/vkproject/vkenv/bin/python3 /home/shami/vkproject/vkenv/bin/gunicorn --
           └─1468 /home/shami/vkproject/vkenv/bin/python3 /home/shami/vkproject/vkenv/bin/gunicorn --

Jan 20 23:59:33 ubuntu-s-2 systemd[1]: Started gunicorn daemon.
Jan 20 23:59:34 ubuntu-s-2 gunicorn[1445]: [2020-01-20 23:59:34 +0000] [1445] [INFO]
Jan 20 23:59:34 ubuntu-s-2 gunicorn[1445]: [2020-01-20 23:59:34 +0000] [1445] [INFO]
Jan 20 23:59:34 ubuntu-s-2 gunicorn[1445]: [2020-01-20 23:59:34 +0000] [1445] [INFO]
Jan 20 23:59:34 ubuntu-s-2 gunicorn[1445]: [2020-01-20 23:59:34 +0000] [1465] [INFO]
Jan 20 23:59:34 ubuntu-s-2 gunicorn[1445]: [2020-01-20 23:59:34 +0000] [1467] [INFO]
Jan 20 23:59:34 ubuntu-s-2 gunicorn[1445]: [2020-01-20 23:59:34 +0000] [1468] [INFO]
```
thanks

**Comment by rkmullapudi** [comment]
Since this is no longer a valid issue for me, I'm closing the issue. Thank you all for your support.

**Comment by ayushsquad** [comment]
someone might find this useful: we had to commend out statsd_host param since our statsd endpoint was down
