### ISSUE TITLE
examples/frameworks/tornadoapp.py requires tornado<6

### ISSUE THREAD

**Issue by javabrett** [benoitc/gunicorn#2239]
Decorator `tornado.web.asynchronous` was deprecated and removed in Tornado 6.0.0, so the existing example won't run with the latest version:

```
  File "/usr/src/app/tornadoapp.py", line 13, in <module>
    from tornado.web import Application, RequestHandler, asynchronous
ImportError: cannot import name 'asynchronous' from 'tornado.web' (/usr/local/lib/python3.8/site-packages/tornado/web.py)
[2020-01-13 19:17:48 +0000] [43] [INFO] Worker exiting (pid: 43)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

Workaround is to pin with `tornado<6`.

The solution is probably to convert to use `gen.coroutine` or similar async support.

**Comment by ljluestc** [comment]
```
import tornado.ioloop
import tornado.web
from tornado import gen

class MainHandler(tornado.web.RequestHandler):
    @gen.coroutine
    def get(self):
        # Your asynchronous code here
        yield gen.sleep(1)  # Example of an asynchronous operation
        self.write("Hello, World!")

def make_app():
    return tornado.web.Application([
        (r"/", MainHandler),
    ])

if __name__ == "__main__":
    app = make_app()
    app.listen(8888)
    tornado.ioloop.IOLoop.current().start()

```

**Comment by benoitc** [comment]
no activity since awhile. closing feel free to create a new ticket if needed.

**Comment by benoitc** [comment]
your example has been applied. thanks!
