### ISSUE TITLE
inotify fails when -c is a simple filename and not a path

### ISSUE THREAD

**Issue by ahaywardtvuk** [benoitc/gunicorn#2262]
If I use -c filename.py I get a failure with inotify:

```
(venv) wagtail@d37322033517:~$ ./venv/bin/gunicorn -c gunicorn.conf.py --reload --reload-engine inotify <name>.wsgi
[2020-02-06 12:39:09 +0000] [27555] [INFO] Starting gunicorn 20.0.4
[2020-02-06 12:39:09 +0000] [27555] [INFO] Listening at: http://127.0.0.1:8000 (27555)
[2020-02-06 12:39:09 +0000] [27555] [INFO] Using worker: sync
[2020-02-06 12:39:09 +0000] [27559] [INFO] Booting worker with pid: 27559
[2020-02-06 12:39:09 +0000] [27560] [INFO] Booting worker with pid: 27560
[2020-02-06 12:39:09 +0000] [27561] [INFO] Booting worker with pid: 27561
[2020-02-06 12:39:09 +0000] [27562] [INFO] Booting worker with pid: 27562
[2020-02-06 12:39:09 +0000] [27563] [INFO] Booting worker with pid: 27563
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/opt/ccike/website/venv/lib/python3.7/site-packages/gunicorn/reloader.py", line 106, in run
    self._watcher.add_watch(dirname, mask=self.event_mask)
  File "/opt/ccike/website/venv/lib/python3.7/site-packages/inotify/adapters.py", line 95, in add_watch
    wd = inotify.calls.inotify_add_watch(self.__inotify_fd, path_bytes, mask)
  File "/opt/ccike/website/venv/lib/python3.7/site-packages/inotify/calls.py", line 35, in _check_nonnegative
    (result,))
inotify.calls.InotifyError: Call failed (should not be -1): (-1) ERRNO=(0)
```

However, if I use ./gunicorn.conf.py instead of gunicorn.conf.py it works:

```
(venv) wagtail@d37322033517:~$ ./venv/bin/gunicorn -c ./gunicorn.conf.py --reload --reload-engine inotify <name>.wsgi
[2020-02-06 12:40:33 +0000] [27587] [INFO] Starting gunicorn 20.0.4
[2020-02-06 12:40:33 +0000] [27587] [INFO] Listening at: http://127.0.0.1:8000 (27587)
[2020-02-06 12:40:33 +0000] [27587] [INFO] Using worker: sync
[2020-02-06 12:40:33 +0000] [27591] [INFO] Booting worker with pid: 27591
[2020-02-06 12:40:33 +0000] [27592] [INFO] Booting worker with pid: 27592
[2020-02-06 12:40:33 +0000] [27593] [INFO] Booting worker with pid: 27593
[2020-02-06 12:40:33 +0000] [27594] [INFO] Booting worker with pid: 27594
[2020-02-06 12:40:33 +0000] [27595] [INFO] Booting worker with pid: 27595
```

strace reveals that in the first case gunicorn uses `inotify_add_watch(9, "", IN_MODIFY|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF )`, which fails because of the empty filename.

This is with gunicorn 20.0.4.

**Comment by sandys** [comment]
lost a couple of hours due to this bug today. would appreciate atleast an error message if nothing else.
