### ISSUE TITLE
Syslog lines logged as separate entities

### ISSUE THREAD

**Issue by FrankyBoy** [benoitc/gunicorn#2275]
Hi!

I'm currently looking into using syslog (with rsyslog and TICK stack) to centralize logging for my systems. However it seems that gunicorn writes all log lines separately, so what should be a single entry becomes [number-of-lines] entries. This is very bad as these lines are not tied together, so it is not possible to write them into influxdb as one entity. 

Example from a `sudo journalctl -eu [myservice]`

```
Feb 24 08:04:15 mymachine gunicorn[6831]: AttributeError: 'NoneType' object has no attribute 'center'
Feb 24 08:04:15 mymachine gunicorn[6831]: [2020-02-24 08:04:15 +0000] [6848] [ERROR] > Exception on /admin/m2w/edit_project/400 [GET]
Feb 24 08:04:15 mymachine gunicorn[6831]: Traceback (most recent call last):
Feb 24 08:04:15 mymachine gunicorn[6831]:   File "/path/to/app/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
Feb 24 08:04:15 mymachine gunicorn[6831]:     response = self.full_dispatch_request()
Feb 24 08:04:15 mymachine gunicorn[6831]:   File "/path/to/app/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
Feb 24 08:04:15 mymachine gunicorn[6831]:     rv = self.handle_user_exception(e)
Feb 24 08:04:15 mymachine gunicorn[6831]:   File "/path/to/app/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
Feb 24 08:04:15 mymachine gunicorn[6831]:     reraise(exc_type, exc_value, tb)
Feb 24 08:04:15 mymachine gunicorn[6831]:   File "/path/to/app/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
Feb 24 08:04:15 mymachine gunicorn[6831]:     raise value
Feb 24 08:04:15 mymachine gunicorn[6831]:   File "/path/to/app/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
Feb 24 08:04:15 mymachine gunicorn[6831]:     rv = self.dispatch_request()
Feb 24 08:04:15 mymachine gunicorn[6831]:   File "/path/to/app/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
Feb 24 08:04:15 mymachine gunicorn[6831]:     return self.view_functions[rule.endpoint](**req.view_args)
Feb 24 08:04:15 mymachine gunicorn[6831]:   File "/path/to/app/venv/lib/python3.7/site-packages/flask_login.py", line 792, in decorated_view
Feb 24 08:04:15 mymachine gunicorn[6831]:     return func(*args, **kwargs)
Feb 24 08:04:15 mymachine gunicorn[6831]:   File "/path/to/app/venv/lib/python3.7/site-packages/flask_security/decorators.py", line 211, in decorated_view
Feb 24 08:04:15 mymachine gunicorn[6831]:     return fn(*args, **kwargs)
Feb 24 08:04:15 mymachine gunicorn[6831]:   File "/path/to/app/modules/security.py", line 36, in decorated_view
Feb 24 08:04:15 mymachine gunicorn[6831]:     return fn(*args, **kwargs)
Feb 24 08:04:15 mymachine gunicorn[6831]:   File "/path/to/app/views/projects.py", line 191, in edit_project
Feb 24 08:04:15 mymachine gunicorn[6831]:     geom_cu_srid = db.session.execute(func.ST_AsGeoJSON(project.center)).first().values()[0]
Feb 24 08:04:15 mymachine gunicorn[6831]: AttributeError: 'NoneType' object has no attribute 'center'
```

Which then results in logspam like this:
![image](https://user-images.githubusercontent.com/265792/75137027-bc4f4580-56e6-11ea-9034-84074d2ed4c5.png)

Which quite obviously nobody wants.

Maybe this can be fixed with a custom error formatting string somehow? But I haven't found any docs on this. 

Cheers

**Comment by FrankyBoy** [comment]
EDIT: ok so this was a fuckup of systemd in coproduction with gunicorn ... basically gunicorn logged to stdout and systemd wrote that to the logs under facility=daemon, source=gunicorn (which is obviously something gunicorn can't influence), and nothing was actually listening to my messages on 514 (and as it's udp obviously you also don't even get errors)

So the configuration I got now is
* rsyslog listening on udp:514
* have the forwarding guarded like so:
  ```
  if $syslogfacility-text != "daemon" then {
    *.* @172.16.1.73:6514;RSYSLOG_SyslogProtocol23Format
  }
  ```
that works well enough, though obviously isn't ideal yet. But that's not a gunicorn problem ;)

**Comment by benoitc** [comment]
@FrankyBoy thanks for the feedback, that will be helpful for others also!

**Comment by FrankyBoy** [comment]
Yeah, hope it helps someone who has the same issue and finds this thread when googling :)
