### ISSUE TITLE
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

### ISSUE THREAD

**Issue by nitishhrms** [benoitc/gunicorn#2280]
2020-02-27T09:04:16.442618+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2020-02-27T09:04:16.537952+00:00 heroku[web.1]: State changed from up to crashed
2020-02-27T09:04:16.520566+00:00 heroku[web.1]: Process exited with status 1
2020-02-27T09:05:58.000000+00:00 app[api]: Build started by user nitishhrms@gmail.com
2020-02-27T09:07:51.286531+00:00 app[api]: Deploy b77e0d97 by user nitishhrms@gmail.com
2020-02-27T09:07:51.286531+00:00 app[api]: Release v4 created by user nitishhrms@gmail.com
2020-02-27T09:07:52.443401+00:00 heroku[web.1]: State changed from crashed to starting
2020-02-27T09:08:04.737711+00:00 heroku[web.1]: Starting process with command `gunicorn -b :21871 app:app`
2020-02-27T09:08:06.982812+00:00 app[web.1]: [2020-02-27 09:08:06 +0000] [4] [INFO] Starting gunicorn 19.6.0
2020-02-27T09:08:06.983552+00:00 app[web.1]: [2020-02-27 09:08:06 +0000] [4] [INFO] Listening at: http://0.0.0.0:21871 (4)
2020-02-27T09:08:06.983676+00:00 app[web.1]: [2020-02-27 09:08:06 +0000] [4] [INFO] Using worker: sync
2020-02-27T09:08:06.989223+00:00 app[web.1]: [2020-02-27 09:08:06 +0000] [10] [INFO] Booting worker with pid: 10
2020-02-27T09:08:07.059937+00:00 app[web.1]: [2020-02-27 09:08:07 +0000] [11] [INFO] Booting worker with pid: 11
2020-02-27T09:08:07.357906+00:00 app[web.1]: Using TensorFlow backend.
2020-02-27T09:08:07.388488+00:00 app[web.1]: Using TensorFlow backend.
2020-02-27T09:08:08.475692+00:00 heroku[web.1]: State changed from starting to up
2020-02-27T09:08:09.923703+00:00 app[web.1]: /app/.heroku/python/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
2020-02-27T09:08:09.923719+00:00 app[web.1]:   warnings.warn(msg, category=FutureWarning)
2020-02-27T09:08:09.944359+00:00 app[web.1]: [2020-02-27 09:08:09 +0000] [11] [ERROR] Exception in worker process
2020-02-27T09:08:09.944360+00:00 app[web.1]: Traceback (most recent call last):
2020-02-27T09:08:09.944367+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
2020-02-27T09:08:09.944368+00:00 app[web.1]:     worker.init_process()
2020-02-27T09:08:09.944368+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2020-02-27T09:08:09.944368+00:00 app[web.1]:     self.load_wsgi()
2020-02-27T09:08:09.944368+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
2020-02-27T09:08:09.944369+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2020-02-27T09:08:09.944369+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2020-02-27T09:08:09.944370+00:00 app[web.1]:     self.callable = self.load()
2020-02-27T09:08:09.944370+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2020-02-27T09:08:09.944371+00:00 app[web.1]:     return self.load_wsgiapp()
2020-02-27T09:08:09.944371+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2020-02-27T09:08:09.944371+00:00 app[web.1]:     return util.import_app(self.app_uri)
2020-02-27T09:08:09.944371+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 357, in import_app
2020-02-27T09:08:09.944372+00:00 app[web.1]:     __import__(module)
2020-02-27T09:08:09.944372+00:00 app[web.1]:   File "/app/app.py", line 2, in <module>
2020-02-27T09:08:09.944373+00:00 app[web.1]:     import label_it
2020-02-27T09:08:09.944373+00:00 app[web.1]:   File "/app/label_it.py", line 22, in <module>
2020-02-27T09:08:09.944373+00:00 app[web.1]:     m=joblib.load('pokemon_model_final.pkl')
2020-02-27T09:08:09.944374+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 605, in load
2020-02-27T09:08:09.944374+00:00 app[web.1]:     obj = _unpickle(fobj, filename, mmap_mode)
2020-02-27T09:08:09.944375+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 529, in _unpickle
2020-02-27T09:08:09.944375+00:00 app[web.1]:     obj = unpickler.load()
2020-02-27T09:08:09.944375+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/pickle.py", line 1050, in load
2020-02-27T09:08:09.944376+00:00 app[web.1]:     dispatch[key[0]](self)
2020-02-27T09:08:09.944376+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/pickle.py", line 1338, in load_global
2020-02-27T09:08:09.944377+00:00 app[web.1]:     klass = self.find_class(module, name)
2020-02-27T09:08:09.944377+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/pickle.py", line 1388, in find_class
2020-02-27T09:08:09.944377+00:00 app[web.1]:     __import__(module, level=0)
2020-02-27T09:08:09.944384+00:00 app[web.1]: ModuleNotFoundError: No module named 'keras.engine.sequential'
2020-02-27T09:08:09.944757+00:00 app[web.1]: [2020-02-27 09:08:09 +0000] [11] [INFO] Worker exiting (pid: 11)
2020-02-27T09:08:09.975111+00:00 app[web.1]: /app/.heroku/python/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
2020-02-27T09:08:09.975119+00:00 app[web.1]:   warnings.warn(msg, category=FutureWarning)
2020-02-27T09:08:09.996287+00:00 app[web.1]: [2020-02-27 09:08:09 +0000] [10] [ERROR] Exception in worker process
2020-02-27T09:08:09.996289+00:00 app[web.1]: Traceback (most recent call last):
2020-02-27T09:08:09.996289+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
2020-02-27T09:08:09.996290+00:00 app[web.1]:     worker.init_process()
2020-02-27T09:08:09.996290+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2020-02-27T09:08:09.996291+00:00 app[web.1]:     self.load_wsgi()
2020-02-27T09:08:09.996291+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
2020-02-27T09:08:09.996292+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2020-02-27T09:08:09.996292+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2020-02-27T09:08:09.996293+00:00 app[web.1]:     self.callable = self.load()
2020-02-27T09:08:09.996293+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2020-02-27T09:08:09.996293+00:00 app[web.1]:     return self.load_wsgiapp()
2020-02-27T09:08:09.996294+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2020-02-27T09:08:09.996294+00:00 app[web.1]:     return util.import_app(self.app_uri)
2020-02-27T09:08:09.996295+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 357, in import_app
2020-02-27T09:08:09.996298+00:00 app[web.1]:     __import__(module)
2020-02-27T09:08:09.996298+00:00 app[web.1]:   File "/app/app.py", line 2, in <module>
2020-02-27T09:08:09.996298+00:00 app[web.1]:     import label_it
2020-02-27T09:08:09.996299+00:00 app[web.1]:   File "/app/label_it.py", line 22, in <module>
2020-02-27T09:08:09.996299+00:00 app[web.1]:     m=joblib.load('pokemon_model_final.pkl')
2020-02-27T09:08:09.996300+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 605, in load
2020-02-27T09:08:09.996300+00:00 app[web.1]:     obj = _unpickle(fobj, filename, mmap_mode)
2020-02-27T09:08:09.996300+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 529, in _unpickle
2020-02-27T09:08:09.996301+00:00 app[web.1]:     obj = unpickler.load()
2020-02-27T09:08:09.996301+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/pickle.py", line 1050, in load
2020-02-27T09:08:09.996302+00:00 app[web.1]:     dispatch[key[0]](self)
2020-02-27T09:08:09.996302+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/pickle.py", line 1338, in load_global
2020-02-27T09:08:09.996302+00:00 app[web.1]:     klass = self.find_class(module, name)
2020-02-27T09:08:09.996303+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/pickle.py", line 1388, in find_class
2020-02-27T09:08:09.996303+00:00 app[web.1]:     __import__(module, level=0)
2020-02-27T09:08:09.996304+00:00 app[web.1]: ModuleNotFoundError: No module named 'keras.engine.sequential'
2020-02-27T09:08:09.996618+00:00 app[web.1]: [2020-02-27 09:08:09 +0000] [10] [INFO] Worker exiting (pid: 10)
2020-02-27T09:08:10.238540+00:00 app[web.1]: [2020-02-27 09:08:10 +0000] [4] [INFO] Shutting down: Master
2020-02-27T09:08:10.238626+00:00 app[web.1]: [2020-02-27 09:08:10 +0000] [4] [INFO] Reason: Worker failed to boot.
2020-02-27T09:08:10.339785+00:00 heroku[web.1]: State changed from up to crashed
2020-02-27T09:08:10.320892+00:00 heroku[web.1]: Process exited with status 3
2020-02-27T09:08:24.000000+00:00 app[api]: Build succeeded

**Comment by nitishhrms** [comment]
In which library keras.engine.sequential is present.I have write keras as well as tensorflow in requirements.txt

**Comment by yyz940922** [comment]
Airflow version: 1.10.10
System: Centos7.6
env: anaconda3
After one restart for auth model edit with the intergation of https://github.com/lattebank/airflow-dag-creation-manager-plugin:
We got this error:
```
   ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2020-04-16 16:29:38,912] {__init__.py:51} INFO - Using executor LocalExecutor
[2020-04-16 16:29:38,913] {dagbag.py:396} INFO - Filling up the DagBag from /root/airflow/dags
Running the Gunicorn Server with:
Workers: 4 sync
Host: 0.0.0.0:8484
Timeout: 120
Logfiles: - -
=================================================================            
/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/apache_airflow-1.10.10-py3.7.egg/airflow/utils/sqlalchemy.py:42: DeprecationWarning: get: Accessing configuration method 'get' directly from the configuration module is deprecated. Please access the configuration from the 'configuration.conf' object via 'conf.get'
  tz = conf.get("core", "default_timezone")
/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/apache_airflow-1.10.10-py3.7.egg/airflow/utils/sqlalchemy.py:50: DeprecationWarning: get: Accessing configuration method 'get' directly from the configuration module is deprecated. Please access the configuration from the 'configuration.conf' object via 'conf.get'
  using_mysql = conf.get('core', 'sql_alchemy_conn').lower().startswith('mysql')
/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/apache_airflow-1.10.10-py3.7.egg/airflow/utils/timezone.py:30: DeprecationWarning: get: Accessing configuration method 'get' directly from the configuration module is deprecated. Please access the configuration from the 'configuration.conf' object via 'conf.get'
  tz = conf.get("core", "default_timezone")
[2020-04-16 16:29:39 +0800] [25692] [INFO] Starting gunicorn 19.8.0
[2020-04-16 16:29:39 +0800] [25692] [INFO] Listening at: http://0.0.0.0:8484 (25692)
[2020-04-16 16:29:39 +0800] [25692] [INFO] Using worker: sync
[2020-04-16 16:29:39 +0800] [25696] [INFO] Booting worker with pid: 25696
[2020-04-16 16:29:39 +0800] [25696] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/apache_airflow-1.10.10-py3.7.egg/airflow/www/app.py", line 37, in <module>
    from airflow.www.blueprints import routes
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/apache_airflow-1.10.10-py3.7.egg/airflow/www/blueprints.py", line 25, in <module>
    from airflow.www import utils as wwwutils
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/apache_airflow-1.10.10-py3.7.egg/airflow/www/utils.py", line 35, in <module>
    from flask_admin.model import filters
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/Flask_Admin-1.5.4-py3.7.egg/flask_admin/model/__init__.py", line 2, in <module>
    from .base import BaseModelView
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/Flask_Admin-1.5.4-py3.7.egg/flask_admin/model/base.py", line 8, in <module>
    from werkzeug import secure_filename
ImportError: cannot import name 'secure_filename' from 'werkzeug' (/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/werkzeug/__init__.py)
[2020-04-16 16:29:39 +0800] [25696] [INFO] Worker exiting (pid: 25696)
[2020-04-16 16:29:39 +0800] [25697] [INFO] Booting worker with pid: 25697
[2020-04-16 16:29:40 +0800] [25697] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/apache_airflow-1.10.10-py3.7.egg/airflow/www/app.py", line 37, in <module>
    from airflow.www.blueprints import routes
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/apache_airflow-1.10.10-py3.7.egg/airflow/www/blueprints.py", line 25, in <module>
    from airflow.www import utils as wwwutils
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/apache_airflow-1.10.10-py3.7.egg/airflow/www/utils.py", line 35, in <module>
    from flask_admin.model import filters
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/Flask_Admin-1.5.4-py3.7.egg/flask_admin/model/__init__.py", line 2, in <module>
    from .base import BaseModelView
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/Flask_Admin-1.5.4-py3.7.egg/flask_admin/model/base.py", line 8, in <module>
    from werkzeug import secure_filename
ImportError: cannot import name 'secure_filename' from 'werkzeug' (/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/werkzeug/__init__.py)
[2020-04-16 16:29:40 +0800] [25697] [INFO] Worker exiting (pid: 25697)
[2020-04-16 16:29:40 +0800] [25698] [INFO] Booting worker with pid: 25698
[2020-04-16 16:29:40 +0800] [25698] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/apache_airflow-1.10.10-py3.7.egg/airflow/www/app.py", line 37, in <module>
    from airflow.www.blueprints import routes
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/apache_airflow-1.10.10-py3.7.egg/airflow/www/blueprints.py", line 25, in <module>
    from airflow.www import utils as wwwutils
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/apache_airflow-1.10.10-py3.7.egg/airflow/www/utils.py", line 35, in <module>
    from flask_admin.model import filters
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/Flask_Admin-1.5.4-py3.7.egg/flask_admin/model/__init__.py", line 2, in <module>
    from .base import BaseModelView
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/Flask_Admin-1.5.4-py3.7.egg/flask_admin/model/base.py", line 8, in <module>
    from werkzeug import secure_filename
ImportError: cannot import name 'secure_filename' from 'werkzeug' (/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/werkzeug/__init__.py)
[2020-04-16 16:29:40 +0800] [25698] [INFO] Worker exiting (pid: 25698)
Traceback (most recent call last):
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 203, in run
    self.manage_workers()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
    self.spawn_workers()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 617, in spawn_workers
    time.sleep(0.1 * random.random())
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/airflow-env/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/app/base.py", line 223, in run
    super(Application, self).run()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 232, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 345, in halt
    self.stop()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
    self.reap_workers()
  File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2020-04-16 16:31:39,139] {cli.py:859} ERROR - No response from gunicorn master within 120 seconds
[2020-04-16 16:31:39,140] {cli.py:860} ERROR - Shutting down webserver

```

**Comment by jamadden** [comment]
@yyz940922 Your problem
```python traceback
 File "/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/Flask_Admin-1.5.4-py3.7.egg/flask_admin/model/base.py", line 8, in <module>
    from werkzeug import secure_filename
ImportError: cannot import name 'secure_filename' from 'werkzeug' (/root/anaconda3/envs/airflow-env/lib/python3.7/site-packages/werkzeug/__init__.py)
```

suggests that you have a missing or incorrect dependency. Check that the version of `Flask_Admin` you have installed is compatible with the version of `werkzeug` you have installed, both are correctly on the Python path, etc.

@nitishhrms You also have an import error, ` ModuleNotFoundError: No module named 'keras.engine.sequential'`. The same advice applies: check your dependencies and make sure you have compatible versions installed.

In general, this tracker can't help find problems with individual sets of requirements or dependency issues.

**Comment by anshulhedau10** [comment]
I solved it. I followed these steps: Remove all the unused libraries. Delete requirements.txt file. Create a new requirements.txt file. Commit to Git and then deploy on Heroku.
