### ISSUE TITLE
TypeError: __call__() missing 3 required positional arguments: 'scope', 'receive', and 'send'

### ISSUE THREAD

**Issue by mikelibg** [benoitc/gunicorn#2338]
Trying to start gunicorn from code with uvicorn worker (same error with gevent worker):
```
from gunicorn.app.base import BaseApplication

class GunicornApplication(BaseApplication):
    def __init__(self, app, options=None):
        self.options = options or {}
        self.application = app
        super(GunicornApplication, self).__init__()

    def init(self, parser, opts, args):
        pass

    def load_config(self):
        config = dict([(key, value) for key, value in self.options.items()
                       if key in self.cfg.settings and value is not None])
        for key, value in config.items():
            self.cfg.set(key.lower(), value)

    @property
    def load(self):
        return self.application

...

config = {
        'bind': f'{args.host}:{args.port}',
        'workers': 1,  # (2 * cpu_count()) + 1,
        'worker_class': 'uvicorn.workers.UvicornWorker',
        'timeout': 120
    }

# uvicorn.run(app, host='0.0.0.0', port=8000) # works
GunicornApplication(app, config).run()
```

Running with:
```
python=3.7

fastapi==0.55.1
gunicorn==19.9.0 (tried with gunicorn==20.0.4 as well)
uvicorn==0.11.5
```

And getting this error:
```
[2020-05-25 20:19:11 +0300] [54937] [INFO] Starting gunicorn 19.9.0
[2020-05-25 20:19:11 +0300] [54937] [INFO] Listening at: http://0.0.0.0:8000 (54937)
[2020-05-25 20:19:11 +0300] [54937] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2020-05-25 20:19:11 +0300] [54940] [INFO] Booting worker with pid: 54940
[2020-05-25 20:19:12 +0300] [54940] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/somewhere/projects/venvs/myproj/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/somewhere/projects/venvs/myproj/lib/python3.7/site-packages/uvicorn/workers.py", line 61, in init_process
    super(UvicornWorker, self).init_process()
  File "/somewhere/projects/venvs/myproj/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/somewhere/projects/venvs/myproj/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/somewhere/projects/venvs/myproj/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
TypeError: __call__() missing 3 required positional arguments: 'scope', 'receive', and 'send'
```

**Comment by mikelibg** [comment]
It is my mistake, somehow annotation of @property was added to the load method of BaseApplication wrapper. Removing it solved the issue.
