### ISSUE TITLE
gunicorn fails to import opencv and numpy on ubuntu

### ISSUE THREAD

**Issue by mhechthz** [benoitc/gunicorn#2340]
Hi,

I'm not sure whether this is the right location to post, but I try.

I hav a simple python script:
```
import sys
print('Python:',sys.version)

import cv2
print('OpenCV:',cv2.__version__)

import numpy as np
print('Numpy:',np.__version__)

def myapp():
  print('Python:',sys.version)
  print('OpenCV:',cv2.__version__)
  print('Numpy:',np.__version__)
```
The output is:
```
Python: 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0]
OpenCV: 4.2.0
Numpy: 1.18.4
```
Running gunicorn like this:
`./gunicorn 'test:myapp()'`

results in
```
3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0]
[2020-05-26 16:55:42 +0200] [22957] [INFO] Starting gunicorn 19.7.1
[2020-05-26 16:55:42 +0200] [22957] [INFO] Listening at: http://127.0.0.1:8000 (22957)
[2020-05-26 16:55:42 +0200] [22957] [INFO] Using worker: sync
[2020-05-26 16:55:42 +0200] [22960] [INFO] Booting worker with pid: 22960
Python: 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0]
ImportError: numpy.core.multiarray failed to import
[2020-05-26 16:55:42 +0200] [22960] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 377, in import_app
    __import__(module)
  File "/home/di29394/tmp/test.py", line 4, in <module>
    import cv2
  File "/home/di29394/.local/lib/python3.7/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
[2020-05-26 16:55:42 +0200] [22960] [INFO] Worker exiting (pid: 22960)
[2020-05-26 16:55:42 +0200] [22957] [INFO] Shutting down: Master
[2020-05-26 16:55:42 +0200] [22957] [INFO] Reason: Worker failed to boot.


```

Where is the problem?

**Comment by mhechthz** [comment]
Changing inside gunicorn the version check from `==` to `>=` solved the problem for me:
```
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'gunicorn>=19.7.1','console_scripts','gunicorn'
__requires__ = 'gunicorn>=19.7.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('gunicorn>=19.7.1', 'console_scripts', 'gunicorn')()
    )

```
This is quite strange.
