### ISSUE TITLE
AssertionError: This event is already used by another greenlet

### ISSUE THREAD

**Issue by desti** [benoitc/gunicorn#235]
i get the following error message if i use gevent as worker class.
the message occurs under heavy load.

2011-07-25 23:32:45 [8864] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/gunicorn-0.12.2-py2.5.egg/gunicorn/workers/async.py", line 62, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/srv/gcms_django/lib/django/contrib/staticfiles/handlers.py", line 68, in **call**
    return self.application(environ, start_response)
  File "/srv/gcms_django/lib/django/core/handlers/wsgi.py", line 273, in **call**
    response = self.get_response(request)
  File "/srv/gcms_django/lib/django/core/handlers/base.py", line 169, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/srv/gcms_django/lib/django/core/handlers/base.py", line 218, in handle_uncaught_exception
    return callback(request, *_param_dict)
  File "/srv/gcms_django/gcms/cms/views.py", line 76, in error500
    c = RequestContext(request,locals())
  File "/srv/gcms_django/lib/django/template/context.py", line 177, in **init**
    self.update(processor(request))
  File "/srv/gcms_django/gcms/cms/context_processors.py", line 26, in main_company
    request.MAIN_COMPANY = company = Company.objects.select_related(depth=1).get(id=settings.MAIN_COMPANY)
  File "/srv/gcms_django/lib/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/srv/gcms_django/lib/django/db/models/query.py", line 82, in **len**
    self._result_cache = list(self.iterator())
  File "/srv/gcms_django/lib/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/srv/gcms_django/lib/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/srv/gcms_django/lib/johnny/cache.py", line 311, in newfun
    gen_key = self.keyhandler.get_generation(_tables, **{'db':db})
  File "/srv/gcms_django/lib/johnny/cache.py", line 202, in get_generation
    return self.get_multi_generation(tables, db)
  File "/srv/gcms_django/lib/johnny/cache.py", line 220, in get_multi_generation
    generations.append(self.get_single_generation(table, db))
  File "/srv/gcms_django/lib/johnny/cache.py", line 208, in get_single_generation
    val = self.cache_backend.get(key, None, db)
  File "/srv/gcms_django/lib/johnny/transaction.py", line 82, in get
    return self.cache_backend.get(key, default)
  File "/srv/gcms_django/lib/django/core/cache/backends/memcached.py", line 58, in get
    val = self._cache.get(key)
  File "build/bdist.linux-x86_64/egg/memcache.py", line 793, in get
    return self._get('get', key)
  File "build/bdist.linux-x86_64/egg/memcache.py", line 776, in _get
    rkey, flags, rlen, = self._expectvalue(server)
  File "build/bdist.linux-x86_64/egg/memcache.py", line 886, in _expectvalue
    line = server.readline()
  File "build/bdist.linux-x86_64/egg/memcache.py", line 1055, in readline
    data = recv(4096)
  File "build/bdist.linux-x86_64/egg/gevent/socket.py", line 427, in recv
    wait_read(sock.fileno(), timeout=self.timeout, event=self._read_event)
  File "build/bdist.linux-x86_64/egg/gevent/socket.py", line 165, in wait_read
    assert event.arg is None, 'This event is already used by another greenlet: %r' % (event.arg, )
AssertionError: This event is already used by another greenlet: (<Greenlet at 0x466f958: <bound method GGeventServer.handle of <GGeventServer at 0x26f12d0 fileno=10 address=10.0.0.140:8307>>(<socket at 0x4861390 fileno=14 sock=10.0.0.140:830, ('10.0.0.150', 55333))>, timeout('timed out',))

**Comment by hatcherfang** [comment]
@tilgovi  I got the same issue. This is my error traceback:
Traceback 
"/usr/lib/python2.7/site-packages/memcache.py", line 700, in set return self._set("set", key, val, time, min_compress_len, noreply) File "/usr/lib/python2.7/site-packages/memcache.py", line 1020, in _set return _unsafe_set() File "/usr/lib/python2.7/site-packages/memcache.py", line 1008, in _unsafe_set server.send_cmd(fullcmd) File "/usr/lib/python2.7/site-packages/memcache.py", line 1395, in send_cmd self.socket.sendall(cmd + b'\r\n') File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 464, in sendall data_sent += self.send(_get_memory(data, data_sent), flags, timeout=timeleft) File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 441, in send self._wait(self._write_event) File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 292, in _wait assert watcher.callback is None, 'This socket is already used by another greenlet: %r' % (watcher.callback, ) AssertionError: This socket is already used by another greenlet: <bound method Waiter.switch of <gevent.hub.Waiter object at 0xcdd89b0>>

Do you mean this is the Gevent monkey patch that I have not added after I  import Memcached?

**Comment by tilgovi** [comment]
@hatcherfang gevent needs to apply its patch before memcache is imported.

**Comment by hatcherfang** [comment]
@tilgovi But I did not use Gevent for Memcache, it's confusing for me.
By the way, I use uwsgi to  establish the server and this is my uwsgi.ini config file:
`[uwsgi]
socket = 127.0.0.1:8001
chdir = /usr/myuwsgi/src
processes = 6
gevent = 1024
listen = 1024
module = webService
master = true
max-requests = 10240
pidfile = /var/myuwsgi/run/uwsgi.pid`

Did the `gevent = 1024`  lead to traceback error?

**Comment by tilgovi** [comment]
I'm sorry, @hatcherfang, I do not know what the gevent config for uwsgi does as far as calling monkey functions. Perhaps you should ask on the uswgi repo or forums.

**Comment by benoitc** [comment]
@hatcherfang how do you launch gunicorn? Where do you init memcache?  Also I believe that the client you're using is blocking the gevent loop (use pylibmc). If you have any simple way to reproduce the issue on our own that would help.

Other than that simply using gunicorn + nginx proxy should work.

**Comment by hatcherfang** [comment]
@tilgovi  Never mind, thank you a lot.
@benoitc  I used supervisord  to init memcached.  
The command is : 
```
[program:memcached]
command=/usr/bin/memcached -p 11211 -m 512 -c 1024 -P /var/run/recv-memcached.pid
autostart=true
startsecs=5
redirect_stderr=true
stdout_logfile=/var/log/recv-memcached.log
```
The memcached is a detached process. 
 ```
[root@logreceiver-uw2-30-1021-b-10-202-241-93 ~]# ps -ef | grep memcache
user     997   986  0 Nov02 ?        00:00:00 /usr/bin/memcached -p 11211 -m 512 -c 1024 -P /var/user/run/xxx-memcached.pid
```
You are right. I should first reproduce the issue or it is difficult for me to solve it.

**Comment by jamadden** [comment]
According to the traceback:
```
File "/usr/lib64/python2.7/site-packages/gevent/socket.py", line 292, 
in _wait assert watcher.callback is   None,
 'This socket is already used by another greenlet: %r' % (watcher.callback, ) 
```

This is gevent 1.0.1 or older. I would suggest upgrading; 1.2.2 is the current version.

**Comment by hatcherfang** [comment]
@jamadden  this is our product environment and it is not easy to upgrade version. Thank you for your advice.
