### ISSUE TITLE
Gunicorn doesn't want to run with admin privilegies on Raspberry Pi

### ISSUE THREAD

**Issue by invictusro** [benoitc/gunicorn#2442]
Hello guys so I do have the next problem, my Gunicorn path is not recognized with sudo privileges which is really weird
![image](https://user-images.githubusercontent.com/70700053/97084746-db112d80-1621-11eb-85b1-42768975834b.png)

I wanted to start gunicorn on startup like this with systemctl using this:
```
[Unit]
Description=Gunicorn Flask

[Service]
Type=simple
WorkingDirectory=/home/pi/Desktop/app
ExecStart=/home/pi/.local/bin/gunicorn --config /home/pi/Desktop/app/gconfig.py main:app

[Install]
WantedBy=multi-user.target

```
But on startup I'm getting the same error as when I'm using sudo privileges why is this happening ?

![image](https://user-images.githubusercontent.com/70700053/97084766-f2501b00-1621-11eb-8ecf-9aa624b76eab.png)

Here is my gunicorn config.py but this has nothing to do with the error because everything works really fine when not using the sudo privileges and I can start my Flask app with no problems using this command:

`/home/pi/.local/bin/gunicorn --config /home/pi/Desktop/app/gconfig.py main:app`

![image](https://user-images.githubusercontent.com/70700053/97084838-422ee200-1622-11eb-89c6-6ab813e2ccc2.png)

Thank you! I do hope to solve this

**Comment by jamadden** [comment]
What errors are you getting? Please always post the errors as text, never images.

**Comment by invictusro** [comment]
> What errors are you getting? Please always post the errors as text, never images.
> […](#)
> On Oct 24, 2020, at 09:59, Invictus ***@***.***> wrote: Hello guys so I do have the next problem, my Gunicorn path is not recognized with sudo privileges which is really weird I wanted to start gunicorn on startup like this with systemctl using this: [Unit] Description=Gunicorn Flask [Service] Type=simple WorkingDirectory=/home/pi/Desktop/app ExecStart=/home/pi/.local/bin/gunicorn --config /home/pi/Desktop/app/gconfig.py main:app [Install] WantedBy=multi-user.target But on startup I'm getting the same error as when I'm using sudo privileges why is this happening ? Here is my gunicorn config.py but this has nothing to do with the error because everything works really fine when not using the sudo privileges and I can start my Flask app with no problems using this command: /home/pi/.local/bin/gunicorn --config /home/pi/Desktop/app/gconfig.py main:app Thank you! I do hope to solve this

Ohh. Sorry :)
Using this command: 
```
/home/pi/.local/bin/gunicorn 
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: No application module specified.
```

So basically it recognizes gunicorn as being there and when I do use this command with sudo:
```
sudo /home/pi/.local/bin/gunicorn
Traceback (most recent call last):
  File "/home/pi/.local/bin/gunicorn", line 6, in <module>
    from gunicorn.app.wsgiapp import run
ModuleNotFoundError: No module named 'gunicorn'
```
This is basically what happens when I'm trying to run gunicorn on startup with system ctl. Here is the systemctl errors:
gserv.service - Gunicorn Flask
```
   Loaded: loaded (/etc/systemd/system/gserv.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2020-10-24 17:47:13 EEST; 2min 47s ago
  Process: 374 ExecStart=/home/pi/.local/bin/gunicorn --config /home/pi/Desktop/app/gconfig.py main:app (code=
 Main PID: 374 (code=exited, status=1/FAILURE)

Oct 24 17:47:12 raspberrypi systemd[1]: Started Gunicorn Flask.
Oct 24 17:47:13 raspberrypi gunicorn[374]: Traceback (most recent call last):
Oct 24 17:47:13 raspberrypi gunicorn[374]:   File "/home/pi/.local/bin/gunicorn", line 6, in <module>
Oct 24 17:47:13 raspberrypi gunicorn[374]:     from gunicorn.app.wsgiapp import run
Oct 24 17:47:13 raspberrypi gunicorn[374]: ModuleNotFoundError: No module named 'gunicorn'
Oct 24 17:47:13 raspberrypi systemd[1]: gserv.service: Main process exited, code=exited, status=1/FAILURE
Oct 24 17:47:13 raspberrypi systemd[1]: gserv.service: Failed with result 'exit-code'.
```

And as I said this command starts my program with no issues at all:
`/home/pi/.local/bin/gunicorn --config /home/pi/Desktop/app/gconfig.py main:app`

**Comment by jamadden** [comment]
> Using this command:
> 
> /home/pi/.local/bin/gunicorn 
> 
> usage: gunicorn [OPTIONS] [APP_MODULE]
> 
> gunicorn: error: No application module specified.
> 
> 
> So basically it recognizes gunicorn as being there and when I do use this command with sudo:
> 
> sudo /home/pi/.local/bin/gunicorn
> 
> Traceback (most recent call last):
> 
>   File "/home/pi/.local/bin/gunicorn", line 6, in <module>
> 
>     from gunicorn.app.wsgiapp import run
> 
> ModuleNotFoundError: No module named 'gunicorn'

I'm guessing you installed gunicorn using `pip install --user`. That's why it's in /home/pi/.local. $HOME/.local is on sys.path automatically, but $HOME is different when you run as different users. Thus the root user can't import the gunicorn (or anything) installed in /home/pi/.local (because it would have 

I suggest creating a virtual environment and installing your software, including gunicorn, in that. The commands in that environment will work for any user.

**Comment by invictusro** [comment]
Hmm. Yeah, I haven’t worked with virtual envs but I gues that I have to

**Comment by invictusro** [comment]
> Using this command: /home/pi/.local/bin/gunicorn usage: gunicorn [OPTIONS] [APP_MODULE] gunicorn: error: No application module specified. So basically it recognizes gunicorn as being there and when I do use this command with sudo: sudo /home/pi/.local/bin/gunicorn Traceback (most recent call last): File "/home/pi/.local/bin/gunicorn", line 6, in <module> from gunicorn.app.wsgiapp import run ModuleNotFoundError: No module named 'gunicorn'
> I'm guessing you installed gunicorn using `pip install --user`. That's why it's in /home/pi/.local. $HOME/.local is on sys.path automatically, but $HOME is different when you run as different users. Thus the root user can't import the gunicorn (or anything) installed in /home/pi/.local (because it would have I suggest creating a virtual environment and installing your software, including gunicorn, in that. The commands in that environment will work for any user.

I have installed using "pip install gunicorn". I was wondering if there is any solution to solve this, if there is none I will try with virtual envs. I was trying to make the process as simple as I can because I have to install it on multiple devices

**Comment by tilgovi** [comment]
I'm closing this due to inactivity. Thank you both for the questions and answers.
