### ISSUE TITLE
"OSError: [Errno 12] Cannot allocate memory" on worker autorestart

### ISSUE THREAD

**Issue by KrishnaRohitDatla** [benoitc/gunicorn#2514]
On Auto restart of the worker after reaching 'max_request' limit, occasionally I encounter "OSError: [Errno 12] Cannot allocate memory"

My observation = 

- Looking at instance metrics in AWS, I see that memory utilization is always under 60 percent, but still, I encounter the above error. I don't think it is actually a memory problem, since I am only running 3 workers on a 4GB instance where the model size is around 450 MB. 

- The error only occurs when trying to perform an auto restart. At times the auto-restart is performed successfully but in few cases, it fails with the below error log. 

- Started getting this error after an increase in model size by around 50 MB

- I think the reason is, during auto restart the memory already occupied by the worker is not freed up completely and as a result, the new worker doesn't have sufficient memory to get started

running on = ml.t2.medium i.e 2 CPU, 4GB memory
machine learning model size = 450MB
gunicorn20.0.4
my gunicorn config - 

['gunicorn',
 '--timeout', '60',
 '-k', 'sync',
 '--preload',
 '--worker-connections', '1',
 '--max-requests', '500',
 '--max-requests-jitter', '100',
 '-b', 'unix:/tmp/gunicorn.sock',
 '-w', '3',
 'wsgi:app']

error = 
[2021-02-08 23:44:12 +0000] [19] [INFO] Autorestarting worker after current request.
10.32.0.2 - - [08/Feb/2021:23:44:12 +0000] "GET /ping HTTP/1.1" 200 1 "-" "AHC/2.0"
[2021-02-08 23:44:12 +0000] [19] [INFO] Worker exiting (pid: 19)
[2021-02-08 23:44:18 +0000] [12] [INFO] Unhandled exception in main loop
2021-02-09T05:14:21.877+05:30
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/arbiter.py", line 211, in run
    self.manage_workers()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/arbiter.py", line 545, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/arbiter.py", line 616, in spawn_workers
    self.spawn_worker()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/arbiter.py", line 567, in spawn_worker
    pid = os.fork()
2021-02-09T05:14:21.877+05:30 OSError: [Errno 12] Cannot allocate memory

Please let me know your thoughts about the problem

Thanks

**Comment by benoitc** [comment]
If you preload the model will be in shared memory and memory is indeed not freed. You should try to make your work asynchronous and only query the result from the web app.

**Comment by benoitc** [comment]
closing issue. no feedback from the requester.
