### ISSUE TITLE
RecursionError when using gunicorn 20.0.4 with gevent 21.1.2 to serve Django 3.1

### ISSUE THREAD

**Issue by merajnouredini** [benoitc/gunicorn#2515]
Hello everyone,
We have a Django website served using gunicorn 20.0.4, which uses `storages.backends.s3boto3.S3ManifestStaticStorage`, we've changed the worker class to 'gevent' recently and found the website broken.
I've searched through the net and read the related issues, and it seems that the issue is fixed, but I get the following errors:
```
/usr/local/lib/python3.8/site-packages/gunicorn/workers/ggevent.py:53: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util.ssl_ (/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py)', 'urllib3.util (/usr/local/lib/python3.8/site-packages/urllib3/util/__init__.py)']. 
  monkey.patch_all()
Internal Server Error: /user/login
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/user/web/views.py", line 6, in login_page
    return render(request, 'user/login.html')
  File "/usr/local/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/templatetags/static.py", line 106, in render
    url = self.url(context)
  File "/usr/local/lib/python3.8/site-packages/django/templatetags/static.py", line 103, in url
    return self.handle_simple(path)
  File "/usr/local/lib/python3.8/site-packages/django/templatetags/static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 240, in inner
    self._setup()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 438, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 373, in __init__
    self.hashed_files = self.load_manifest()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 383, in load_manifest
    content = self.read_manifest()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 377, in read_manifest
    with self.open(self.manifest_name) as manifest:
  File "/usr/local/lib/python3.8/site-packages/django/core/files/storage.py", line 36, in open
    return self._open(name, mode)
  File "/usr/local/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 427, in _open
    f = S3Boto3StorageFile(name, mode, self)
  File "/usr/local/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 104, in __init__
    self.obj = storage.bucket.Object(name)
  File "/usr/local/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 361, in bucket
    self._bucket = self.connection.Bucket(self.bucket_name)
  File "/usr/local/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 341, in connection
    self._connections.connection = session.resource(
  File "/usr/local/lib/python3.8/site-packages/boto3/session.py", line 384, in resource
    client = self.client(
  File "/usr/local/lib/python3.8/site-packages/boto3/session.py", line 258, in client
    return self._session.create_client(
  File "/usr/local/lib/python3.8/site-packages/botocore/session.py", line 834, in create_client
    client = client_creator.create_client(
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 85, in create_client
    client_args = self._get_client_args(
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 326, in _get_client_args
    return args_creator.get_client_args(
  File "/usr/local/lib/python3.8/site-packages/botocore/args.py", line 99, in get_client_args
    endpoint = endpoint_creator.create_endpoint(
  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 292, in create_endpoint
    http_session = http_session_cls(
  File "/usr/local/lib/python3.8/site-packages/botocore/httpsession.py", line 180, in __init__
    self._manager = PoolManager(**self._get_pool_manager_kwargs())
  File "/usr/local/lib/python3.8/site-packages/botocore/httpsession.py", line 188, in _get_pool_manager_kwargs
    'ssl_context': self._get_ssl_context(),
  File "/usr/local/lib/python3.8/site-packages/botocore/httpsession.py", line 197, in _get_ssl_context
    return create_urllib3_context()
  File "/usr/local/lib/python3.8/site-packages/botocore/httpsession.py", line 72, in create_urllib3_context
    context.options |= options
  File "/usr/local/lib/python3.8/ssl.py", line 602, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/local/lib/python3.8/ssl.py", line 602, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/usr/local/lib/python3.8/ssl.py", line 602, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 379 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
127.0.0.1 - - [09/Feb/2021:08:10:21 +0000] "GET /user/login HTTP/1.1" 500 145 "-" "curl/7.64.0"
```
looking at the first line:
```
/usr/local/lib/python3.8/site-packages/gunicorn/workers/ggevent.py:53: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util.ssl_ (/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py)', 'urllib3.util (/usr/local/lib/python3.8/site-packages/urllib3/util/__init__.py)']. 
  monkey.patch_all()
```
it seems the warning is related to the issue and we should call the `monkey.patch_all()` earlier, but I do not have any idea how to do that. any help would be appreciated.

here are the environment specifications:
```
python 3.8
django 3.1
boto3 1.16.47
gunicorn 20.0.4
gevent 21.1.2
```

gunicorn config:
```
from django.conf import settings

bind = "0.0.0.0:8000"

pythonpath = settings.BASE_DIR

workers = 12
worker_class = 'gevent'
worker_connections = 1000
timeout = 300
keepalive = 2
accesslog = '-'
errorlog = '-'
loglevel = 'warning'
```

**Comment by tilgovi** [comment]
Is `from django.conf import settings` here importing a module from your application? The gevent worker will monkey patch for you and you should not need to do it yourself, but if you import code in your config file you may cause things to import before the monkey patch.

There have been reports that Gunicorn could monkey patch earlier and it would work, so you might be able to do it even in your config file, before you make any other imports. See https://github.com/benoitc/gunicorn/pull/1828 for more information. But the safest thing is to see if you can set the python path without performing those imports.

**Comment by m-nouredini** [comment]
Sorry for my late response,
I think I tried monkey patching in the first line of the settings file, and it caused some wired behavior, the server couldn't start and every manage.py command stuck right after running them.

**Comment by venkatesan001** [comment]
am also facing this issue. Any update?

**Comment by m-nouredini** [comment]
@venkatesan001 No, unfortunately I couldn't make it work so I gave up using gevent.

**Comment by eadwinCode** [comment]
This code arrangement works for me in wsgi.py file

```python
"""
WSGI config for bookstore project. And my project also uses django-storage

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/howto/deployment/wsgi/
"""
import os
from gevent import monkey
from psycogreen.gevent import patch_psycopg


monkey.patch_all()
patch_psycopg()

from django.core.wsgi import get_wsgi_application
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'your_django.settings')
application = get_wsgi_application()

```

Then start up your gunicorn
`gunicorn --worker-class gevent --bind 0.0.0.0:8080 you_django_app:wsgi
`

**Comment by dolfinus** [comment]
Got just the same thing on MLflow 1.17 (Flask-based app) + gunicorn 20.1.0 + boto3 1.14.26 without gevent installed.
Server run command is:
```bash
gunicorn -b 0.0.0.0:5000 -w 4 mlflow.server:app
```

**Comment by s4ke** [comment]
For anyone stumbling across this. @eadwinCode 's suggestion was required for our code to work properly when upgrading to Python 3.9/3.10. We had the patches in post_fork, but for Python >3.9 apparently this needs to be done earlier.

**Comment by s4ke** [comment]
To get around the monkey patching causing issues with manage commands you have to make sure that *only* code that runs in gunicorn/gevent has the monkey patches enabled. we solved this with a simple env var as high up possible in the import chain as possible:

```
if os.environ.get('RUNNING_GUNICORN', 'false') == 'true':
    # python 3.9 and python 3.10 need this to be done as soon as possible
    # also, only do this for gunicorn. Celery workers are still
    # using the sync workers since its simpler
    from psycogreen.gevent import patch_psycopg  # type: ignore
    from gevent import monkey
    monkey.patch_all()
    patch_psycopg()
```

And then in our central run bash script we simply do:

```
  RUNNING_GUNICORN=true exec gunicorn \
    --timeout "${worker_timeout}" \
    --capture-output \
    --access-logfile - \
    --error-logfile - \
    --log-file - \
    --log-level $log_level \
    --access-logformat "$gunicorn_access_log_format" \
    -k $worker_type \
    --workers=$worker_count \
    ${statsd_gunicorn_params} \
    --limit-request-line "$gunicorn_limit_request_line" \
    -c python:ourapp.gunicorn \
    -b $bind_ip:8000 \
    ourapp.wsgi
```
