### ISSUE TITLE
unable to start a custom worker

### ISSUE THREAD

**Issue by nskalis** [benoitc/gunicorn#2571]
Hi,

Given the environment:
```
> python --version
Python 3.8.7
> uvicorn --version
Running uvicorn 0.13.3 with CPython 3.8.7 on Linux
> gunicorn --version
gunicorn (version 20.1.0)
```

and a custom worker class based on `unicorn` as documented here https://www.uvicorn.org/deployment/#gunicorn
```
from uvicorn.workers import UvicornWorker


class WSprotoUvicornWorker(UvicornWorker):
    CONFIG_KWARGS = {
        "loop": "uvloop",
        "http": "httptools",
        "ws": "wsproto",
    }
```

When I try run the api using `uvicorn`:
```
> /home/app/.pyenv/shims/uvicorn glass:api --reload --port 5048 --ws wsproto
INFO:     Uvicorn running on http://127.0.0.1:5048 (Press CTRL+C to quit)
INFO:     Started reloader process [117944] using watchgod
INFO:     Started server process [117990]
INFO:     Waiting for application startup.
INFO:     Application startup complete.

```

When I try to run the api under `gunicorn`, I encounter the following issue:
```
> /home/app/.local/bin/gunicorn --bind 127.0.0.1:5048 --workers 1 --worker-class uvicorn.workers.WSprotoUvicornWorker --log-config config/logging.conf glass:api 
2021-04-27 20:21:43 [118032] [INFO] Starting gunicorn 20.1.0
2021-04-27 20:21:43 [118032] [INFO] Starting gunicorn 20.1.0
2021-04-27 20:21:43 [118032] [INFO] Listening at: http://127.0.0.1:5048 (118032)
2021-04-27 20:21:43 [118032] [INFO] Listening at: http://127.0.0.1:5048 (118032)
2021-04-27 20:21:43 [118032] [INFO] Using worker: uvicorn.workers.WSprotoUvicornWorker
2021-04-27 20:21:43 [118032] [INFO] Using worker: uvicorn.workers.WSprotoUvicornWorker
2021-04-27 20:21:43 [118032] [INFO] Unhandled exception in main loop
Traceback (most recent call last):
  File "/home/app/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/home/app/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
    self.spawn_workers()
  File "/home/app/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 622, in spawn_workers
    self.spawn_worker()
  File "/home/app/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 569, in spawn_worker
    worker = self.worker_class(self.worker_age, self.pid, self.LISTENERS,
TypeError: 'str' object is not callable
2021-04-27 20:21:43 [118032] [INFO] Unhandled exception in main loop
Traceback (most recent call last):
  File "/home/app/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/home/app/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
    self.spawn_workers()
  File "/home/app/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 622, in spawn_workers
    self.spawn_worker()
  File "/home/app/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 569, in spawn_worker
    worker = self.worker_class(self.worker_age, self.pid, self.LISTENERS,
TypeError: 'str' object is not callable
```

Can you please advise what can be the reason why the workers are not spawned?

**Comment by Junnplus** [comment]
You should use custom worker class path instead of `uvicorn.workers.WSprotoUvicornWorker`

**Comment by nskalis** [comment]
thanks @Junnplus for looking into it.

```
> /home/app/.local/bin/gunicorn --bind 127.0.0.1:5048 --workers 1 --worker-class WSprotoUvicornWorker --log-config config/logging.conf glass:api 

Error: class uri 'WSprotoUvicornWorker' invalid or not found: 

[Traceback (most recent call last):
  File "/home/app/.local/lib/python3.8/site-packages/gunicorn/util.py", line 88, in load_class
    return pkg_resources.load_entry_point(
  File "/home/app/.pyenv/versions/3.8.7/lib/python3.8/site-packages/pkg_resources/__init__.py", line 488, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/app/.pyenv/versions/3.8.7/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2860, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('gunicorn.workers', 'WSprotoUvicornWorker') not found
]

> pwd
/home/app/ip-spotlight/code/api/glass

> ls
client.py  config  glass.py  __pycache__  schemas.py  WSprotoUvicornWorker.py
```

How we make `gunicorn.workers` know about `WSprotoUvicornWorker` ?

**Comment by jamadden** [comment]
Try using the fully qualified name of your worker class. As you can see from the code and the error message, if you don't use a fully qualified name, gunicorn tries some alternate lookups (which of course fail).

**Comment by nskalis** [comment]
@jamadden thanks for the help, but I am not able to follow :( is it an idea maybe to possibly provide an example?

- `gunicorn` binary is located at `/home/app/.local/bin/gunicorn`
- `glass.py` is the api itself and it is located at `/home/app/ip-spotlight/code/api/glass`
- `WSprotoUvicornWorker.py` is the worker class and located at `/home/app/ip-spotlight/code/api/glass`
- `/home/app/.local/bin/gunicorn --bind 127.0.0.1:5048 --workers 1 --worker-class WSprotoUvicornWorker --log-config config/logging.conf glass:api` is the command I issue while being at the directory `/home/app/ip-spotlight/code/api/glass`

**Comment by jamadden** [comment]
> `WSprotoUvicornWorker.py` is the worker class

I doubt it. That's a file (corresponding to a module), not a class.

If you have a file `foo.py`, and `foo.py` looks like this:
```python
class Worker(…):
   …
```

The fully qualified name of the worker class would be `foo.Worker` (i.e., the fully qualified name of the module, plus the name of the class). Naturally, if you have things nested more deeply in packages, your qualified name would be longer. If this is unfamiliar, perhaps do some reading on Python modules, Python packages, and how Python's `sys.path` is used.

**Comment by nskalis** [comment]
a ha, the class path. thanks a lot!
