### ISSUE TITLE
ssl ciphers issues with gunicorn and uvicorn issues TLS1_2

### ISSUE THREAD

**Issue by mariobriggs** [benoitc/gunicorn#2578]
Here is my scenario

Retrieve tlsv12 ciphers available to python ssl module
```
import ssl, pprint
ctx = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
ciphers = ctx.get_ciphers()
v12 = []
for cip in ciphers:
  if cip['protocol'] == 'TLSv1.2':  
    v12.append(cip['name'])
':'.join(v12)
```
output : 
```
ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256
```

Now try to run gunicorn (with uvicorn workers) using the available cipher list

```
export CIPHERLIST=ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256

gunicorn -k uvicorn.workers.UvicornWorker --bind=0.0.0.0:9999 --workers=1 --certfile=<path_to_crt> --keyfile=<path_to_key> --ssl-version=TLSv1_2  --ciphers=CIPHERLIST xxx.yyy:app
[2021-04-20 12:01:49 +0000] [315] [INFO] Starting gunicorn 20.0.4
[2021-04-20 12:01:49 +0000] [315] [INFO] Listening at: https://0.0.0.0:9999 (315)
[2021-04-20 12:01:49 +0000] [315] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2021-04-20 12:01:49 +0000] [317] [INFO] Booting worker with pid: 317
[2021-04-20 12:01:50 +0000] [317] [err] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/workers.py", line 63, in init_process
    super(UvicornWorker, self).init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 140, in init_process
    self.run()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/workers.py", line 76, in run
    loop.run_until_complete(server.serve(sockets=self.sockets))
  File "uvloop/loop.pyx", line 1494, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 55, in serve
    config.load()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 273, in load
    self.ssl = create_ssl_context(
  File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 114, in create_ssl_context
    ctx.set_ciphers(ciphers)
ssl.SSLError: ('No cipher can be selected.',)
```

**Comment by mariobriggs** [comment]
closing. sorry above works, there was typo my side. 

>--ciphers=CIPHERLIST

should have been

--ciphers=$CIPHERLIST
