### ISSUE TITLE
eventlet v0.30.2 breaks gunicorn with ImportError

### ISSUE THREAD

**Issue by goodspark** [benoitc/gunicorn#2582]
I'm using gunicorn and the geventlet worker class. I recently upgraded to eventlet from 0.29.1 to 0.31.0 to address a security vulnerability (https://github.com/eventlet/eventlet/security/advisories/GHSA-9p9m-jm8w-94p2).

Now when my app starts, gunicorn fails:

```
[Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/util.py", line 99, in load_class
    mod = importlib.import_module('.'.join(components))
  File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 23, in <module>
    from eventlet.wsgi import ALREADY_HANDLED as EVENTLET_ALREADY_HANDLED
ImportError: cannot import name 'ALREADY_HANDLED' from 'eventlet.wsgi' (/app/.heroku/python/lib/python3.8/site-packages/eventlet/wsgi.py)
```

Looks like this was broken in eventlet 0.30.3 (https://github.com/eventlet/eventlet/commit/df0bc00c3b758b0a632929a7ade2125d0a80c08a#diff-f5505c9146e0d3140cc0c6685771ff0a4f0cbadcb95e8115ce2501744007a9f4L72-L84).

Edit: Looks like https://github.com/benoitc/gunicorn/pull/2581/files already solves this!

**Comment by benoitc** [comment]
fixed in latest master.
