### ISSUE TITLE
gevent.exceptions.BlockingSwitchOutError: Impossible to call blocking function in the event loop callback

### ISSUE THREAD

**Issue by felixgao** [benoitc/gunicorn#2586]
`ctrl-c` on docker image running gunicorn 20.1.0
I also don't understand why is gevent used when I choose `sync` worker_class. 
```
[2021-05-26 22:33:24 +0000] [6] [DEBUG] Current configuration:
  config: /gunicorn_conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8080']
  backlog: 2048
  workers: 2
  worker_class: sync
  threads: 8
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 1000
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /usr/local/app
  daemon: False
  raw_env: ['FLASK_ENV=local']
  pidfile: /var/run/gunicorn.pid
  worker_tmp_dir: /dev/shm
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: -
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: False
  logger_class: <class '__config__.CustomGunicornLogger'>
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags:
  statsd_prefix:
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f11f8b952f0>
  on_reload: <function OnReload.on_reload at 0x7f11f8b95400>
  when_ready: <function WhenReady.when_ready at 0x7f11f8b95510>
  pre_fork: <function Prefork.pre_fork at 0x7f11f8b95620>
  post_fork: <function Postfork.post_fork at 0x7f11f8b95730>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f11f8b95840>
  worker_int: <function WorkerInt.worker_int at 0x7f11f8b95950>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f11f8b95a60>
  pre_exec: <function PreExec.pre_exec at 0x7f11f8b95b70>
  pre_request: <function PreRequest.pre_request at 0x7f11f8b95c80>
  post_request: <function PostRequest.post_request at 0x7f11f8b95d08>
  child_exit: <function ChildExit.child_exit at 0x7f11f8b95e18>
  worker_exit: <function WorkerExit.worker_exit at 0x7f11f8b95f28>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f11f895c0d0>
  on_exit: <function OnExit.on_exit at 0x7f11f895c1e0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2021-05-26 22:33:24 +0000] [6] [INFO] Starting gunicorn 20.1.0
[2021-05-26 22:33:24 +0000] [6] [DEBUG] Arbiter booted
[2021-05-26 22:33:24 +0000] [6] [INFO] Listening at: http://0.0.0.0:8080 (6)
[2021-05-26 22:33:24 +0000] [6] [INFO] Using worker: gthread
[2021-05-26 22:33:24 +0000] [9] [INFO] Booting worker with pid: 9
[2021-05-26 22:33:24 +0000] [10] [INFO] Booting worker with pid: 10
[2021-05-26 22:33:24 +0000] [6] [DEBUG] 2 workers
[2021-05-26 22:33:31 +0000] [10] [DEBUG] GET /health/full
[2021-05-26 22:33:31 +0000] [10] [DEBUG] Closing connection.
^C[2021-05-26 22:33:36 +0000] [6] [INFO] Handling signal: int
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 103, in handle_quit
    time.sleep(0.1)
  File "/usr/local/lib/python3.6/site-packages/gevent/hub.py", line 159, in sleep
    hub.wait(t)
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 151, in gevent.__waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 66, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
  File "src/gevent/_greenlet_primitives.py", line 67, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
gevent.exceptions.BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
2021-05-26T22:33:36Z
[2021-05-26 22:33:36 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 142, in init_process
    self.run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 200, in run
    events = self.poller.select(1.0)
  File "/usr/local/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 103, in handle_quit
    time.sleep(0.1)
  File "/usr/local/lib/python3.6/site-packages/gevent/hub.py", line 159, in sleep
    hub.wait(t)
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 151, in gevent.__waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
gevent.exceptions.BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
[2021-05-26 22:33:36 +0000] [9] [INFO] Worker exiting (pid: 9)
[2021-05-26 22:33:38 +0000] [6] [INFO] Shutting down: Master
```

**Comment by benoitc** [comment]
stalled issue
