### ISSUE TITLE
Eventlet recently made a change that created a bug

### ISSUE THREAD

**Issue by chidioguejiofor** [benoitc/gunicorn#2590]
While running my app with Gunicorn(using eventlet as the worker class, I get the following error:

```

2021-06-02T16:01:10.867028+00:00 app[web.1]: Error: class uri 'eventlet' invalid or not found: 
2021-06-02T16:01:10.867029+00:00 app[web.1]: 
2021-06-02T16:01:10.867030+00:00 app[web.1]: [Traceback (most recent call last):
2021-06-02T16:01:10.867030+00:00 app[web.1]:   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 99, in load_class
2021-06-02T16:01:10.867031+00:00 app[web.1]:     mod = importlib.import_module('.'.join(components))
2021-06-02T16:01:10.867031+00:00 app[web.1]:   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
2021-06-02T16:01:10.867031+00:00 app[web.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2021-06-02T16:01:10.867032+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2021-06-02T16:01:10.867033+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2021-06-02T16:01:10.867033+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2021-06-02T16:01:10.867034+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2021-06-02T16:01:10.867034+00:00 app[web.1]:   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
2021-06-02T16:01:10.867034+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2021-06-02T16:01:10.867035+00:00 app[web.1]:   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 20, in <module>
2021-06-02T16:01:10.867093+00:00 app[web.1]:     from eventlet.wsgi import ALREADY_HANDLED as EVENTLET_ALREADY_HANDLED
2021-06-02T16:01:10.867094+00:00 app[web.1]: ImportError: cannot import name 'ALREADY_HANDLED' from 'eventlet.wsgi' (/usr/local/lib/python3.8/site-packages/eventlet/wsgi.py)
```

After investigating, I found that this was caused by a breaking change in eventlet. See [this issue](https://github.com/benoitc/gunicorn/pull/2581)  for more info. 

#### Environment
Gunicorn: 20.1.0
Python: 3.8.2

**Comment by benoitc** [comment]
@Medve01 check https://github.com/benoitc/gunicorn/milestone/20 progress
