### ISSUE TITLE
OSError: [Errno 92] Protocol not available - Gunicorn on WSL2 

### ISSUE THREAD

**Issue by Rathan007** [benoitc/gunicorn#2694]
im trying to run gunicorn on windows WSL ubuntu 20.04 LTS 
```python
gunicorn app:app --worker-class gevent --bind 127.0.0.1:8000
```
when i try to run this i get the following error 
```
(venv) $ gunicorn app:app --worker-class gevent --bind 127.0.0.1:8000
[2021-11-24 18:27:19 +0530] [10622] [INFO] Starting gunicorn 20.1.0
[2021-11-24 18:27:19 +0530] [10622] [INFO] Listening at: http://127.0.0.1:8000 (10622)
[2021-11-24 18:27:19 +0530] [10622] [INFO] Using worker: gevent
[2021-11-24 18:27:19 +0530] [10624] [INFO] Booting worker with pid: 10624
[2021-11-24 18:27:19 +0530] [10624] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/mnt/w/OFFICE/ImgClr_Identify_V4/pubsub/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/mnt/w/OFFICE/ImgClr_Identify_V4/pubsub/venv/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 144, in init_process
    self.patch()
  File "/mnt/w/OFFICE/ImgClr_Identify_V4/pubsub/venv/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 43, in patch
    sockets.append(socket.socket(s.FAMILY, socket.SOCK_STREAM,
  File "/mnt/w/OFFICE/ImgClr_Identify_V4/pubsub/venv/lib/python3.8/site-packages/gevent/_socket3.py", line 133, in __init__
    self._sock = self._gevent_sock_class(family, type, proto, fileno)
OSError: [Errno 92] Protocol not available
[2021-11-24 18:27:19 +0530] [10624] [INFO] Worker exiting (pid: 10624)
[2021-11-24 18:27:19 +0530] [10622] [INFO] Shutting down: Master
[2021-11-24 18:27:19 +0530] [10622] [INFO] Reason: Worker failed to boot.
```
Can someone help me with this

**Comment by 404-BugNotFound** [comment]
Me too. Have you solved it yet?
my version:
gevent==21.12.0
gunicorn==20.1.0

**Comment by 404-BugNotFound** [comment]
i was fix it when i update wsl 1 to wsl 2

**Comment by zachsiegel-capsida** [comment]
+1

**Comment by scvannost** [comment]
Confirmed that updating to WSL 2 remedies the problem
I had to follow these steps: https://learn.microsoft.com/en-us/windows/wsl/install-manual
