### ISSUE TITLE
Error handling request 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Panlq** [benoitc/gunicorn#2708]
version: 19.9.0
```python traceback
[2022-01-04 10:39:29 +0800] [22] [ERROR] Error handling request /api/param?xxxx=xxx
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 55, in handle
self.handle_request(listener_name, req, client, addr)
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 143, in handle_request
super().handle_request(listener_name, req, sock, addr)
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 113, in handle_request
for item in respiter:
TypeError: 'NoneType' object is not iterable
```
```python
    def handle_request(self, listener_name, req, sock, addr):
            # ......

            respiter = self.wsgi(environ, resp.start_response)
            if self.is_already_handled(respiter):
                return False
            try:
                if isinstance(respiter, environ['wsgi.file_wrapper']):
                    resp.write_file(respiter)
                else:
                    for item in respiter:
                        resp.write(item)
                resp.close()
                request_time = datetime.now() - request_start
                self.log.access(resp, req, environ, request_time)
            # ......
        return True
```
When will respiter return None?

**Comment by jamadden** [comment]
> When will respiter return None?

When the WSGI callable (i.e., your app or middleware that wraps it) returns `None`. That is, it's `respiter` itself that is `None`. This WSGI callable will always produce that error:

```python
def app(environ, start_response):
    start_response('200 OK', [('Content-Type', 'text/plain')])
    return None
```

**Comment by javabrett** [comment]
Would need to see `app` variable or factory and configuration to understand why it is returning `None`.

**Comment by Panlq** [comment]
Thx got it.
