### ISSUE TITLE
Random error made the workers being killed without restarting them

### ISSUE THREAD

**Issue by fernandocamargoai** [benoitc/gunicorn#2736]
Hello, y'all.

I've being using Gunicorn through BentoML to deploy our ML models for almost two year and I've had a very strange error today:

```
[2022-02-01 14:59:28 +0000] [11] [INFO] Unhandled exception in main loop
Traceback (most recent call last):
 File "/opt/conda/lib/python3.8/site-packages/gunicorn/arbiter.py", line 210, in run
 self.murder_workers()
 File "/opt/conda/lib/python3.8/site-packages/gunicorn/arbiter.py", line 495, in murder_workers
 if time.time() - worker.tmp.last_update() <= self.timeout:
 TypeError: attribute name must be string, not 'wrapper_descriptor'
```

After this error, all workers were killed (without restarting) and all the new requests started failing.

So, first, does anyone know what could cause this error? Unfortunately that's all I have from the logs. Second, why weren't my workers restarted? I had cases in which there's a bug in my workers' code and they would be restarted over and over. This time, this strange error seems to have happened outside my workers' code and they were completely killed. Is it possible to make sure they always restart?

**Comment by benoitc** [comment]
How to reproduce it ? I guess your application is trying too modify python functions or something like it;

Though, I will say it again. Don't run tensorflow any intensive backgfround intense cpu task in a web server. Instead run it as a separate service that your http application can query. This will be safer and in the logic of a web application. THat may work with llanguage designed for this though.

**Comment by benoitc** [comment]
no activity since awhile. closing feel free to create a new ticket if needed.
