### ISSUE TITLE
Better Documentation Needed for Threads and umask in Config File

### ISSUE THREAD

**Issue by elibroftw** [benoitc/gunicorn#2750]
It's not clear that when threads is specified, that gunicorn requires `gthread.` Nor does any useful error message pop up. This error message might be due to Python3.10 or it could be due to me using threads without gthread:
```
maste@ubuntu-lenerva:~/projects/lenerva.com$ gunicorn app

Error: class uri 'gunicorn.workers.gthread.ThreadWorker' invalid or not found:

[Traceback (most recent call last):
  File "/home/maste/.local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 40, in <module>
    from asyncio import selectors
ImportError: cannot import name 'selectors' from 'asyncio' (/usr/lib/python3.10/asyncio/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maste/.local/lib/python3.10/site-packages/gunicorn/util.py", line 135, in load_class
    mod = import_module('.'.join(components))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/maste/.local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 42, in <module>
    from gunicorn import selectors
  File "/home/maste/.local/lib/python3.10/site-packages/gunicorn/selectors.py", line 11, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
]
```
`gunicorn.conf.py`
```python
import multiprocessing

workers = multiprocessing.cpu_count() * 2 + 1
threads = 2
bind = ['unix:gunicorn.sock']
preload_app = True
pidfile = 'gunicorn.pid'
daemon = True
app = 'app'

umask = 0o007
```
Furthermore, as you can see above, the umask is `0o007` not `007`. I had to search up why gunicorn couldn't understand '007'. Please add to the documentation on how to use `umask` in a config file. Thanks.

**Comment by CosmoFox** [comment]
Will be docs updated?
