### ISSUE TITLE
Error: class uri 'eventlet' invalid or not found: 

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [benoitc/gunicorn#2774]
```
2022-04-06T00:17:18.112082+00:00 app[web.1]: Error: class uri 'eventlet' invalid or not found: 
2022-04-06T00:17:18.112082+00:00 app[web.1]: 
2022-04-06T00:17:18.112082+00:00 app[web.1]: [Traceback (most recent call last):
2022-04-06T00:17:18.112090+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/util.py", line 99, in load_class
2022-04-06T00:17:18.112091+00:00 app[web.1]:     mod = importlib.import_module('.'.join(components))
2022-04-06T00:17:18.112091+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
2022-04-06T00:17:18.112092+00:00 app[web.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2022-04-06T00:17:18.112092+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2022-04-06T00:17:18.112092+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2022-04-06T00:17:18.112093+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2022-04-06T00:17:18.112093+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2022-04-06T00:17:18.112093+00:00 app[web.1]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2022-04-06T00:17:18.112093+00:00 app[web.1]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2022-04-06T00:17:18.112094+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/workers/geventlet.py", line 20, in <module>
2022-04-06T00:17:18.112094+00:00 app[web.1]:     from eventlet.wsgi import ALREADY_HANDLED as EVENTLET_ALREADY_HANDLED
2022-04-06T00:17:18.112095+00:00 app[web.1]: ImportError: cannot import name 'ALREADY_HANDLED' from 'eventlet.wsgi' (/app/.heroku/python/lib/python3.10/site-packages/eventlet/wsgi.py)
2022-04-06T00:17:18.112095+00:00 app[web.1]: ]
```

**Comment by nickwest** [comment]
This is fixed in a merged pull request #2581 

You can find a workaround in the comments in there, but there are security concerns in leveraging that workaround now. We're all waiting on a new release, there hasn't been one for over a year now...
