### ISSUE TITLE
Gevent exception Greenlet Exit

### ISSUE THREAD

**Issue by amroghoneim** [benoitc/gunicorn#2787]
Hello.

I am currently facing this issue when receiving a post request in my web app with this exception popping up

```
Traceback (most recent call last):
  File "/app/api/app.py", line 61, in ocr
    data = json.loads(request.data)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/utils.py", line 107, in __get__
    value = self.fget(obj)  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/werkzeug/wrappers/request.py", line 354, in data
    return self.get_data(parse_form_data=True)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/wrappers/request.py", line 405, in get_data
    rv = self.stream.read()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/http/body.py", line 215, in read
    data = self.reader.read(1024)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/http/body.py", line 130, in read
    data = self.unreader.read()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
  File "/usr/local/lib/python3.7/site-packages/gevent/_socketcommon.py", line 663, in recv
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 304, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
greenlet.GreenletExit
```

gunicorn command used
```
gunicorn wsgi:app --bind  0.0.0.0:443 --log-level=info --worker-tmp-dir /dev/shm --workers=4 --worker-class gevent --max-requests 10 --reload --timeout 300 --graceful-timeout 300 --log-file=-
```

I run the app on a docker container on an Azure container instance with GPU support running pytorch models.

What exactly is the issue here?

**Comment by rahozin-ivan** [comment]
Hello @amroghoneim, how you solved this issue?

**Comment by amroghoneim** [comment]
@rahozin-ivan 
Hey sorry just saw this. I wouldn't say I solved it. I changed the worker to gevent-pywsgi which I believe just changes the parsing nothing more and this stopped popping up. Let me know if you reached a conclusion regarding this as well.
