### ISSUE TITLE
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'> #2667 

### ISSUE THREAD

**Issue by InfernalAzazel** [benoitc/gunicorn#2816]
error:

2022-06-20 08:06:06 +0800] [7] [WARNING] Worker with pid 2855 was terminated due to signal 6
[2022-06-20 08:06:06 +0800] [2864] [INFO] Booting worker with pid: 2864
[2022-06-20 08:06:06 +0800] [7] [WARNING] Worker with pid 2856 was terminated due to signal 6
[2022-06-20 08:06:06 +0800] [7] [WARNING] Worker with pid 2861 was terminated due to signal 6
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
    self.log.warning(
  File "/usr/local/lib/python3.10/site-packages/gunicorn/glogging.py", line 261, in warning
    self.error_log.warning(msg, *args, **kwargs)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1489, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1108, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1021, in handleError
    sys.stderr.write('--- Logging error ---\n')
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>
Call stack:
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 211, in run
    self.manage_workers()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 623, in spawn_workers
    time.sleep(0.1 * random.random())
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
    self.log.warning(
  File "/usr/local/lib/python3.10/site-packages/gunicorn/glogging.py", line 261, in warning
    self.error_log.warning(msg, *args, **kwargs)
Message: 'Worker with pid %s was terminated due to signal %s'
Arguments: (2861, 6)

**Comment by bengabp** [comment]
after 2 years , this issue hasnt been fixed and now im getting thesame error

**Comment by DmitriyLyalyuev** [comment]
The same here. :(

**Comment by randomir** [comment]
Regression of https://github.com/benoitc/gunicorn/issues/2564.

**Comment by ChanChiChoi** [comment]
the same here，too

**Comment by zevlg** [comment]
Same for me, causing bad things in production, such as master process hang up while restarting service.  To workaround it, I've changed `loglevel = 'error'` to `loglevel = 'critical'` in app config.

Why not just stop writing logs in SIGCHLD handler?

**Comment by fumiyas** [comment]
Fixed by #3441? (Gunicorn 24.1.0 or newer)

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — this one looks like it was addressed by the arbiter signal-handling refactor in 24.1.0.

Evidence:
- PR [#3441](https://github.com/benoitc/gunicorn/pull/3441) "Arbiter signal handling improvements" (merged 2026-01-22, released in [24.1.0](https://github.com/benoitc/gunicorn/releases/tag/24.1.0) on 2026-01-23) explicitly removes logging from signal context and replaces the PIPE+select machinery with `queue.SimpleQueue`, exactly the class of fix this report needed.
- On the 24.1.0 tag, [`gunicorn/arbiter.py` lines 233-238](https://github.com/benoitc/gunicorn/blob/24.1.0/gunicorn/arbiter.py#L233-L238) show the SIGCHLD handler now reads:
  ```python
  def signal_chld(self, sig, frame):
      """SIGCHLD signal handler - NO LOGGING, just queue the signal."""
      self.SIG_QUEUE.put_nowait(sig)
  ```
  Logging was moved to `handle_chld()` which is invoked from the main loop, so the reentrant-write into `<stderr>` reported here can no longer happen.
- The earlier PR [#2667](https://github.com/benoitc/gunicorn/pull/2667) (which this issue cross-references) was closed in favour of the larger #3441 refactor that actually shipped.

If anyone is still seeing this on >= 24.1.0 it would be worth opening a fresh issue with a reproducer against current main, but the original premise looks resolved. Otherwise would you mind closing this out?

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the file/line and PR references above were verified manually against the 24.1.0 tag.*
