### ISSUE TITLE
Gunicorn fails to launch

### ISSUE THREAD

**Issue by Sharkitty** [benoitc/gunicorn#2886]
Hello! I'm having problems running gunicorn for my zou development environment [(zou documentation).](https://zou.cg-wire.com/development/) I'm getting an OSError stating Protocol not available as shown below.  I'm running gunicorn from WSL as I'm using windows. If anyone can help I would appreciate it :)

```
gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -b 127.0.0.1:5001 -w 1 zou.event_stream:app
[2022-10-27 14:53:26 +0200] [1687] [INFO] Starting gunicorn 20.1.0
[2022-10-27 14:53:26 +0200] [1687] [INFO] Listening at: http://127.0.0.1:5001 (1687)
[2022-10-27 14:53:26 +0200] [1687] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2022-10-27 14:53:26 +0200] [1689] [INFO] Booting worker with pid: 1689
[2022-10-27 14:53:26 +0200] [1689] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/mnt/e/Normaal/Kitsu/zou/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/mnt/e/Normaal/Kitsu/zou/.venv/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 144, in init_process
    self.patch()
  File "/mnt/e/Normaal/Kitsu/zou/.venv/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 43, in patch
    sockets.append(socket.socket(s.FAMILY, socket.SOCK_STREAM,
  File "/mnt/e/Normaal/Kitsu/zou/.venv/lib/python3.8/site-packages/gevent/_socket3.py", line 133, in __init__
    self._sock = self._gevent_sock_class(family, type, proto, fileno)
OSError: [Errno 92] Protocol not available
[2022-10-27 14:53:26 +0200] [1689] [INFO] Worker exiting (pid: 1689)
[2022-10-27 14:53:26 +0200] [1687] [INFO] Shutting down: Master
[2022-10-27 14:53:26 +0200] [1687] [INFO] Reason: Worker failed to boot.
```

**Comment by Sharkitty** [comment]
Fixed by switching from WSL1 to WSL2
