### ISSUE TITLE
Gunicorn errors when using background process

### ISSUE THREAD

**Issue by BenjaminPelletier** [benoitc/gunicorn#2919]
Simply attempting to run a background process with Gunicorn 20.1.0 + Flask 2.2.2 results in a number of errors.  To reproduce, add the following two files to a folder named `missing_config`:

`__init__.py`:
```python
import flask


webapp = flask.Flask(__name__)


@webapp.route('/', methods=['GET'])
def index():
    return 'Hello world', 200
```

`gunicorn.conf.py`:
```python
from multiprocessing import Process


def _background():
    print("Hello from background process")


def on_starting(server):
    """gunicorn server hook called just before master process is initialized."""
    print('on_starting')

    p = Process(target=_background)
    p.start()
```

Then, start the web server from the `missing_config` folder with:
```bash
gunicorn --preload --pythonpath=$(pwd)/.. --config=./gunicorn.conf.py --workers=2 --bind=0.0.0.0:5000 missing_config:webapp
```

I expect that this should work fine and I should see `Hello from background process` printed in the terminal.  Instead, I see this error message:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/pelletierb/.pyenv/versions/3.8.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/pelletierb/.pyenv/versions/3.8.8/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
ModuleNotFoundError: No module named '__config__'
```

And, when I press ctrl-c to stop the server, I get the following error messages:

```
^C[2023-01-16 17:41:24 -0800] [94802] [INFO] Handling signal: int
[2023-01-16 17:41:24 -0800] [94806] [INFO] Worker exiting (pid: 94806)
[2023-01-16 17:41:24 -0800] [94807] [INFO] Worker exiting (pid: 94807)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
Error in atexit._run_exitfuncs:
  File "/Users/pelletierb/.pyenv/versions/3.8.8/lib/python3.8/multiprocessing/util.py", line 357, in _exit_function
Traceback (most recent call last):
  File "/Users/pelletierb/.pyenv/versions/3.8.8/lib/python3.8/multiprocessing/util.py", line 357, in _exit_function
    p.join()
    p.join()
  File "/Users/pelletierb/.pyenv/versions/3.8.8/lib/python3.8/multiprocessing/process.py", line 147, in join
  File "/Users/pelletierb/.pyenv/versions/3.8.8/lib/python3.8/multiprocessing/process.py", line 147, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
AssertionError: can only join a child process
```

**Comment by vincent-grosbois** [comment]
The second one is a small bug in gunicorn where worker processes will, on exit, try to also kill the process id that you spawned in the main process. But since it's not possible, you get this error message. There is a way to remove this but it doesn't really change your program behavior, it's just ignored.

**Comment by BenjaminPelletier** [comment]
Being able to differentiate between the true error messages and false error messages would be very useful; what is the way to remove this behavior (so that I don't get the second error messages)?

**Comment by vincent-grosbois** [comment]
I just applied this : https://github.com/benoitc/gunicorn/issues/1391#issuecomment-467010209
basically you can force the child processes to not handle the clean-up of processes they are linked to on exit, which is incorrect in that case

**Comment by benoitc** [comment]
> The second one is a small bug in gunicorn where worker processes will, on exit, try to also kill the process id that you spawned in the main process. But since it's not possible, you get this error message. There is a way to remove this but it doesn't really change your program behavior, it's just ignored.

That not a bug but rather per design. Imo processes shouldn't be launched directly from a worker process. Workers processes are supposed to be managed by the arbiter.  I would suggest rather to launch a main process with a unix socket to reuse across worker. Then pass to this process any order to start a new process.

**Comment by BenjaminPelletier** [comment]
> Imo processes shouldn't be launched directly from a worker process.

They aren't in this example, right?  The only time a process is launched outside gunicorn's internals is in the `on_starting` server hook that is "Called just before the master process is initialized."  Is this call (which happens before the master process is initialized, which is what I would have previously assumed controls worker processes) from a worker process?

> I would suggest rather to launch a main process with a unix socket to reuse across worker. Then pass to this process any order to start a new process.

I'm not sure I follow; I just want to start a background process when the server starts up.  What's the right way to do that?  Are you suggesting the background process be in an entirely separate application and to use sockets for interprocess communication?

**Comment by benoitc** [comment]
no activity since awhile. closing feel free to create a new ticket if needed.

**Comment by BenjaminPelletier** [comment]
There was no activity awaiting the answers to [4 questions](https://github.com/benoitc/gunicorn/issues/2919#issuecomment-1405725383):

1. [Processes] aren't [launched from a worker process] in this example, right?  (in reference to "Imo processes shouldn't be launched directly from a worker process.")
2. Is [the call from on_starting] (which happens before the master process is initialized, which is what I would have previously assumed controls worker processes) from a worker process?
3. I just want to start a background process when the server starts up. What's the right way to do that?
4. Are you suggesting the background process be in an entirely separate application and to use sockets for interprocess communication?

This issue is not completed.

**Comment by georgipopovhs** [comment]
Alright, I also hit these two errors when trying to start a background process (for the purpose of monitoring gunicorn busy workers and backlog).

The reason for `ModuleNotFoundError: No module named '__config__'` comes from gunicorn loading its config file as a python module named `__config__`. The exact mechanism is that when using `multiprocessing` with a [start method](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.set_start_method) different from `fork` (e.g. on MacOS the default is `spawn`), everything passed to the background process needs to be pickled, like `target` function and `args`. Then during unpickling, the module where `target` is defined needs to be loaded in the new process, however it isn't aware of any module named `__config__`, as this is a fictious name set by the master process. See config loading logic in https://github.com/benoitc/gunicorn/blob/a86ea1e4e6c271d1cd1823c7e14490123f9238fe/gunicorn/app/base.py#L100

My workaround was to create another file under [pythonpath](https://docs.gunicorn.org/en/stable/settings.html#pythonpath) and define a subclass of Process (or you could define the `target` function there) and import it in the gunicorn config file to use when starting the background process.

another_file.py
```python
import multiprocessing

class MyProcess(multiprocessing.Process):
    def run(self):
        print('hi!')
```
gunicorn_config.py
```python
import multiprocessing
from another_file import MyProcess

def when_ready(server):
    multiprocessing.set_start_method('spawn')
    MyProcess(daemon=True).start()
```
