### ISSUE TITLE
wsgi.errors implements RawIOBase but fails when given bytes

### ISSUE THREAD

**Issue by bipface** [benoitc/gunicorn#2921]
The `environ['wsgi.errors']` object (`WSGIErrorsWrapper`) subclasses `io.RawIOBase`, however passing bytes to `environ['wsgi.errors'].write` raises an error (`TypeError: write() argument must be str, not bytes`).

According to [the RawIOBase docs](https://docs.python.org/3.10/library/io.html?highlight=textio#io.RawIOBase), write should accept a bytes-like object:
> `write(b, /)` - Write the given bytes-like object, *b*, to the underlying raw stream, and return the number of bytes written

Also note that `WSGIErrorsWrapper.write` doesn't return the number of bytes (or characters) written.

Also note that according to [the WSGI specification](https://peps.python.org/pep-3333/#input-and-error-streams) the signature for `environ['wsgi.errors'].write` should be `write(str)`, so it may be more correct for `WSGIErrorsWrapper` to subclass `io.TextIOBase` instead.

Tested using Gunicorn 20.1.0 on Python 3.10.6

example.py:
```py
import io
def wsgi_app(environ, start_response):
        assert isinstance(environ['wsgi.errors'], io.RawIOBase)
        environ['wsgi.errors'].write(b'foo')

        start_response('200 OK', [])
        return ()
```

launch and test:
```sh
python3 -m gunicorn example:wsgi_app
curl 'http://localhost:8000'
```

result:
```
[2023-01-19 12:54:42 +1100] [20495] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python3/dist-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/replictags/example.py", line 4, in wsgi_app
    environ['wsgi.errors'].write(b'foo')
  File "/usr/lib/python3/dist-packages/gunicorn/http/wsgi.py", line 62, in write
    stream.write(data)
TypeError: write() argument must be str, not bytes
```

**Comment by benoitc** [comment]
Closing due to lack of activity. If you have a fix for this compatibility issue, please submit a PR.
