### ISSUE TITLE
Problems with using systemd to run Flask app with Gunicorn in Docker

### ISSUE THREAD

**Issue by jackylu0124** [benoitc/gunicorn#2962]
I have been having the `ModuleNotFoundError: No module named` error when I try to use `systemd` to run Gunicorn in Docker when the machine starts. I have verified that I can run Gunicorn in Docker with the same command plus the `-it` flag with no issues, and this issue only happens when `systemd`'s service is used to run Docker which in turn runs Gunicorn. This made me wonder if there are any special "launch sequence" or packages that are required by Gunicorn when the machine first starts. I have pasted my `systemd` service file below for reference as well as the stack trace of this failed `systemd` service when the machine first starts. I have also tried everything people suggested online, including Gunicorn's `--chdir` and `--pythonpath`, as well as Docker's `-w`, but none of them solves the issue. What's interesting is that the Docker container runs perfectly with no issues at all, and it only becomes problematic when it's used with `systemd`. I have seen posts on issues when using `systemd + Gunicorn` and posts on issues when using `Docker+ Gunicorn`, but no posts on using all three (`systemd + Docker + Gunicorn`) together online so far. I would really apprciate any insight or help on this. Thanks a lot in advance!

My project folder structure looks like the following:
`server_v0`
---- `frontend`
-------- `frontend`
------------ `frontend_server_v001.py` (a Flask app)

\
My `frontend_server_v001.py` file is very simple and looks like the following:

```
from flask import Flask, request, send_file

app = Flask(__name__)

@app.route("/")
def index():
    return "This is the index page."

@app.route("/api/dev", methods=["POST"])
def api_dev():
    if request.method == "POST":
        # Extract data
        # Some additional code
```

\
My systemd's service file name: **frontend.service**
(note that `docker-network-create.service` in the configuration below is a service for creating a Docker network called `my_network` in order to communicate with other Docker containers)
```
[Unit]
Description=Server's Flask frontend
After=network.target docker.service docker-network-create.service
Requires=docker.service

[Service]
User=ubuntu
Group=www-data
WorkingDirectory=/home/ubuntu/server_v0/frontend
ExecStart=/usr/bin/docker run \
--gpus=all --rm --name=my_frontend \
--network=my_network -p5000:5000 \
-v ${PWD}/frontend:/frontend --shm-size="2g" frontend_v0 \
gunicorn --chdir /frontend -b 0.0.0.0:5000 --workers=5 frontend_server_v001:app
Restart=always

[Install]
WantedBy=multi-user.target
```

\
The error stack trace that I obtained with the command `journalctl -u frontend.service -b --no-pager`:
```
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]: [2023-03-29 02:49:48 +0000] [1] [INFO] Starting gunicorn 20.1.0
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]: [2023-03-29 02:49:48 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]: [2023-03-29 02:49:48 +0000] [1] [INFO] Using worker: sync
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]: [2023-03-29 02:49:48 +0000] [8] [INFO] Booting worker with pid: 8
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]: [2023-03-29 02:49:48 +0000] [8] [ERROR] Exception in worker process
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]: Traceback (most recent call last):
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:     worker.init_process()
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:     self.load_wsgi()
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:     self.wsgi = self.app.wsgi()
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:     self.callable = self.load()
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:     return self.load_wsgiapp()
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:     return util.import_app(self.app_uri)
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:   File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:     mod = importlib.import_module(module)
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:     return _bootstrap._gcd_import(name[level:], package, level)
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]:   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]: ModuleNotFoundError: No module named 'frontend_server_v001'
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]: [2023-03-29 02:49:48 +0000] [8] [INFO] Worker exiting (pid: 8)
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]: [2023-03-29 02:49:48 +0000] [1] [INFO] Shutting down: Master
Mar 29 02:49:48 ip-XXX-XX-XX-XX docker[57122]: [2023-03-29 02:49:48 +0000] [1] [INFO] Reason: Worker failed to boot.
Mar 29 02:49:49 ip-XXX-XX-XX-XX systemd[1]: frontend.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Mar 29 02:49:49 ip-XXX-XX-XX-XX systemd[1]: frontend.service: Failed with result 'exit-code'.
Mar 29 02:49:49 ip-XXX-XX-XX-XX systemd[1]: frontend.service: Scheduled restart job, restart counter is at 87.
Mar 29 02:49:49 ip-XXX-XX-XX-XX systemd[1]: Stopped Server's Flask frontend.
Mar 29 02:49:49 ip-XXX-XX-XX-XX systemd[1]: Started Server's Flask frontend.
```

**Comment by benoitc** [comment]
You can set the python_path to point to the correct path. Make sure the process in docker knows where to find the volume.
