### ISSUE TITLE
incorrect handling of SCRIPT_NAME

### ISSUE THREAD

**Issue by mastier** [benoitc/gunicorn#2969]
/As in title

This part should not fail if you have script name for instance = '/admin' 
 and you call the 'root'  like http://domain.example/
 ```
      path_info = req.path                                                                            
      if script_name:                                                                                 
          path_info = path_info.split(script_name, 1)[1]                                              
      environ['PATH_INFO'] = util.unquote_to_wsgi_str(path_info)                                      
      environ['SCRIPT_NAME'] = script_name                                                            
 ```
 This should give 404 Not found not 500 Internal server error
 
```
headscale-webui | [2023-04-16 19:20:33 +0200] [1] [INFO] Starting gunicorn 20.1.0
headscale-webui | [2023-04-16 19:20:33 +0200] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
headscale-webui | [2023-04-16 19:20:33 +0200] [1] [INFO] Using worker: sync
headscale-webui | [2023-04-16 19:20:33 +0200] [8] [INFO] Booting worker with pid: 8
headscale-webui | [2023-04-16 19:20:34,257] INFO in server: Headscale-WebUI Version:  v0.6.1 / main
headscale-webui | [2023-04-16 19:20:34,257] INFO in server: LOG LEVEL SET TO INFO
headscale-webui | [2023-04-16 19:20:34,257] INFO in server: DEBUG STATE:  False
headscale-webui | [2023-04-16 19:20:34,258] INFO in server: Loading basic auth libraries and configuring app...
headscale-webui | [2023-04-16 19:20:35 +0200] [8] [ERROR] Error handling request /
headscale-webui | Traceback (most recent call last):
headscale-webui |   File "/app/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 136, in handle
headscale-webui |     self.handle_request(listener, req, client, addr)
headscale-webui |   File "/app/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 169, in handle_request
headscale-webui |     resp, environ = wsgi.create(req, client, addr,
headscale-webui |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
headscale-webui |   File "/app/.venv/lib/python3.11/site-packages/gunicorn/http/wsgi.py", line 183, in create
headscale-webui |     path_info = path_info.split(script_name, 1)[1]
headscale-webui |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
headscale-webui | IndexError: list index out of range
headscale-webui | [2023-04-16 19:20:35 +0200] [8] [ERROR] Error handling request /favicon.ico
headscale-webui | Traceback (most recent call last):
headscale-webui |   File "/app/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 136, in handle
headscale-webui |     self.handle_request(listener, req, client, addr)
headscale-webui |   File "/app/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 169, in handle_request
headscale-webui |     resp, environ = wsgi.create(req, client, addr,
headscale-webui |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
headscale-webui |   File "/app/.venv/lib/python3.11/site-packages/gunicorn/http/wsgi.py", line 183, in create
headscale-webui |     path_info = path_info.split(script_name, 1)[1]
headscale-webui |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
headscale-webui | IndexError: list index out of range
```

**Comment by lel-amri** [comment]
Related to #226

**Comment by tilgovi** [comment]
I don't think we are likely to change this. If you define a script name, then all requests should start with that path.
