### ISSUE TITLE
filedescriptor out of range in select() exception received

### ISSUE THREAD

**Issue by pchaseh** [benoitc/gunicorn#2994]
Hi,

We use gunicorn along with uvicorn to run an API server. Today, during a restart of our application, it did not come up successfully, instead failing with the following:

```
Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/usr/src/app/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: filedescriptor out of range in select()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/xdp_synproxy_py/api.py", line 409, in run_api
    StandaloneApplication("xdp_synproxy_py.api:app", options).run()
  File "/usr/src/app/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/src/app/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 238, in run
    sys.exit(-1)
SystemExit: -1
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 91 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 114 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 90 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 92 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 108 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 89 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 103 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 110 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 82 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 106 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 86 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 100 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 84 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 124 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 126 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 102 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 117 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 111 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 79 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 96 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 105 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 80 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 116 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 115 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 83 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 119 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 121 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 113 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 78 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 118 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 123 was terminated due to signal 9
[2023-05-12 17:39:30 +0000] [76] [WARNING] Worker with pid 122 was terminated due to signal 9
[ERROR] api:
```

Looking at the source code of [arbiter.py](https://github.com/benoitc/gunicorn/blob/master/gunicorn/arbiter.py#L360) and referenced exception trace, I can see that the call to `select` is failing. Searching on the Internet reveals that this system call does not support file descriptor numbers greater than `FD_SETSIZE`. From https://man7.org/linux/man-pages/man2/select.2.html:
> WARNING: select() can monitor only file descriptors numbers that
       are less than FD_SETSIZE (1024)—an unreasonably low limit for
       many modern applications—and this limitation will not change.
       All modern applications should instead use [poll(2)](https://man7.org/linux/man-pages/man2/poll.2.html) or [epoll(7)](https://man7.org/linux/man-pages/man7/epoll.7.html),
       which do not suffer this limitation.

Interestingly enough, after a restart of the application it is working fine despite the gunicorn workers referencing the FD number 1025, whereas `FD_SETSIZE` is in fact 1024 on the machine: 
```bash
$ sudo ss -tnlp | grep 8091
LISTEN 0      2048               127.0.0.1:8091       0.0.0.0:*    users:(("gunicorn: worke",pid=3610946,fd=1025),("gunicorn: worke",pid=3610944,fd=1025),("gunicorn: worke",pid=3610943,fd=1025),("gunicorn: worke",pid=3610942,fd=1025),("gunicorn: worke",pid=3610941,fd=1025),("gunicorn: worke",pid=3610940,fd=1025),("gunicorn: worke",pid=3610939,fd=1025),("gunicorn: worke",pid=3610938,fd=1025),("gunicorn: worke",pid=3610937,fd=1025),("gunicorn: worke",pid=3610936,fd=1025),("gunicorn: worke",pid=3610935,fd=1025),("gunicorn: worke",pid=3610934,fd=1025),("gunicorn: worke",pid=3610933,fd=1025),("gunicorn: worke",pid=3610931,fd=1025),("gunicorn: worke",pid=3610930,fd=1025),("gunicorn: worke",pid=3610929,fd=1025),("gunicorn: worke",pid=3610928,fd=1025),("gunicorn: worke",pid=3610927,fd=1025),("gunicorn: worke",pid=3610923,fd=1025),("gunicorn: worke",pid=3610922,fd=1025),("gunicorn: worke",pid=3610921,fd=1025),("gunicorn: worke",pid=3610920,fd=1025),("gunicorn: worke",pid=3610917,fd=1025),("gunicorn: worke",pid=3610916,fd=1025),("gunicorn: worke",pid=3610915,fd=1025),("gunicorn: worke",pid=3610912,fd=1025),("gunicorn: worke",pid=3610911,fd=1025),("gunicorn: worke",pid=3610909,fd=1025),("gunicorn: worke",pid=3610908,fd=1025),("gunicorn: worke",pid=3610907,fd=1025),("gunicorn: worke",pid=3610906,fd=1025),("gunicorn: worke",pid=3610905,fd=1025),("gunicorn: maste",pid=3610903,fd=1025))
```

```bash
$ grep FD_SETSIZE /usr/include/x86_64-linux-gnu/bits/typesizes.h
#define __FD_SETSIZE            1024
````

Would it be wiser to switch to using `poll` to avoid this? According to https://docs.python.org/3/library/select.html, `poll` also scales better and is more suitable for network servers.

**Comment by benoitc** [comment]
we don't need to scale there, ,,,,,,this behaviour is odd though. Why more than 1024 FD there?

**Comment by kzemek** [comment]
We run Gunicorn programatically as per https://docs.gunicorn.org/en/stable/custom.html and have plenty of FDs open before the API starts (and the API has to have access to these FDs, so closing them is not a scalable option).

**Comment by benoitc** [comment]
Fixed in commit b650332c (Arbiter signal handling improvements #3441). The arbiter no longer uses `select()` which had the FD_SETSIZE limit. It now uses `queue.SimpleQueue()` which has no such limitation.
