### ISSUE TITLE
Gunicorn is not find while deploying django project to railway in windows.

### ISSUE THREAD

**Issue by adikesavulu-15** [benoitc/gunicorn#3018]
i intsalled alll packages but still getting error like 

﻿/bin/bash: line 1: gunicorn: command not found

and in django terminal i run the version of gunicorn it displays error like this 

(venv) C:\Users\madi9\Documents\fan\fancardpro1>gunicorn --version
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\madi9\Documents\fan\fancardpro1\venv\Scripts\gunicorn.exe\__main__.py", line 4, in <module>
  File "C:\Users\madi9\Documents\fan\fancardpro1\venv\Lib\site-packages\gunicorn\app\wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "C:\Users\madi9\Documents\fan\fancardpro1\venv\Lib\site-packages\gunicorn\app\base.py", line 11, in <module>
    from gunicorn import util
  File "C:\Users\madi9\Documents\fan\fancardpro1\venv\Lib\site-packages\gunicorn\util.py", line 8, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

i reinstall the gunicorn but same error came for me.

python-3.11.1
Django==4.2.2
gunicorn 20.1.0

please help me on this.

**Comment by benoitc** [comment]
gunicorn doesn't run natively on windows. I'm not using myself windows so it's a low priority for now. You can run it in any unix/linux env however, including shell on windows.
