### ISSUE TITLE
OSError   gunicorn.util in write Bad file descriptor guincorn v 21.0.1

### ISSUE THREAD

**Issue by revanthmahesh** [benoitc/gunicorn#3025]
```[2023-07-18 07:43:52 +0000] [75] [ERROR] Socket error processing request.

 Traceback (most recent call last):

   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/gthread.py", line 282, in handle

     keepalive = self.handle_request(req, conn)

   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/gthread.py", line 354, in handle_request

     util.reraise(*sys.exc_info())

   File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 641, in reraise

     raise value

   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/gthread.py", line 340, in handle_request

     resp.write(item)

   File "/usr/local/lib/python3.8/dist-packages/gunicorn/http/wsgi.py", line 326, in write

     self.send_headers()

   File "/usr/local/lib/python3.8/dist-packages/gunicorn/http/wsgi.py", line 322, in send_headers

     util.write(self.sock, util.to_bytestring(header_str, "latin-1"))

   File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 299, in write

     sock.sendall(data)

 OSError: [Errno 9] Bad file descriptor
 ```
 
 This happening with latest gunicorn release, using previous versions is working fine

**Comment by benoitc** [comment]
@revanthmahesh how to reproduce it?

**Comment by SaravEasy** [comment]
We got the same issue today in Production and have reduced the version back to 20.1.0 to fix things.

**Comment by benoitc** [comment]
@SaravEasy I doin't reproduce it. Can you provide more info on how to reproduce it or in which context?

**Comment by SaravEasy** [comment]
@benoitc, let me try to reproduce this issue in a local environment and share more information shortly.

**Comment by SaravEasy** [comment]
Environment Details
---------------------

Python Version : 3.6
OS architecture: AMD64
Flask: 0.12.1
Werkzeug: 0.12.1

Our API server started throwing the following exceptions intermittently and we noticed this issue and we reduced the version and it worked.

We did not take the open socket or file descriptors at that time or could not find the pattern.  

Hope this helps you get started in the right direction. @benoitc 


Stack Trace - Error
------------------------

[2023-07-18 13:59:48 +0000] [18681] [ERROR] Exception in worker process
[2023-07-18 13:59:48 +0000] [18681] [INFO] Worker exiting (pid: 18681)
ValueError: Invalid file descriptor: -1
raise ValueError("Invalid file descriptor: {}".format(fd))
File "/usr/local/lib/python3.6/selectors.py", line 41, in _fileobj_to_fd
return _fileobj_to_fd(fileobj)
File "/usr/local/lib/python3.6/selectors.py", line 224, in _fileobj_lookup
key = self._fd_to_key.pop(self._fileobj_lookup(fileobj))
File "/usr/local/lib/python3.6/selectors.py", line 248, in unregister
key = super().unregister(fileobj)
File "/usr/local/lib/python3.6/selectors.py", line 419, in unregister
self.poller.unregister(conn.sock)
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 176, in murder_keepalived
self.murder_keepalived()
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 232, in run
self.run()
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 142, in init_process
super().init_process()
File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
worker.init_process()
File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
Traceback (most recent call last):
[2023-07-18 13:59:49 +0000] [16] [ERROR] Worker (pid:18681) exited with code 255.
[2023-07-18 13:59:49 +0000] [16] [ERROR] Worker (pid:18681) exited with code 255

**Comment by benoitc** [comment]
Please test https://github.com/benoitc/gunicorn/pull/3033 and let me know how it behaves after it.

**Comment by revanthmahesh** [comment]
Tested using the script below in docker with os 

FROM ubuntu:20.04

RUN pip install git+https://github.com/benoitc/gunicorn.git@fix-gthread

Issue is fixed now @benoitc

**Comment by ahmetkurukose** [comment]
I also tested the fix-gthread branch with the Python 3.11 Debian Docker image, and I did not encounter any errors @benoitc

**Comment by jgehrcke** [comment]
Thank you @benoitc -- this also affected us.

**Comment by benoitc** [comment]
change applied in master. Thaks for the feedback!
