### ISSUE TITLE
gunicorn 21.1.0: `class uri 'eventlet' invalid or not found` and `ModuleNotFoundError: No module named 'cryptography'`

### ISSUE THREAD

**Issue by fabswt** [benoitc/gunicorn#3034]
gunicorn 21.1.0 crashes with these errors:

```
class uri 'eventlet' invalid or not found […] RuntimeError: eventlet worker requires eventlet 0.24.1 or higher
ModuleNotFoundError: No module named 'cryptography'
```

requirements.txt, with gunicorn 21.1.0 and eventlet 0.33.3:

```
gunicorn==21.1.0
azure-cognitiveservices-speech==1.28.0
bcrypt==4.0.1
boto3==1.26.142
botocore==1.29.142
deepl==1.14.0
eventlet==0.33.3
Flask==2.3.2
Flask_Cors==3.0.10
Flask_Login==0.6.2
Flask-Session==0.5.0
Flask_SocketIO==5.3.4
Flask_SQLAlchemy==2.5.1
Jinja2==3.1.2
Markdown==3.4.3
openai==0.27.8
psycopg2-binary==2.9.6
pydub==0.25.1
python-dotenv==0.21.1
pytz==2022.6
requests==2.31.0
SQLAlchemy==1.4.44
sqlalchemy_citext==1.8.0
stripe==5.4.0
Werkzeug==2.3.4
langcodes==3.3.0
language-data==1.1
emoji==2.4.0
pyyaml==6.0
email-validator==1.3.1
tenacity==8.2.2
html2text==2020.1.16
requests-toolbelt==1.0.0
```

Here is the build log from Heroku that shows eventlet==0.33.3 is being installed:

```
-----> Building on the Heroku-22 stack
-----> Using buildpacks:
       1. heroku-community/apt
       2. https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git
       3. heroku/python
-----> Apt app detected
-----> Reusing cache
-----> Updating apt caches
       Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
       Get:2 http://archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
       Hit:3 http://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease
       Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
       Fetched 229 kB in 1s (334 kB/s)
       Reading package lists...
W: http://apt.postgresql.org/pub/repos/apt/dists/jammy-pgdg/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
-----> Fetching http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
-----> Installing libssl1.1_1.1.1f-1ubuntu2_amd64.deb
-----> Writing profile script
-----> Rewrite package-config files
-----> ffmpeg app detected
-----> Installing ffmpeg
       Variable FFMPEG_DOWNLOAD_URL isn't set, using default value
       Downloading https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
       Unpacking the archive
       Installation successful
-----> Python app detected
-----> Using Python version specified in runtime.txt
 !     
 !     A Python security update is available! Upgrade as soon as possible to: python-3.11.4
 !     See: https://devcenter.heroku.com/articles/python-runtimes
 !     
-----> Requirements file has been changed, clearing cached dependencies
-----> Installing python-3.11.3
-----> Installing pip 23.1.2, setuptools 67.8.0 and wheel 0.40.0
-----> Installing SQLite3
-----> Installing requirements with pip
       Collecting gunicorn==21.1.0 (from -r requirements.txt (line 1))
         Downloading gunicorn-21.1.0-py3-none-any.whl (80 kB)
       Collecting azure-cognitiveservices-speech==1.28.0 (from -r requirements.txt (line 2))
         Downloading azure_cognitiveservices_speech-1.28.0-py3-none-manylinux1_x86_64.whl (3.1 MB)
       Collecting bcrypt==4.0.1 (from -r requirements.txt (line 3))
         Downloading bcrypt-4.0.1-cp36-abi3-manylinux_2_28_x86_64.whl (593 kB)
       Collecting boto3==1.26.142 (from -r requirements.txt (line 4))
         Downloading boto3-1.26.142-py3-none-any.whl (135 kB)
       Collecting botocore==1.29.142 (from -r requirements.txt (line 5))
         Downloading botocore-1.29.142-py3-none-any.whl (10.8 MB)
       Collecting deepl==1.14.0 (from -r requirements.txt (line 6))
         Downloading deepl-1.14.0-py3-none-any.whl (39 kB)
       Collecting eventlet==0.33.3 (from -r requirements.txt (line 7))
         Downloading eventlet-0.33.3-py2.py3-none-any.whl (226 kB)
       Collecting Flask==2.3.2 (from -r requirements.txt (line 8))
         Downloading Flask-2.3.2-py3-none-any.whl (96 kB)
       Collecting Flask_Cors==3.0.10 (from -r requirements.txt (line 9))
         Downloading Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
       Collecting Flask_Login==0.6.2 (from -r requirements.txt (line 10))
         Downloading Flask_Login-0.6.2-py3-none-any.whl (17 kB)
       Collecting Flask-Session==0.5.0 (from -r requirements.txt (line 11))
         Downloading flask_session-0.5.0-py3-none-any.whl (7.2 kB)
       Collecting Flask_SocketIO==5.3.4 (from -r requirements.txt (line 12))
         Downloading Flask_SocketIO-5.3.4-py3-none-any.whl (17 kB)
       Collecting Flask_SQLAlchemy==2.5.1 (from -r requirements.txt (line 13))
         Downloading Flask_SQLAlchemy-2.5.1-py2.py3-none-any.whl (17 kB)
       Collecting Jinja2==3.1.2 (from -r requirements.txt (line 14))
         Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
       Collecting Markdown==3.4.3 (from -r requirements.txt (line 15))
         Downloading Markdown-3.4.3-py3-none-any.whl (93 kB)
       Collecting openai==0.27.8 (from -r requirements.txt (line 16))
         Downloading openai-0.27.8-py3-none-any.whl (73 kB)
       Collecting psycopg2-binary==2.9.6 (from -r requirements.txt (line 17))
         Downloading psycopg2_binary-2.9.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
       Collecting pydub==0.25.1 (from -r requirements.txt (line 18))
         Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
       Collecting python-dotenv==0.21.1 (from -r requirements.txt (line 19))
         Downloading python_dotenv-0.21.1-py3-none-any.whl (19 kB)
       Collecting pytz==2022.6 (from -r requirements.txt (line 20))
         Downloading pytz-2022.6-py2.py3-none-any.whl (498 kB)
       Collecting requests==2.31.0 (from -r requirements.txt (line 21))
         Downloading requests-2.31.0-py3-none-any.whl (62 kB)
       Collecting SQLAlchemy==1.4.44 (from -r requirements.txt (line 22))
         Downloading SQLAlchemy-1.4.44-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
       Collecting sqlalchemy_citext==1.8.0 (from -r requirements.txt (line 23))
         Downloading sqlalchemy-citext-1.8.0.tar.gz (3.6 kB)
         Preparing metadata (setup.py): started
         Preparing metadata (setup.py): finished with status 'done'
       Collecting stripe==5.4.0 (from -r requirements.txt (line 24))
         Downloading stripe-5.4.0-py2.py3-none-any.whl (255 kB)
       Collecting Werkzeug==2.3.4 (from -r requirements.txt (line 25))
         Downloading Werkzeug-2.3.4-py3-none-any.whl (242 kB)
       Collecting langcodes==3.3.0 (from -r requirements.txt (line 26))
         Downloading langcodes-3.3.0-py3-none-any.whl (181 kB)
       Collecting language-data==1.1 (from -r requirements.txt (line 27))
         Downloading language_data-1.1-py3-none-any.whl (4.9 MB)
       Collecting emoji==2.4.0 (from -r requirements.txt (line 28))
         Downloading emoji-2.4.0.tar.gz (353 kB)
         Preparing metadata (setup.py): started
         Preparing metadata (setup.py): finished with status 'done'
       Collecting pyyaml==6.0 (from -r requirements.txt (line 29))
         Downloading PyYAML-6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (757 kB)
       Collecting email-validator==1.3.1 (from -r requirements.txt (line 30))
         Downloading email_validator-1.3.1-py2.py3-none-any.whl (22 kB)
       Collecting tenacity==8.2.2 (from -r requirements.txt (line 31))
         Downloading tenacity-8.2.2-py3-none-any.whl (24 kB)
       Collecting html2text==2020.1.16 (from -r requirements.txt (line 32))
         Downloading html2text-2020.1.16-py3-none-any.whl (32 kB)
       Collecting requests-toolbelt==1.0.0 (from -r requirements.txt (line 33))
         Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
       Collecting packaging (from gunicorn==21.1.0->-r requirements.txt (line 1))
         Downloading packaging-23.1-py3-none-any.whl (48 kB)
       Collecting jmespath<2.0.0,>=0.7.1 (from boto3==1.26.142->-r requirements.txt (line 4))
         Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
       Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.26.142->-r requirements.txt (line 4))
         Downloading s3transfer-0.6.1-py3-none-any.whl (79 kB)
       Collecting python-dateutil<3.0.0,>=2.1 (from botocore==1.29.142->-r requirements.txt (line 5))
         Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
       Collecting urllib3<1.27,>=1.25.4 (from botocore==1.29.142->-r requirements.txt (line 5))
         Downloading urllib3-1.26.16-py2.py3-none-any.whl (143 kB)
       Collecting dnspython>=1.15.0 (from eventlet==0.33.3->-r requirements.txt (line 7))
         Downloading dnspython-2.4.0-py3-none-any.whl (300 kB)
       Collecting greenlet>=0.3 (from eventlet==0.33.3->-r requirements.txt (line 7))
         Downloading greenlet-2.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (618 kB)
       Collecting six>=1.10.0 (from eventlet==0.33.3->-r requirements.txt (line 7))
         Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
       Collecting itsdangerous>=2.1.2 (from Flask==2.3.2->-r requirements.txt (line 8))
         Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
       Collecting click>=8.1.3 (from Flask==2.3.2->-r requirements.txt (line 8))
         Downloading click-8.1.6-py3-none-any.whl (97 kB)
       Collecting blinker>=1.6.2 (from Flask==2.3.2->-r requirements.txt (line 8))
         Downloading blinker-1.6.2-py3-none-any.whl (13 kB)
       Collecting cachelib (from Flask-Session==0.5.0->-r requirements.txt (line 11))
         Downloading cachelib-0.10.2-py3-none-any.whl (18 kB)
       Collecting python-socketio>=5.0.2 (from Flask_SocketIO==5.3.4->-r requirements.txt (line 12))
         Downloading python_socketio-5.8.0-py3-none-any.whl (56 kB)
       Collecting MarkupSafe>=2.0 (from Jinja2==3.1.2->-r requirements.txt (line 14))
         Downloading MarkupSafe-2.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (28 kB)
       Collecting tqdm (from openai==0.27.8->-r requirements.txt (line 16))
         Downloading tqdm-4.65.0-py3-none-any.whl (77 kB)
       Collecting aiohttp (from openai==0.27.8->-r requirements.txt (line 16))
         Downloading aiohttp-3.8.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
       Collecting charset-normalizer<4,>=2 (from requests==2.31.0->-r requirements.txt (line 21))
         Downloading charset_normalizer-3.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
       Collecting idna<4,>=2.5 (from requests==2.31.0->-r requirements.txt (line 21))
         Downloading idna-3.4-py3-none-any.whl (61 kB)
       Collecting certifi>=2017.4.17 (from requests==2.31.0->-r requirements.txt (line 21))
         Downloading certifi-2023.5.7-py3-none-any.whl (156 kB)
       Collecting marisa-trie<0.8.0,>=0.7.7 (from language-data==1.1->-r requirements.txt (line 27))
         Downloading marisa_trie-0.7.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
       Collecting httpcore>=0.17.3 (from dnspython>=1.15.0->eventlet==0.33.3->-r requirements.txt (line 7))
         Downloading httpcore-0.17.3-py3-none-any.whl (74 kB)
       Collecting sniffio<2.0,>=1.1 (from dnspython>=1.15.0->eventlet==0.33.3->-r requirements.txt (line 7))
         Downloading sniffio-1.3.0-py3-none-any.whl (10 kB)
       Collecting bidict>=0.21.0 (from python-socketio>=5.0.2->Flask_SocketIO==5.3.4->-r requirements.txt (line 12))
         Downloading bidict-0.22.1-py3-none-any.whl (35 kB)
       Collecting python-engineio>=4.3.0 (from python-socketio>=5.0.2->Flask_SocketIO==5.3.4->-r requirements.txt (line 12))
         Downloading python_engineio-4.5.1-py3-none-any.whl (53 kB)
       Collecting attrs>=17.3.0 (from aiohttp->openai==0.27.8->-r requirements.txt (line 16))
         Downloading attrs-23.1.0-py3-none-any.whl (61 kB)
       Collecting multidict<7.0,>=4.5 (from aiohttp->openai==0.27.8->-r requirements.txt (line 16))
         Downloading multidict-6.0.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (117 kB)
       Collecting async-timeout<5.0,>=4.0.0a3 (from aiohttp->openai==0.27.8->-r requirements.txt (line 16))
         Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
       Collecting yarl<2.0,>=1.0 (from aiohttp->openai==0.27.8->-r requirements.txt (line 16))
         Downloading yarl-1.9.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (282 kB)
       Collecting frozenlist>=1.1.1 (from aiohttp->openai==0.27.8->-r requirements.txt (line 16))
         Downloading frozenlist-1.4.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (250 kB)
       Collecting aiosignal>=1.1.2 (from aiohttp->openai==0.27.8->-r requirements.txt (line 16))
         Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
       Collecting h11<0.15,>=0.13 (from httpcore>=0.17.3->dnspython>=1.15.0->eventlet==0.33.3->-r requirements.txt (line 7))
         Downloading h11-0.14.0-py3-none-any.whl (58 kB)
       Collecting anyio<5.0,>=3.0 (from httpcore>=0.17.3->dnspython>=1.15.0->eventlet==0.33.3->-r requirements.txt (line 7))
         Downloading anyio-3.7.1-py3-none-any.whl (80 kB)
       Building wheels for collected packages: sqlalchemy_citext, emoji
         Building wheel for sqlalchemy_citext (setup.py): started
         Building wheel for sqlalchemy_citext (setup.py): finished with status 'done'
         Created wheel for sqlalchemy_citext: filename=sqlalchemy_citext-1.8.0-py2.py3-none-any.whl size=3548 sha256=29272c6d3566c3bf1acea079725cf5c78c25c85ce24bd7c5c08ab477eb93ece3
         Stored in directory: /tmp/pip-ephem-wheel-cache-oqwbqd2b/wheels/36/e7/40/bf4c0ae57480dba7de44c2a877edb2be7aeaf644c303ef3d3d
         Building wheel for emoji (setup.py): started
         Building wheel for emoji (setup.py): finished with status 'done'
         Created wheel for emoji: filename=emoji-2.4.0-py2.py3-none-any.whl size=350809 sha256=89f8e49cd602fd49d792c2149370e5a67419775c355e02c2154f30efb127357f
         Stored in directory: /tmp/pip-ephem-wheel-cache-oqwbqd2b/wheels/8c/bf/17/02e400a37d0292f1a44ec18e58cfb29b2db6eb86e9c0c3a03f
       Successfully built sqlalchemy_citext emoji
       Installing collected packages: pytz, pydub, urllib3, tqdm, tenacity, sniffio, six, pyyaml, python-engineio, python-dotenv, psycopg2-binary, packaging, multidict, MarkupSafe, Markdown, marisa-trie, langcodes, jmespath, itsdangerous, idna, html2text, h11, greenlet, frozenlist, emoji, click, charset-normalizer, certifi, cachelib, blinker, bidict, bcrypt, azure-cognitiveservices-speech, attrs, async-timeout, yarl, Werkzeug, SQLAlchemy, requests, python-socketio, python-dateutil, language-data, Jinja2, gunicorn, anyio, aiosignal, stripe, sqlalchemy_citext, requests-toolbelt, httpcore, Flask, deepl, botocore, aiohttp, s3transfer, openai, Flask_SQLAlchemy, Flask_SocketIO, Flask-Session, Flask_Login, Flask_Cors, dnspython, eventlet, email-validator, boto3
       Successfully installed Flask-2.3.2 Flask-Session-0.5.0 Flask_Cors-3.0.10 Flask_Login-0.6.2 Flask_SQLAlchemy-2.5.1 Flask_SocketIO-5.3.4 Jinja2-3.1.2 Markdown-3.4.3 MarkupSafe-2.1.3 SQLAlchemy-1.4.44 Werkzeug-2.3.4 aiohttp-3.8.4 aiosignal-1.3.1 anyio-3.7.1 async-timeout-4.0.2 attrs-23.1.0 azure-cognitiveservices-speech-1.28.0 bcrypt-4.0.1 bidict-0.22.1 blinker-1.6.2 boto3-1.26.142 botocore-1.29.142 cachelib-0.10.2 certifi-2023.5.7 charset-normalizer-3.2.0 click-8.1.6 deepl-1.14.0 dnspython-2.4.0 email-validator-1.3.1 emoji-2.4.0 eventlet-0.33.3 frozenlist-1.4.0 greenlet-2.0.2 gunicorn-21.1.0 h11-0.14.0 html2text-2020.1.16 httpcore-0.17.3 idna-3.4 itsdangerous-2.1.2 jmespath-1.0.1 langcodes-3.3.0 language-data-1.1 marisa-trie-0.7.8 multidict-6.0.4 openai-0.27.8 packaging-23.1 psycopg2-binary-2.9.6 pydub-0.25.1 python-dateutil-2.8.2 python-dotenv-0.21.1 python-engineio-4.5.1 python-socketio-5.8.0 pytz-2022.6 pyyaml-6.0 requests-2.31.0 requests-toolbelt-1.0.0 s3transfer-0.6.1 six-1.16.0 sniffio-1.3.0 sqlalchemy_citext-1.8.0 stripe-5.4.0 tenacity-8.2.2 tqdm-4.65.0 urllib3-1.26.16 yarl-1.9.2
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 138.1M
-----> Launching...
       Released v469
       https://gliglish.herokuapp.com/ deployed to Heroku
```

Here are the logs showing the crash:

```
Jul 19 08:37:03Z gliglish heroku/web.2 Restarting
Jul 19 08:37:03Z gliglish heroku/web.2 State changed from up to starting
Jul 19 08:37:04Z gliglish heroku/web.1 Restarting
Jul 19 08:37:04Z gliglish heroku/web.1 State changed from up to starting
Jul 19 08:37:04Z gliglish app/api Release v469 created by user fabien.snauwaert@gmail.com
Jul 19 08:37:04Z gliglish app/api Deploy e394729e by user fabien.snauwaert@gmail.com
Jul 19 08:37:04Z gliglish heroku/web.1 Stopping all processes with SIGTERM
Jul 19 08:37:04Z gliglish heroku/web.2 Stopping all processes with SIGTERM
Jul 19 08:37:05Z gliglish app/web.1 [2023-07-19 08:37:04 +0000] [2] [INFO] Handling signal: term
Jul 19 08:37:05Z gliglish app/web.2 [2023-07-19 08:37:04 +0000] [2] [INFO] Handling signal: term
Jul 19 08:37:09Z gliglish heroku/router at=info method=POST path="/api/get-past-useraudio-assessment" host=gliglish.com request_id=83a79f00-7dc9-4aad-8b65-c5c6e0f22be7 fwd="80.83.234.173" dyno=web.1 connect=1ms service=4407ms status=200 bytes=16314 protocol=https
Jul 19 08:37:09Z gliglish app/web.1 10.1.42.81 - - [19/Jul/2023:08:37:08 +0000] "POST /api/get-past-useraudio-assessment HTTP/1.1" 200 16051 "https://gliglish.com/lab/bf7b3b09-e160-4f17-b84a-b56e7df57fc9" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36"
Jul 19 08:37:09Z gliglish app/web.1 10.1.41.94 - - [19/Jul/2023:08:37:09 +0000] "POST /api/get-modelaudio-from-useraudio HTTP/1.1" 200 16012 "https://gliglish.com/lab/bf7b3b09-e160-4f17-b84a-b56e7df57fc9" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36"
Jul 19 08:37:09Z gliglish heroku/router at=info method=POST path="/api/get-modelaudio-from-useraudio" host=gliglish.com request_id=49060187-a951-4295-b37f-d0d85ca14632 fwd="80.83.234.173" dyno=web.1 connect=0ms service=4659ms status=200 bytes=16275 protocol=https
Jul 19 08:37:09Z gliglish heroku/web.2 Starting process with command `gunicorn wsgi:app -w 1 --worker-class eventlet`
Jul 19 08:37:10Z gliglish heroku/web.2 State changed from starting to crashed
Jul 19 08:37:10Z gliglish heroku/web.2 State changed from crashed to starting
Jul 19 08:37:10Z gliglish app/web.2 Error: class uri 'eventlet' invalid or not found:
Jul 19 08:37:10Z gliglish app/web.2 [Traceback (most recent call last):
Jul 19 08:37:10Z gliglish app/web.2 File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/workers/geventlet.py", line 10, in <module>
Jul 19 08:37:10Z gliglish app/web.2 import eventlet
Jul 19 08:37:10Z gliglish app/web.2 File "/app/.heroku/python/lib/python3.11/site-packages/eventlet/__init__.py", line 17, in <module>
Jul 19 08:37:10Z gliglish app/web.2 from eventlet import convenience
Jul 19 08:37:10Z gliglish app/web.2 File "/app/.heroku/python/lib/python3.11/site-packages/eventlet/convenience.py", line 7, in <module>
Jul 19 08:37:10Z gliglish app/web.2 from eventlet.green import socket
Jul 19 08:37:10Z gliglish app/web.2 File "/app/.heroku/python/lib/python3.11/site-packages/eventlet/green/socket.py", line 21, in <module>
Jul 19 08:37:10Z gliglish app/web.2 from eventlet.support import greendns
Jul 19 08:37:10Z gliglish app/web.2 File "/app/.heroku/python/lib/python3.11/site-packages/eventlet/support/greendns.py", line 79, in <module>
Jul 19 08:37:10Z gliglish app/web.2 setattr(dns, pkg, import_patched('dns.' + pkg))
Jul 19 08:37:10Z gliglish app/web.2 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 08:37:10Z gliglish app/web.2 File "/app/.heroku/python/lib/python3.11/site-packages/eventlet/support/greendns.py", line 61, in import_patched
Jul 19 08:37:10Z gliglish app/web.2 return patcher.import_patched(module_name, **modules)
Jul 19 08:37:10Z gliglish app/web.2 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 08:37:10Z gliglish app/web.2 File "/app/.heroku/python/lib/python3.11/site-packages/eventlet/patcher.py", line 132, in import_patched
Jul 19 08:37:10Z gliglish app/web.2 return inject(
Jul 19 08:37:10Z gliglish app/web.2 ^^^^^^^
Jul 19 08:37:10Z gliglish app/web.2 File "/app/.heroku/python/lib/python3.11/site-packages/eventlet/patcher.py", line 109, in inject
Jul 19 08:37:10Z gliglish app/web.2 module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
Jul 19 08:37:10Z gliglish app/web.2 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 08:37:10Z gliglish app/web.2 File "/app/.heroku/python/lib/python3.11/site-packages/dns/dnssecalgs/__init__.py", line 5, in <module>
Jul 19 08:37:10Z gliglish app/web.2 from dns.dnssecalgs.dsa import PrivateDSA, PrivateDSANSEC3SHA1
Jul 19 08:37:10Z gliglish app/web.2 File "/app/.heroku/python/lib/python3.11/site-packages/dns/dnssecalgs/dsa.py", line 3, in <module>
Jul 19 08:37:10Z gliglish app/web.2 from cryptography.hazmat.backends import default_backend
Jul 19 08:37:10Z gliglish app/web.2 ModuleNotFoundError: No module named 'cryptography'
Jul 19 08:37:10Z gliglish app/web.2 During handling of the above exception, another exception occurred:
Jul 19 08:37:10Z gliglish app/web.2 Traceback (most recent call last):
Jul 19 08:37:10Z gliglish app/web.2 File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/util.py", line 111, in load_class
Jul 19 08:37:10Z gliglish app/web.2 mod = importlib.import_module('.'.join(components))
Jul 19 08:37:10Z gliglish app/web.2 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 08:37:10Z gliglish app/web.2 File "/app/.heroku/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
Jul 19 08:37:10Z gliglish app/web.2 return _bootstrap._gcd_import(name[level:], package, level)
Jul 19 08:37:10Z gliglish app/web.2 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 19 08:37:10Z gliglish app/web.2 File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
Jul 19 08:37:10Z gliglish app/web.2 File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
Jul 19 08:37:10Z gliglish app/web.2 File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
Jul 19 08:37:10Z gliglish app/web.2 File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
Jul 19 08:37:10Z gliglish app/web.2 File "<frozen importlib._bootstrap_external>", line 940, in exec_module
Jul 19 08:37:10Z gliglish app/web.2 File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Jul 19 08:37:10Z gliglish app/web.2 File "/app/.heroku/python/lib/python3.11/site-packages/gunicorn/workers/geventlet.py", line 12, in <module>
Jul 19 08:37:10Z gliglish app/web.2 raise RuntimeError("eventlet worker requires eventlet 0.24.1 or higher")
Jul 19 08:37:10Z gliglish app/web.2 RuntimeError: eventlet worker requires eventlet 0.24.1 or higher
Jul 19 08:37:10Z gliglish app/web.2 ]
Jul 19 08:37:10Z gliglish heroku/web.2 Process exited with status 1
```

I run gunicorn this way:

```
# Procfile
web: gunicorn wsgi:app -w 1 --worker-class eventlet
```

What I find most confusing is that it started crashing this way before explicitly upgrading to 21.1.0. i.e. *this* worked fine for months:

```
gunicorn @ git+https://github.com/benoitc/gunicorn.git@792edf6
```

With still this exact line in place (instead of `gunicorn==x.x.x`), it started crashing when I deployed yesterday on July 18th (my first deploy in a week).

Upgrading to 21.1.0 didn't fix it – like I said, the error is the same.

So I'm confused as to why `gunicorn @ git+https://github.com/benoitc/gunicorn.git@792edf6` doesn't let me downgrade.

I'm stuck and unable to deploy until I find a fix.

Anyone else running into this?

**Comment by benoitc** [comment]
the cryptography package need to be installed separately.  I don't know why it's not a dependency by default of the eventlet project.

**Comment by benoitc** [comment]
For our testing of the worker I edited https://github.com/benoitc/gunicorn/blob/master/requirements_test.txt with that dependency required by latest eventlet. It's most probably related to the SSL module but not an issue in Gunicorn itself. I will drop a note in the documentation.

**Comment by fabswt** [comment]
Thanks for the prompt reply.

Found the culprit: dnspython. Pinning it to 2.3.0 works fine:

```
dnspython==2.3.0
```

(I'd removed it from requirements.txt a while back, which meant latest `2.4.0` was being used.)

I hate myself for it because I'd ran into the issue before! 🤦‍♂️

Tested OK with:

- gunicorn @ git+https://github.com/benoitc/gunicorn.git@792edf6
- gunicorn 21.1.0

The app no longer crashes.

Sorry about the false alarm.

**Comment by benoitc** [comment]
thanks for the feedback :)
