### ISSUE TITLE
log error

### ISSUE THREAD

**Issue by danerlt** [benoitc/gunicorn#3055]
I encountered an error while using flask and gunicorn and meinheld during the execution process.

start command:
```bash
gunicorn -c /app/run/gunicorn.conf.py -b 0.0.0.0:5000 main:app
```
gunicorn.conf.py
```python
import multiprocessing

try:
cores = multiprocessing.cpu_count()
workers = cores * 1 + 1
print("workers:", workers)
worker_class = "meinheld.gmeinheld.MeinheldWorker"  
keepalive = 10
timeout = 60
threads = 32
preload_app = True
reload = True
x_forwarded_for_header = 'X_FORWARDED-FOR'

```

the error trace is :
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 360, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 554, in reap_workers
    self.log.error(msg)
TypeError: _error() missing 2 required positional arguments: 'val' and 'tb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 236, in run
    super().run()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 234, in run
    exc_info=True)
TypeError: _error() got an unexpected keyword argument 'exc_info'
```

version info:
```
Flask==2.2.5
meinheld==1.0.2
gunicorn==21.2.0
```

**Comment by XingDongZhe** [comment]
This is not gunicorn issue, it is meinheld. And sorry to find a easy way to fix issue of meinheld
I wonder what version of meinheld do you start to use?
I dig into source code, found that it gets same problem start at v0.5.1

**Comment by benoitc** [comment]
answered.
