### ISSUE TITLE
--worker-class eventlet does not successfully switch to websocket, Traceback

### ISSUE THREAD

**Issue by ReimarBauer** [benoitc/gunicorn#3058]
Hi there,

we use gunicorn for our flask socketio mscolab server by the conda-forge application MSS.

 I want to report what I found using the 21.2.0 gunicorn.

 In the past I used to call our app this way
` 
 gunicorn --access-logfile INSTANCE/log/mscolab-access.log --error-logfile INSTANCE/log/mscolab-error.log --worker-class eventlet  -b 127.0.0.1:8083 mscolab:APP`
 
 when I do this with 21.2.0 I only get polling working.
 
 When I remove the parameter --worker-class eventlet e.g.
` gunicorn --access-logfile INSTANCE/log/mscolab-access.log --error-logfile INSTANCE/log/mscolab-error.log -b 127.0.0.1:8083 mscolab:APP`
 
 then also eventlet is used, because of its precedence but it crashes after upgrading to websocket.
 
 I got this failure report
 
```
 Traceback (most recent call last):
  File "/home/mss-mscolab/mambaforge/envs/mssenv/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/mss-mscolab/mambaforge/envs/mssenv/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 193, in handle_request
    util.reraise(*sys.exc_info())
  File "/home/mss-mscolab/mambaforge/envs/mssenv/lib/python3.9/site-packages/gunicorn/util.py", line 641, in reraise
    raise value
  File "/home/mss-mscolab/mambaforge/envs/mssenv/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 184, in handle_request
    resp.write(item)
  File "/home/mss-mscolab/mambaforge/envs/mssenv/lib/python3.9/site-packages/gunicorn/http/wsgi.py", line 326, in write
    self.send_headers()
  File "/home/mss-mscolab/mambaforge/envs/mssenv/lib/python3.9/site-packages/gunicorn/http/wsgi.py", line 322, in send_headers
    util.write(self.sock, util.to_bytestring(header_str, "latin-1"))
  File "/home/mss-mscolab/mambaforge/envs/mssenv/lib/python3.9/site-packages/gunicorn/util.py", line 299, in write
    sock.sendall(data)
OSError: [Errno 9] Bad file descriptor
```

I reviewed the changes and found
https://github.com/benoitc/gunicorn/commit/858b743d072c7a6cbbf3eff1fffef08e76212e0e

with undoing this I could now execute the first call and I tried again

`gunicorn --access-logfile INSTANCE/log/mscolab-access.log --error-logfile INSTANCE/log/mscolab-error.log --worker-class eventlet  -b 127.0.0.1:8083 mscolab:APP`

this now upgrades to websocket and it is not giving a traceback ;) 

Please have a look on this too. Thx

**Comment by ReimarBauer** [comment]
gunicorn 22.0.0 was released

**Comment by benoitc** [comment]
no activity since awhile. closing feel free to create a new ticket if needed.

**Comment by benoitc** [comment]
Closing - this issue was reported against gunicorn 21.2.0 which is now outdated. Please retest with the current version (23.0.0+) and open a new issue if the problem persists with updated reproduction steps.
