### ISSUE TITLE
gunicorn.http.body.Body doesn't implement io.BaseIO

### ISSUE THREAD

**Issue by The-Gopher** [benoitc/gunicorn#3226]
That causes this to fail

```python

from io import TextIOWrapper
from flask import Flask, request

app = Flask(__name__)

@app.route("/", methods=["POST"])
def test():
    TextIOWrapper(request.stream, encoding="utf8")
    return "Hello, World!"
```

```
gunicorn --bind=":5001" --preload --timeout=0 "gunicorn_test:app"

curl -X 'POST' localhost:5001 -d 'stringasdf,asdf,asdf
asdf,asdf
asdf'
````

With this exception
```
Traceback (most recent call last):
  File ".../python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "gunicorn_test.py", line 9, in test
    TextIOWrapper(request.stream, encoding="utf8")
AttributeError: 'Body' object has no attribute 'readable'
````

**Comment by The-Gopher** [comment]
Is there a standard wrapper? I've written one which works for the test case I have but I'm not confident it will be solid.

```python
"""
from flask import request
stream = TextIOWrapper(InputStreamWrapper(request.stream), encoding="utf8")
"""

import io
from typing import Protocol


class StreamProtocol(Protocol):
    @property
    def name(self) -> str: ...

    def read(self, size: int = -1, /) -> bytes: ...


class InputStreamWrapper(io.IOBase):
    def __init__(self, stream: StreamProtocol):
        self.stream = stream

    @property
    def name(self) -> str:
        return self.stream.name

    def readable(self) -> bool:
        return True

    def read(self, size: int = -1) -> bytes:
        return self.stream.read(size)

```

**Comment by benoitc** [comment]
You can already stream the body using read/readline or iteration, si using  an abstraction on top of it should be feasible: https://github.com/benoitc/gunicorn/blob/master/gunicorn/http/body.py#L179-L264 

Why do you need another abstraction over it?

**Comment by The-Gopher** [comment]
It is mostly because that is the abstraction many other python functions accept and I was shocked when creating a TextIOWrapper (from the stdlib) was throwing an error on create when I passed what I thought was a valid IO[bytes]. The reason I thought it was a valid IO[bytes] is that is what werkzeug presents it as which I guess is incorrect.

Since PEP-3333 specifies it should only provide the limit function I'm fine closing this as wont fix.
