### ISSUE TITLE
cwd = os.getcwd() message on Openbsd

### ISSUE THREAD

**Issue by mikygee** [benoitc/gunicorn#3291]
OS: Openbsd 7.5
Netbox: v4.0.11

Hello,

I'm trying to execute an application called netbox that uses gunicorn like this
`# su -s /bin/ksh _netbox -c '/var/www/htdocs/applications/netbox-4.0.11/env/bin/gunicorn --name netbox --pid /var/run/netbox/netbox.pid --user=www --group=www --config /var/www/htdocs/applications/netbox-4.0.11/gunicorn.py --log-level=info --log-file=- netbox.wsgi:application'`

And I see these messages

```
Traceback (most recent call last):
  File "/var/www/htdocs/applications/netbox-4.0.11/env/lib/python3.10/site-packages/gunicorn/util.py", line 448, in getcwd
    a = os.stat(os.environ['PWD'])
FileNotFoundError: [Errno 2] No such file or directory: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/htdocs/applications/netbox-4.0.11/env/bin/gunicorn", line 5, in <module>
    from gunicorn.app.wsgiapp import run
  File "/var/www/htdocs/applications/netbox-4.0.11/env/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 8, in <module>
    from gunicorn.app.base import Application
  File "/var/www/htdocs/applications/netbox-4.0.11/env/lib/python3.10/site-packages/gunicorn/app/base.py", line 12, in <module>
    from gunicorn.config import Config, get_default_config_file
  File "/var/www/htdocs/applications/netbox-4.0.11/env/lib/python3.10/site-packages/gunicorn/config.py", line 1060, in <module>
    class Chdir(Setting):
  File "/var/www/htdocs/applications/netbox-4.0.11/env/lib/python3.10/site-packages/gunicorn/config.py", line 1065, in Chdir
    default = util.getcwd()
  File "/var/www/htdocs/applications/netbox-4.0.11/env/lib/python3.10/site-packages/gunicorn/util.py", line 455, in getcwd
    cwd = os.getcwd()
PermissionError: [Errno 13] Permission denied
```

cwd doesn't exist on openbsd, it's pwd here.

I manage to avoid the error like this
`# su -s /bin/ksh _netbox -c 'cd /var/www/htdocs/applications/netbox-4.0.11 && export PWD=/var/www/htdocs/applications/netbox-4.0.11 && /var/www/htdocs/applications/netbox-4.0.11/env/bin/gunicorn --name netbox --pid /var/run/netbox/netbox.pid --user=www --group=www --config /var/www/htdocs/applications/netbox-4.0.11/gunicorn.py --log-level=info --log-file=- netbox.wsgi:application'`
But what should be used is not the PWD environnement variable but the pwd command.

At line 445 file netbox-4.0.11/env/lib/python3.10/site-packages/gunicorn/util.py, I don't see any pwd related command, just cwd

```
def getcwd():
    # get current path, try to use PWD env first
    try:
        a = os.stat(os.environ['PWD'])
        b = os.stat(os.getcwd())
        if a.st_ino == b.st_ino and a.st_dev == b.st_dev:
            cwd = os.environ['PWD']
        else:
            cwd = os.getcwd()
    except Exception:
        cwd = os.getcwd()
    return cwd
```

I would like to ask if gunicorn supports openbsd and pwd instead of cwd.
If not could you implement it.

Thank you

**Comment by mikygee** [comment]
Hello,
I'm closing this issue.
Thank you for your advice, about the location, I'll think about it, what to do.
I see Netbox as a web applicatoin, that's why I put it there, it's accessed by the user through a browser. I installed it on a specific server, isolated from Internet and with ACLs.
