### ISSUE TITLE
ValueError:I/O operation on closed file

### ISSUE THREAD

**Issue by xiangpingjiang** [benoitc/gunicorn#3324]
version 22.0.0

error :
2024-11-16 02:46:19,802 [526764] [ERROR] [glogging.exception:284] Exception in worker process
Traceback (most recent call last):
  File "/home/admin/run/lib64/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/admin/run/lib64/python3.10/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
    super().init_process()
  File "/home/admin/run/lib64/python3.10/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.log.close_on_exec()
  File "/home/admin/run/lib64/python3.10/site-packages/gunicorn/glogging.py", line 401, in close_on_exec
    util.close_on_exec(handler.stream.fileno())
ValueError: I/O operation on closed file

there is still this issue   https://github.com/benoitc/gunicorn/issues/863

**Comment by benoitc** [comment]
Closing due to insufficient information. Please provide a reproducible example, gunicorn version, Python version, and full traceback if this issue persists.
