### ISSUE TITLE
OSError on trying to load django config from inaccesible director for non-django app

### ISSUE THREAD

**Issue by tschundler** [benoitc/gunicorn#578]
Starting up gunicorn (in this case for a flask app), in 17.5 (this did not occur in 0.16.1), gunicorn fails to start if the current directory is my home directory.

When gunicorn starts, it switches to to user in the configuration file. And now it seems to hunt for a django configuration file in the current directory, which the user it is now running as does not have access to.
gunicorn/app/wsgiapp.py catches a RuntimeError, but not this OSError.

```
2013-07-24 18:36:22 [4906] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/opt/***/python2.7/site-packages/gunicorn-17.5-py2.7.egg/gunicorn/arbiter.py", line 473, in spawn_worker
    worker.init_process()
  File "/opt/***/python2.7/site-packages/gunicorn-17.5-py2.7.egg/gunicorn/workers/base.py", line 100, in init_process
    self.wsgi = self.app.wsgi()
  File "/opt/***/python2.7/site-packages/gunicorn-17.5-py2.7.egg/gunicorn/app/base.py", line 115, in wsgi
    self.callable = self.load()
  File "/opt/***/python2.7/site-packages/gunicorn-17.5-py2.7.egg/gunicorn/app/wsgiapp.py", line 29, in load
    djangoapp.make_default_env(self.cfg)
  File "/opt/***/python2.7/site-packages/gunicorn-17.5-py2.7.egg/gunicorn/app/djangoapp.py", line 59, in make_default_env
    project_path, settings_name = find_settings_module(cwd)
  File "/opt/***/python2.7/site-packages/gunicorn-17.5-py2.7.egg/gunicorn/app/djangoapp.py", line 26, in find_settings_module
    for d in os.listdir(path):
OSError: [Errno 13] Permission denied: '/home/tschundler'
```

**Comment by mohanraj-r** [comment]
@benoitc 

I am seeing this in 19.6.0. I am running a django app using `run_gunicorn` - I realize this way is deprecated but I am freezing it into a binary using PyInstaller and hence I have to rely on this method. When the user specified in the gunicorn config doesn't have executable perms (read / write doesn't seem to matter) on the cwd the error seems to occur. When I give `711` perms on the directory, the error goes away. Is this to be expected?

```
[2016-08-01 20:38:15 +0000] [15097] [INFO] Starting gunicorn 19.6.0
[2016-08-01 20:38:15 +0000] [15097] [INFO] Listening at: https://0.0.0.0:8443 (15097)
[2016-08-01 20:38:15 +0000] [15097] [INFO] Using worker: sync
[2016-08-01 20:38:15 +0000] [15104] [INFO] Booting worker with pid: 15104
[2016-08-01 20:38:15 +0000] [15104] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
  File "site-packages/gunicorn/workers/base.py", line 126, in init_process
  File "site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
  File "site-packages/gunicorn/app/base.py", line 67, in wsgi
  File "site-packages/gunicorn/app/djangoapp.py", line 135, in load
OSError: [Errno 13] Permission denied: '/home/vagrant'
[2016-08-01 20:38:15 +0000] [15104] [INFO] Worker exiting (pid: 15104)
[2016-08-01 20:38:15 +0000] [15105] [INFO] Booting worker with pid: 15105
[2016-08-01 20:38:15 +0000] [15105] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
  File "site-packages/gunicorn/workers/base.py", line 126, in init_process
  File "site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
  File "site-packages/gunicorn/app/base.py", line 67, in wsgi
  File "site-packages/gunicorn/app/djangoapp.py", line 135, in load
OSError: [Errno 13] Permission denied: '/home/vagrant'
[2016-08-01 20:38:15 +0000] [15105] [INFO] Worker exiting (pid: 15105)
[2016-08-01 20:38:15 +0000] [15097] [INFO] Shutting down: Master
[2016-08-01 20:38:15 +0000] [15097] [INFO] Reason: Worker failed to boot.
```

**Comment by mohanraj-r** [comment]
I found that specifying a `chdir` setting in the config file to point to a dir on which the gunicorn `user` has access to fixes this error. 

Maybe the exception case could be handled and a better error message printed to the user?

**Comment by benoitc** [comment]
@mohanraj-r this ticket is closed. The idea is interesting though, can you open a new ticket asking for some log clarifications?
