### ISSUE TITLE
buffered keep alive requests fail during worker shutdown

### ISSUE THREAD

**Issue by bninja** [benoitc/gunicorn#712]
env:
- python v2.7
- gunicorn v18.0 daemonized
- gevent v1.0 worker type
- keep alive lb proxy (aws elb) in front of gunicorn

under load hup gunicorn (to reload) usually causes:

``` python
21:13:20,616 ERROR [gunicorn.error] [11335] [Dummy-2739] [guru_id=] Socket error processing request.
Traceback (most recent call last):
  File "/opt/rump/embedded/lib/python2.7/site-packages/gunicorn/workers/async.py", line 45, in handle
    self.handle_request(listener, req, client, addr)
  File "/opt/rump/embedded/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 151, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File "/opt/rump/embedded/lib/python2.7/site-packages/gunicorn/workers/async.py", line 83, in handle_request
    listener.getsockname(), self.cfg)
  File "<string>", line 1, in getsockname
error: [Errno 9] Bad file descriptor
```

looks like:
- gunicorn async worker is serving buffered keep-alive requests
- tries to get socketname from listener
- listener has been closed (stop accepting) since this is during worker shutdown so errs

**Comment by duyanghao** [comment]
env:
Docker-registry V1 master
python 2.6.6
python-gunicorn 19.4.1
python-gevent 0.13.8
python-greenlet 0.4.2
libevent 1.4.13

Under  HTTP request /v1/search and pull images usually causes:

[2015-12-28 16:34:12 +0000] [11122] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/gunicorn/workers/async.py", line 64, in handle
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/lib/python2.6/site-packages/gunicorn/workers/async.py", line 35, in handle
    listener_name = listener.getsockname()
  File "<string>", line 1, in getsockname
error: [Errno 9] Bad file descriptor
[2015-12-28 16:34:12 +0000] [11122] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/gunicorn/workers/async.py", line 64, in handle
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/lib/python2.6/site-packages/gunicorn/workers/async.py", line 35, in handle
    listener_name = listener.getsockname()
  File "<string>", line 1, in getsockname
error: [Errno 9] Bad file descriptor

**Comment by benoitc** [comment]
this is not related to above can you reopen  a new ticket with that issue. Sounds like an issue wile interacting with the docker env...
