### ISSUE TITLE
gunicorn.workers.ggevent.GeventWorker in ErrorType

### ISSUE THREAD

**Issue by aztrock** [benoitc/gunicorn#715]
```
Traceback (most recent call last):
  File "/opt/repositories/django/local/lib/python3.3/site-packages/gevent/baseserver.py", line 140, in _do_read
    args = self.do_read()
  File "/opt/repositories/django/local/lib/python3.3/site-packages/gevent/server.py", line 98, in do_read
    return socket(_sock=client_socket), address
TypeError: __init__() got an unexpected keyword argument '_sock'
<StreamServer at 0xb6bc058c fileno=5 address=0.0.0.0:8000 handle=functools.partial(<bound method GeventWorker.handle of <gunicorn.workers.ggevent.GeventWorker object at 0xb6bf458c>>, <gunicorn.sock.TCPSocket object at 0xb6bf450c>)> failed with TypeError
```

**Comment by gjcarneiro** [comment]
You can now close the bug.  I tested that this is fixed in git (but not in the latest release).  The code in git seems to work fine for python 3 and gevent from git.

**Comment by tilgovi** [comment]
Thanks!
