### ISSUE TITLE
Unexplainable Gunicorn Request Failure

### ISSUE THREAD

**Issue by dsoprea** [benoitc/gunicorn#798]
Because there haven't been any releases with the config-name fix, I was forced to rename my configurations to ".py", and update my production with *master*. It was working. However, today I started seeing this in production, where things weren't working at all:

```
2014-06-18 21:02:23 [13593] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 91, in handle
    parser = http.RequestParser(self.cfg, client)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/parser.py", line 49, in __init__
    super(RequestParser, self).__init__(Request, *args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
2014-06-18 21:02:23,451 - gunicorn.error - ERROR - Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 91, in handle
    parser = http.RequestParser(self.cfg, client)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/parser.py", line 49, in __init__
    super(RequestParser, self).__init__(Request, *args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
2014-06-18 21:21:25 [13593] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 91, in handle
    parser = http.RequestParser(self.cfg, client)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/parser.py", line 49, in __init__
    super(RequestParser, self).__init__(Request, *args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
2014-06-18 21:21:25,111 - gunicorn.error - ERROR - Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 91, in handle
    parser = http.RequestParser(self.cfg, client)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/http/parser.py", line 49, in __init__
    super(RequestParser, self).__init__(Request, *args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
```

I believe it *was* working, but nothing has changed.

I was forced to keep all of my renamed configuration (renamed to ".py"), hand-deleting the *git*-installed *gunicorn* version, and installing the last published release (19.0).

What's going on in this error?

**Comment by benoitc** [comment]
not reproduced since. closing the issue.
