### ISSUE TITLE
GreenletExit error in Django + Gunicorn app

### ISSUE THREAD

**Issue by parisk** [benoitc/gunicorn#924]
I am running a Django app that is being served by Gunicorn, which raises `GreenletExit` exceptions from time to time.

The main issue is caused because I have enabled exception reporting in Django and I get email reports with `GreenletExit` exceptions too often. From what I have read at http://www.gevent.org/gevent.html#gevent.GreenletExit, this seems like a graceful exiting, but shouldn't it be caught somewhere and not reach the surface of the app?

Is this an issue of Gunicorn or Django, or should it be handled somehow by me?

### Software version info

- Python version: `2.7.6 (default, Mar 22 2014, 22:59:56) \n[GCC 4.8.2]`
- Django version: `1.6.1`
- Gunicorn version: ` 19.1.1`

### Gunicorn settings file

```python
worker_class = 'gevent'
port = config['port']
bind = '0.0.0.0:%s' % port
pidfile = '/run/app.pid'
loglevel = 'info'
workers = multiprocessing.cpu_count() * 2 + 1
max_requests = 1000
timeout = 60
accesslog = '/var/log/app/gunicorn.access.log'
errorlog = '/var/log/app/gunicorn.error.log'
statsd_host = config['statsd_host']
```

### Exception raised

```
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)

  File "/home/app/common/decorators.py", line 86, in wrapped_view
    return view_func(view, request, *args, **kwargs)

  File "/home/app/common/decorators.py", line 75, in wrapped_view
    return view_func(view, request, *args, **kwargs)

  File "/home/app/resources/views.py", line 228, in get
    return self.action_view(request)

  File "/home/app/resources/views.py", line 346, in action_view
    resource = self.get_resource(request, project['id'], resource_id)

  File "/home/app/resources/views.py", line 206, in get_resource
    return resource_client.detail(resource_id)

  File "/home/app/common/internal_api.py", line 75, in detail
    return self._response_handle(get(path, **kwargs))

  File "/home/app/common/internal_api.py", line 11, in get
    resp = requests.get(INTERNAL_API + path, **kwargs)

  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)

  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)

  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)

  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)

  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 330, in send
    timeout=timeout

  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 542, in urlopen
    body=body, headers=headers)

  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 367, in _make_request
    conn.request(method, url, **httplib_request_kw)

  File "/usr/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)

  File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)

  File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)

  File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)

  File "/usr/lib/python2.7/httplib.py", line 791, in send
    self.connect()

  File "/usr/lib/python2.7/httplib.py", line 772, in connect
    self.timeout, self.source_address)

  File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 579, in create_connection
    sock.connect(sa)

  File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 347, in connect
    self._wait(self._write_event)

  File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 298, in _wait
    self.hub.wait(watcher)

  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 341, in wait
    result = waiter.get()

  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 568, in get
    return self.hub.switch()

  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 331, in switch
    return greenlet.switch(self)

GreenletExit
```

**Comment by tilgovi** [comment]
This issue is old and there is no new information. Unfortunately, I believe that if the greenlet exits for any number of valid reasons, such as the server shutting down, this might be caught by Django because it catched `Exception` and logs it with its exception handling middleware.

I'm not sure there's any action here, but if anyone encounters similar errors please report them and we can test. Please provide the worker and relevant versions (like the version of gevent).

**Comment by jhh3000** [comment]
Hi,

We are encountering the same issues. Here's some relevant information to start off with:

Django==1.9.7
gevent==1.1.2
gunicorn==19.6.0
requests==2.5.0
nginx-full [1.4.6-1ubuntu3.4]

Stack trace:

```
Traceback (most recent call last):
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  ***6 internal / irrelevant calls***
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/opbeat/instrumentation/packages/base.py", line 63, in __call__
    args, kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/opbeat/instrumentation/packages/base.py", line 222, in call_if_sampling
    return self.call(module, method, wrapped, instance, args, kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/opbeat/instrumentation/packages/requests.py", line 37, in call
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 518, in urlopen
    body=body, headers=headers)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/gevent/_ssl2.py", line 228, in recv
    return self.read(buflen)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/gevent/_ssl2.py", line 130, in read
    self._wait(self._read_event, timeout_exc=_SSLErrorReadTimeout)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/gevent/_socket2.py", line 179, in _wait
    self.hub.wait(watcher)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/gevent/hub.py", line 630, in wait
    result = waiter.get()
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/gevent/hub.py", line 878, in get
    return self.hub.switch()
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/gevent/hub.py", line 609, in switch
    return greenlet.switch(self)
GreenletExit
```

From what I can tell, the worker doesn't exit, but hangs instead. It seems like the requests package here is in part to blame. Here are some conjectures:
- The worker is waiting on an external API call, times out, and gevent panics
- The worker attempts to give up its monitor since the request is awaiting a response, but something blows up
- The worker runs out of available threads, and so can't acquire the monitor? Unlikely

Thoughts?

**Comment by DylanYoung** [comment]
@jhh3000 Did you ever resolve this?

**Comment by melbic** [comment]
I would be interested in that too, seeing some of those errors as well...

**Comment by plkvlk** [comment]
Me too.

**Comment by roddajohn** [comment]
I'm seeing the same sort of thing -- doesn't seem to be a pattern in terms of route, or time spent before a `GreenletExit`
