### ISSUE TITLE
url encode error 500

### ISSUE THREAD

**Issue by larryhq** [benoitc/gunicorn#930]
http://<mysite.com>/api/v1/tags/%E5%A5%94%E9%A9%B0/cards/ 
python3.4.2 + django1.7.1 + gunicorn19.1.1
if url include chinese ,it traceback 500 error

``` bash
Traceback (most recent call last):
  File "/home/ubuntu/Envs/guadou/lib/python3.4/site-packages/aiohttp/server.py", line 215, in start
    yield from handler
  File "/home/ubuntu/Envs/guadou/lib/python3.4/site-packages/aiohttp/wsgi.py", line 153, in handle_request
    riter = self.wsgi(environ, response.start_response)
  File "/home/ubuntu/Envs/guadou/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
    request = self.request_class(environ)
  File "/home/ubuntu/Envs/guadou/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 86, in __init__
    path_info = get_path_info(environ)
  File "/home/ubuntu/Envs/guadou/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 203, in get_path_info
    path_info = get_bytes_from_wsgi(environ, 'PATH_INFO', '/')
  File "/home/ubuntu/Envs/guadou/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 250, in get_bytes_from_wsgi
    return value if six.PY2 else value.encode(ISO_8859_1)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 13-14: ordinal not in range(256)

```

**Comment by nypisces** [comment]
@asvetlov Fix it https://github.com/KeepSafe/aiohttp/pull/248

**Comment by tilgovi** [comment]
Do we need this issue here or is it an upstream issue?

**Comment by benoitc** [comment]
should be probably closed there. Maybe we could add a test about the version inside the worker like others?

**Comment by tilgovi** [comment]
Maybe we could add a test about the version inside the worker like others?

Where do you mean? Is there an example?

**Comment by benoitc** [comment]
oups sorry. yed the evenlet worker is checking the version installed.

**Comment by benoitc** [comment]
i'm closing this issue.
