### ISSUE TITLE
TypeError when running with --worker-class socketio.sgunicorn.GeventSoetIOWorker

### ISSUE THREAD

**Issue by fzumstein** [benoitc/gunicorn#975]
When I try to run the [example](https://github.com/miguelgrinberg/Flask-SocketIO/tree/master/example) from Flask-SocketIO, I get the following error, any ideas?

```
(env)root@test4:~/Flask-SocketIO/example# env/bin/gunicorn --worker-class socketio.sgunicorn.GeventSoetIOWorker app:app
[2015-02-03 12:05:42 +0000] [13839] [INFO] Starting gunicorn 19.2.0
[2015-02-03 12:05:42 +0000] [13839] [INFO] Listening at: http://127.0.0.1:8000 (13839)
[2015-02-03 12:05:42 +0000] [13839] [INFO] Using worker: socketio.sgunicorn.GeventSoetIOWorker
Traceback (most recent call last):
  File "env/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/root/Flask-SocketIO/example/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/root/Flask-SocketIO/example/env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 189, in run
    super(Application, self).run()
  File "/root/Flask-SocketIO/example/env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/root/Flask-SocketIO/example/env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 170, in run
    self.manage_workers()
  File "/root/Flask-SocketIO/example/env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 473, in manage_workers
    self.spawn_workers()
  File "/root/Flask-SocketIO/example/env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 536, in spawn_workers
    self.spawn_worker()
  File "/root/Flask-SocketIO/example/env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 490, in spawn_worker
    self.cfg, self.log)
TypeError: 'str' object is not callable
```

**Comment by fzumstein** [comment]
sorry for the noise... typo in `GeventSocketIOWorker`
