### ISSUE TITLE
Workers crashing on shutdown in Python 3 on OS X

### ISSUE THREAD

**Issue by AlexanderOMara** [benoitc/gunicorn#981]
I'm having a strange issue with using gunicorn and Django with Python 3, where when I send a keyboard interrupt with `Crtl` + `C` on OS X, I receive the application quite unexpectedly dialog.

> **Python quit unexpectedly.**
> Click Reopen to open the application again. Click Report to see more detailed information and send a report to Apple.

I am using Python 3.4.2 installed via Homebrew on OS X 10.9, and installed Django and gunicorn into a virtual environment with `pyvenv`. I only get this when using Python 3. When I create the exact same setup using `virtualenv` in Python 2, it does not throw this error on shutdown.

Here are the commands I ran to get to the error, followed by `Ctrl` + `C`.

```
$ pyvenv .
$ source bin/activate
$ pip install Django
$ pip install gunicorn
$ django-admin.py startproject hello
$ cd hello
$ gunicorn hello.wsgi:application --bind localhost:8000
```

I've narrowed it do to an issue with the workers shutting down. If I run `gunicorn` with `--workers 0`, I do not get the error. Sometimes, though not every time, when I run it with `--workers 3`, I will get a stack trace among the output, but it is not always the same stack trace. Here are two different outputs I got.

```
[2015-02-08 19:38:53 -0500] [5494] [INFO] Starting gunicorn 19.2.1
[2015-02-08 19:38:53 -0500] [5494] [INFO] Listening at: http://127.0.0.1:8000 (5494)
[2015-02-08 19:38:53 -0500] [5494] [INFO] Using worker: sync
[2015-02-08 19:38:53 -0500] [5497] [INFO] Booting worker with pid: 5497
[2015-02-08 19:38:53 -0500] [5498] [INFO] Booting worker with pid: 5498
[2015-02-08 19:38:53 -0500] [5499] [INFO] Booting worker with pid: 5499
^C[2015-02-09 00:38:54 +0000] [5497] [INFO] Worker exiting (pid: 5497)
[2015-02-09 00:38:54 +0000] [5499] [INFO] Worker exiting (pid: 5499)
[2015-02-09 00:38:54 +0000] [5498] [INFO] Worker exiting (pid: 5498)
[2015-02-08 19:38:54 -0500] [5494] [INFO] Handling signal: int
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/weakref.py", line 569, in _exitfunc
    f()
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/weakref.py", line 488, in __call__
    def __call__(self, _=None):
  File "REDACTED/lib/python3.4/site-packages/gunicorn/workers/base.py", line 151, in handle_quit
    sys.exit(0)
SystemExit: 0
[2015-02-08 19:38:54 -0500] [5494] [INFO] Shutting down: Master
```

```
[2015-02-08 19:40:37 -0500] [5523] [INFO] Starting gunicorn 19.2.1
[2015-02-08 19:40:37 -0500] [5523] [INFO] Listening at: http://127.0.0.1:8000 (5523)
[2015-02-08 19:40:37 -0500] [5523] [INFO] Using worker: sync
[2015-02-08 19:40:37 -0500] [5526] [INFO] Booting worker with pid: 5526
[2015-02-08 19:40:37 -0500] [5527] [INFO] Booting worker with pid: 5527
[2015-02-08 19:40:37 -0500] [5528] [INFO] Booting worker with pid: 5528
^C[2015-02-09 00:40:39 +0000] [5526] [INFO] Worker exiting (pid: 5526)
[2015-02-09 00:40:39 +0000] [5527] [INFO] Worker exiting (pid: 5527)
[2015-02-09 00:40:39 +0000] [5528] [INFO] Worker exiting (pid: 5528)
[2015-02-08 19:40:39 -0500] [5523] [INFO] Handling signal: int
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 1875, in shutdown
    h.close()
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py", line 885, in close
    if self._name and self._name in _handlers:
  File "REDACTED/lib/python3.4/site-packages/gunicorn/workers/base.py", line 151, in handle_quit
    sys.exit(0)
SystemExit: 0
[2015-02-08 19:40:39 -0500] [5523] [INFO] Shutting down: Master
```

While trying to track down where in the source the issue might be, I discovered something strange. In `arbiter.py` -> `class Arbiter(object):` -> `def spawn_worker(self):`, if I insert a short delay after `self.cfg.worker_exit(self, worker)`, I do not get the dialog.

```
        finally:
            self.log.info("Worker exiting (pid: %s)", worker_pid)
            try:
                worker.tmp.close()
                self.cfg.worker_exit(self, worker)
                time.sleep(0.1)
            except:
                pass
```

I'm not sure what could be the problem here, or why it is crashing python itself, but I'm guessing it's a race condition. I would greatly appreciate any assistance in further tracking down what the root of the problem could be.

**Comment by AlexanderOMara** [comment]
Some more information as I continue to try to debug this issue. I've tried running it with the `--log-level=debug` command line argument, and I also do not get the Python crash.
```
$ gunicorn hello.wsgi:application --bind localhost:8000 --log-level=debug
$ gunicorn hello.wsgi:application --bind localhost:8000 --log-level=debug
[2015-02-10 23:42:24 -0500] [21085] [DEBUG] Current configuration:
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x10440da60>
  django_settings: None
  do_handshake_on_connect: False
  timeout: 30
  worker_tmp_dir: None
  umask: 0
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  errorlog: -
  default_proc_name: hello.wsgi:application
  syslog_addr: unix:///var/run/syslog
  check_config: False
  proxy_allow_ips: ['127.0.0.1']
  limit_request_fields: 100
  worker_connections: 1000
  graceful_timeout: 30
  keepalive: 2
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x104406f28>
  worker_exit: <function WorkerExit.worker_exit at 0x10440d8c8>
  daemon: False
  limit_request_line: 4094
  spew: False
  ssl_version: 3
  loglevel: debug
  statsd_host: None
  statsd_prefix:
  ca_certs: None
  proc_name: None
  worker_int: <function WorkerInt.worker_int at 0x10440d158>
  preload_app: False
  post_request: <function PostRequest.post_request at 0x10440d730>
  on_exit: <function OnExit.on_exit at 0x10440dbf8>
  syslog_prefix: None
  user: 501
  config: None
  paste: None
  reload: False
  proxy_protocol: False
  backlog: 2048
  ciphers: TLSv1
  bind: ['localhost:8000']
  worker_class: sync
  threads: 1
  on_starting: <function OnStarting.on_starting at 0x104406730>
  post_fork: <function Postfork.post_fork at 0x104406d90>
  pre_exec: <function PreExec.pre_exec at 0x10440d488>
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  logger_class: gunicorn.glogging.Logger
  syslog_facility: user
  enable_stdio_inheritance: False
  pre_request: <function PreRequest.pre_request at 0x10440d620>
  certfile: None
  chdir: /Users/main/Sites/django/gunicornpy3/hello
  raw_env: []
  pidfile: None
  pythonpath: None
  keyfile: None
  suppress_ragged_eofs: True
  on_reload: <function OnReload.on_reload at 0x1044068c8>
  limit_request_field_size: 8190
  when_ready: <function WhenReady.when_ready at 0x104406a60>
  worker_abort: <function WorkerAbort.worker_abort at 0x10440d2f0>
  max_requests: 0
  max_requests_jitter: 0
  sendfile: True
  tmp_upload_dir: None
  cert_reqs: 0
  accesslog: None
  logconfig: None
  syslog: False
  workers: 1
  group: 20
  pre_fork: <function Prefork.pre_fork at 0x104406bf8>
[2015-02-10 23:42:24 -0500] [21085] [INFO] Starting gunicorn 19.2.1
[2015-02-10 23:42:24 -0500] [21085] [DEBUG] Arbiter booted
[2015-02-10 23:42:24 -0500] [21085] [INFO] Listening at: http://127.0.0.1:8000 (21085)
[2015-02-10 23:42:24 -0500] [21085] [INFO] Using worker: sync
[2015-02-10 23:42:24 -0500] [21088] [INFO] Booting worker with pid: 21088
[2015-02-10 23:42:24 -0500] [21085] [DEBUG] 1 workers
[2015-02-10 23:42:25 -0500] [21085] [DEBUG] 1 workers
[2015-02-10 23:42:26 -0500] [21085] [DEBUG] 1 workers
^C[2015-02-10 23:42:26 -0500] [21085] [DEBUG] 1 workers
[2015-02-11 04:42:26 +0000] [21088] [INFO] Worker exiting (pid: 21088)
[2015-02-10 23:42:26 -0500] [21085] [INFO] Handling signal: int
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/weakref.py", line 552, in _exitfunc
    import gc
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2164, in _find_spec
  File "<frozen importlib._bootstrap>", line 1271, in find_spec
  File "<frozen importlib._bootstrap>", line 871, in spec_from_loader
  File "<frozen importlib._bootstrap>", line 547, in _requires_builtin_wrapper
  File "REDACTED/lib/python3.4/site-packages/gunicorn/workers/base.py", line 151, in handle_quit
    sys.exit(0)
SystemExit: 0
[2015-02-10 23:42:26 -0500] [21085] [INFO] Shutting down: Master
```
Again, the traceback in the output is inconsistent between runs. Hopefully I can assistance on this.

**Comment by tilgovi** [comment]
My first thought is that this is similar to #910.
My next thought is that, no, maybe it's that the worker receives the QUIT signal, starts to shut down including closing loggers, then receives the KILL signal. Or something to this effect.

**Comment by AlexanderOMara** [comment]
Hmm, anything I can do to try to debug the issue?
